---
title: "datatables"
author: "Bagi Laura"
date: "2023-10-16"
output: html_document
---

```{r}

#Librarys
library(ggplot2)
library(ggpubr)
library(match2C)
library(dplyr)
library(plyr)
library(tidyr)
library(readxl)
library(forcats)
library(survival)
library(survminer)

#UKB Datas all in 1
year_of_birth = read.table("", header = T) #34
month_of_birth= read.table("", header = T) #52
ukb_datas_all_in_1=data.frame(eid= year_of_birth$eid)
df_births = data.frame(eid=year_of_birth$eid, year=year_of_birth$value, 
                       month= month_of_birth$value[match(month_of_birth$eid, year_of_birth$eid)], 
                       day= 15)
df_births$birthdate = paste(df_births$year,
                  df_births$month,
                  df_births$day,
                  sep = "-")
df_births$birthdate=as.Date(df_births$birthdate)
df_births$birthdate = format(df_births$birthdate, "%Y-%m-%d")
ukb_datas_all_in_1$birthdate= df_births$birthdate[match(df_births$eid, ukb_datas_all_in_1$eid)]
rm(year_of_birth, month_of_birth, df_births)

sex = read.table("", header = T) #31
ukb_datas_all_in_1$sex = sex$value[match(sex$eid, ukb_datas_all_in_1$eid)]
rm(sex)

ethnic = read.table("", header = T) #21000
dataframe_ethnic = pivot_wider(data = ethnic, id_cols = eid, names_from = UKB_column_name, values_from = value)
colnames(dataframe_ethnic)=c("eid", "ethnic_1", "ethnic_2", "ethnic_3", "ethnic_4")
ukb_datas_all_in_1 = cbind(ukb_datas_all_in_1, dataframe_ethnic[match(ukb_datas_all_in_1$eid, dataframe_ethnic$eid), c("ethnic_1", "ethnic_2", "ethnic_3", "ethnic_4")])
rm(ethnic, dataframe_ethnic)

date_of_attendings = read.table("", header = T) #53
attendings = pivot_wider(date_of_attendings, id_cols = eid, names_from = UKB_column_name, values_from = value)
colnames(attendings)=c("eid", "attending_1", "attending_3", "attending_4", "attending_2")
ukb_datas_all_in_1 = cbind(ukb_datas_all_in_1, attendings[match(ukb_datas_all_in_1$eid, attendings$eid), c("attending_1", "attending_2", "attending_3", "attending_4")])
rm(date_of_attendings, attendings)

#paste("attending", 1:10, sep = "_")
#paste0("attending", 1:10)
#paste("attending", 1:10, sep = "_", collapse = ",")

age_of_cancer_diag=read.table("", header = T)#40008
ukb_datas_all_in_1$Cancer.Diag.Age= age_of_cancer_diag$value[match(ukb_datas_all_in_1$eid, age_of_cancer_diag$eid)]
rm(age_of_cancer_diag)


date_of_death= read.table("", header = T) #40000
ukb_datas_all_in_1$date_of_death = date_of_death$value[match(ukb_datas_all_in_1$eid, date_of_death$eid, nomatch = NA)]
ukb_datas_all_in_1$death= !is.na(ukb_datas_all_in_1$date_of_death)

rm(date_of_death)

p_cause_of_death = read.table("", header = T) #40001
ukb_datas_all_in_1$cause_of_death = p_cause_of_death$value[match(ukb_datas_all_in_1$eid, p_cause_of_death$eid, nomatch = NA)]
rm(p_cause_of_death)

reported_occurences = read.table("", header = T) #40009
ukb_datas_all_in_1$c.occurences= reported_occurences$value[match(ukb_datas_all_in_1$eid, reported_occurences$eid, nomatch = NA)]
rm(reported_occurences)


```
#Cancer codes
```{r}
histology_of_cancer = read.table("", header = T) #40011
type_of_cancer = read.table("", header = T) #40006
date_of_cancer_diag = read.table("", header = T) #40005

cancer_data = lapply(X = unique(histology_of_cancer$eid),FUN=function(x){
   temp_df=histology_of_cancer[histology_of_cancer$eid==x,]
   temp_df$cnid= substr(x = temp_df$UKB_column_name, start = 7, stop = 10)
   tempdf_2=type_of_cancer[type_of_cancer$eid==x,]
   tempdf_2$cnid= substr(x = tempdf_2$UKB_column_name, start = 7, stop = 10)
   tempdf_3=date_of_cancer_diag[date_of_cancer_diag$eid==x,]
   tempdf_3$cnid=substr(x = tempdf_3$UKB_column_name, start = 7, stop = 10)
   cancer_codes_df=left_join(x = temp_df, y = tempdf_2,  by = "cnid")
   cancer_codes_df= left_join(x = cancer_codes_df, y = tempdf_3, by="cnid")
   cancer_codes_df=cancer_codes_df[,c(1,10,7,3)]
   colnames(cancer_codes_df)= c("eid", "date","ICD10", "histology")
   cancer_codes_df
})
rm(date_of_cancer_diag, histology_of_cancer, type_of_cancer)
cancer_data = do.call(rbind, cancer_data)
cancer_data = unite(cancer_data,col = "ICD_hist", c("ICD10", "histology") ,sep = "_", remove = F )
cancer_data$birthdate = ukb_datas_all_in_1$birthdate[match(cancer_data$eid, ukb_datas_all_in_1$eid)]
cancer_data$time = apply(X = cancer_data, MARGIN = 1, FUN = function(x){
  as.Date(as.character(x[2]))-as.Date(as.character(x[6]))
})
colnames(cancer_data)[colnames(cancer_data)=="date"] = "diag_date"

#Only cancer datas
sex = read.table("", header = T) #31
cancer_data$sex = sex$value[match(cancer_data$eid, sex$eid)]
rm(sex)
ethnic = read.table("", header = T) #21000
dataframe_ethnic = pivot_wider(data = ethnic, id_cols = eid, names_from = UKB_column_name, values_from = value)
colnames(dataframe_ethnic)=c("eid", "ethnic_1", "ethnic_2", "ethnic_3", "ethnic_4")
cancer_data= cbind(cancer_data, dataframe_ethnic[match(cancer_data$eid, dataframe_ethnic$eid),c("ethnic_1", "ethnic_2", "ethnic_3", "ethnic_4")])
rm(ethnic, dataframe_ethnic)
date_of_attendings = read.table("", header = T) #53
attendings = pivot_wider(date_of_attendings, id_cols = eid, names_from = UKB_column_name, values_from = value)
colnames(attendings)=c("eid", "attending_1", "attending_3", "attending_4", "attending_2")
cancer_data= cbind(cancer_data, attendings[match(cancer_data$eid, attendings$eid), c("attending_1", "attending_2", "attending_3", "attending_4")])
rm(date_of_attendings, attendings)
age_of_cancer_diag=read.table("", header = T)#40008
cancer_data$age_of_cancer.diag= age_of_cancer_diag$value[match(cancer_data$eid, age_of_cancer_diag$eid)]
rm(age_of_cancer_diag)
date_of_death= read.table("", header = T) #40000
cancer_data$date_of_death=date_of_death$value[match(cancer_data$eid, date_of_death$eid)]
cancer_data$death= !is.na(cancer_data$date_of_death)
rm(date_of_death)
p_cause_of_death = read.table("", header = T) #40001
cancer_data$cause_of_death= p_cause_of_death$value[match(cancer_data$eid, p_cause_of_death$eid)]
rm(p_cause_of_death)
reported_occurences = read.table("", header = T) #40009
cancer_data$r.occurences= reported_occurences$value[match(cancer_data$eid, reported_occurences$eid)]
rm(reported_occurences)
cancer_data = cancer_data[, c(1, 6, 2:21)]
if ("birthdate.1" %in% colnames(cancer_data)) {
  cancer_data=cancer_data[, -which(colnames(cancer_data) == "birthdate.1")]
}
ukb_datas_all_in_1 = left_join(ukb_datas_all_in_1, cancer_data %>% select(eid, diag_date, ICD_hist, ICD10, histology, time), by = "eid")

#Boxplot
count_data = table(cancer_data$ICD_hist)
more_than_500_data = names(count_data[count_data > 500])
filtered_data = cancer_data[cancer_data$ICD_hist %in% more_than_500_data, ]
filtered_data$ICD_hist= fct_reorder(.f = filtered_data$ICD_hist, .x = filtered_data$time, .fun = median)

tumor_datas = ggplot(filtered_data, aes(x = ICD_hist, y = time)) +
  geom_boxplot(varwidth = T) +
   labs(title = "Tumor datas",
       x = "ICD10_histology",
       y = "Duration in days") +
   theme_classic()+
   theme(axis.text.x = element_text(angle = 90))
print(tumor_datas)

#ICD10, histology codes
ICD10_codes = read_xlsx("")
ICD10_codes_clean = ICD10_codes %>%
  select(CODE, `LONG DESCRIPTION (VALID ICD-10 FY2023)`)
rm(ICD10_codes)
ICD10_characters = unique(unlist(strsplit(ICD10_codes_clean$`LONG DESCRIPTION (VALID ICD-10 FY2023)`, split = "")))
ICD10_codes_clean$`LONG DESCRIPTION (VALID ICD-10 FY2023)` = gsub("['.,()-]", "", ICD10_codes_clean$`LONG DESCRIPTION (VALID ICD-10 FY2023)`)
Histology_codes = read_xlsx("")
Histology_codes_clean = Histology_codes %>%
   select(`Site recode`, `Histology/Behavior`, `Histology/Behavior Description`)
Histology_character =unique(unlist(strsplit(Histology_codes$`Histology/Behavior Description`, split = "")))
Histology_codes_clean$`Histology/Behavior Description`= gsub("['.,()-]", "", Histology_codes_clean$`Histology/Behavior Description`)
rm(Histology_codes, Histology_character, ICD10_characters)

```
#Melanoma_incidencia by UKB
```{r}
#plus column: melanoma$c_date=NA, for loop, i->number of rows, filtered table, death col., if true date of death, if false 2023. 11. 14. or melanoma$c_date=current date, melanoma$c_date[meloanoma$death==T] = melanoma$date_of_death[melanoma$death==T]
melanoma=data.frame(eid=unique(ukb_datas_all_in_1$eid),
                    timepoint1=NA,
                    timepoint2=NA,
                    event=NA)
for(i in 1:nrow(ukb_datas_all_in_1)){
   melanoma$eid[i]
   tempdf=ukb_datas_all_in_1[ukb_datas_all_in_1$eid==melanoma$eid[i],]
   melanoma$timepoint1[i]=tempdf$birthdate[1]
   if("C439_8720" %in% tempdf$ICD_hist==TRUE){
      melanoma$timepoint2[i]=tempdf$diag_date[tempdf$ICD_hist=="C439_8720"]
      melanoma$event[i]=1
   }else if("C439_8720" %in% tempdf$ICD_hist==FALSE & tempdf$death[1]==F){
      melanoma$timepoint2[i]="2023.11.14."
      melanoma$event[i]=0
   }else{
      melanoma$timepoint2[i]=tempdf$date_of_death[1]
      melanoma$event[i]=0}
}

melanoma_list =lapply(X = unique(ukb_datas_all_in_1$eid), FUN = function(x){
  tempdf=ukb_datas_all_in_1[ukb_datas_all_in_1$eid==x,]
  timepoint1=tempdf$birthdate[1]
  if("C439_8720" %in% tempdf$ICD_hist==TRUE){
      timepoint2=tempdf$diag_date[tempdf$ICD_hist=="C439_8720"]
      event=1
   }else if("C439_8720" %in% tempdf$ICD_hist==FALSE & tempdf$death[1]==F){
      timepoint2="2023.11.14."
      event=0
   }else{
      timepoint2=tempdf$date_of_death[1]
      event=0}
   c(x, timepoint1, timepoint2, event)
})
melanoma_df=do.call(rbind, melanoma_list)
colnames(melanoma_df)=c("eid", "timepoint1", "timepoint2", "event")




```
#Melanoma by cancer data
```{r}
#first: unique by eid dataframe
#for loop, melanoma_2, malanoma_2$timepoint_1;timepoint_2;event->NA, for(i in 1:nrow(melanoma_2)){}


#melanoma_only=data.frame()
#if ("C439_8720" %in% cancer_data$ICD_hist == TRUE) {#melanoma_only <- subset(cancer_data, ICD_hist == "C439_8720", select = c(eid))}

#for(i in 1:nrow(cancer_data)){x   melanoma_only$eid[i]
   #tempdf=cancer_data[cancer_data$eid==melanoma_only$eid[i],]
   #if("C439_8720" %in% cancer_data$ICD_hist==T){
    #  melanoma_only$timepoint1[i]=tempdf$diag_date[tempdf$ICD_hist=="C439_8720"] 
#   }
#   else if ("C439_8720" %in% tempdf$ICD_hist == TRUE & tempdf$date_of_death[1] == TRUE) {
#    melanoma_only$timepoint2[i] <- tempdf$date_of_death[1]
#    melanoma_only$event[i] <- 1
#  } else if ("C439_8720" %in% tempdf$ICD_hist == TRUE & tempdf$date_of_death[1] == FALSE) {
#    melanoma_only$timepoint2[i] <- "2023.11.14."
#    melanoma_only$event[i] <- 0
#  }
#}

#for (i in 1:nrow(melanoma_only)) {
#   tempdf <- cancer_data[cancer_data$eid == melanoma_only$eid[i], ]
#  if ("C439_8720" %in% tempdf$ICD_hist) {
#    melanoma_only$timepoint1[i] <- ifelse("C439_8720" %in% tempdf$ICD_hist, tempdf$diag_date[tempdf$ICD_hist == "C439_8720"], NA)
    #if (any(tempdf$date_of_death != "")) {
     # melanoma_only$timepoint2[i] <- tempdf$date_of_death[tempdf$date_of_death != ""][1]
      #melanoma_only$event[i] <- 1
   # } else {
    #  melanoma_only$timepoint2[i] <- "2023.11.14."
   # melanoma_only$event[i] <- 0
    #}
  #} else {
   # melanoma_only$timepoint1[i] <- NA
    #melanoma_only$timepoint2[i] <- NA
    #melanoma_only$event[i] <- NA
  #}
#}

melanoma_only=data.frame(eid = character(),
                            timepoint1 = character(),
                            timepoint2 = character(),
                            event = numeric(),
                            stringsAsFactors = FALSE)
unique_eids=unique(cancer_data$eid[cancer_data$ICD_hist == "C439_8720"])
for (eid in unique_eids) {
  tempdf=cancer_data[cancer_data$eid == eid, ]
  timepoint1=tempdf$diag_date[tempdf$ICD_hist=="C439_8720"]
  if (any(!is.na(tempdf$date_of_death) & tempdf$date_of_death != "")) {
    timepoint2=tempdf$date_of_death[!is.na(tempdf$date_of_death) & tempdf$date_of_death != ""][1]
    event=1
  } else {
    timepoint2="2023.11.14."
    event=ifelse(tempdf$death[1], 1, 0)
  }
 melanoma_only=rbind(melanoma_only, c(eid, timepoint1, timepoint2, event))
}
colnames(melanoma_only)=c("eid", "timepoint1", "timepoint2", "event")
   

    
```
Melanoma2 by UKB
```{r}

melanoma_list2 =lapply(X = unique(ukb_datas_all_in_1$eid)) FUN = function(x){
  tempdf=ukb_datas_all_in_1[ukb_datas_all_in_1$eid==x,]
  timepoint1=tempdf$attending_1[1]
  if("C439_8720" %in% tempdf$ICD_hist==TRUE){
      timepoint2=tempdf$diag_date[tempdf$ICD_hist=="C439_8720"]
      event=1
  }else if("C439_8720" %in% tempdf$ICD_hist==FALSE){
      timepoint2="2023.11.14."
      event=0
  }else{("C439_8720" %in% tempdf$ICD_hist==FALSE){
      melanoma$timepoint2[i]="2023.11.14."
      melanoma$event[i]=0 
  }
     }
}


melanoma2=data.frame(eid=unique(ukb_datas_all_in_1$eid),
                    timepoint1=NA,
                    timepoint2=NA,
                    event=NA)
for (i in 1:nrow(ukb_datas_all_in_1)) {
  melanoma2$eid[i]
  tempdf = ukb_datas_all_in_1[ukb_datas_all_in_1$eid == melanoma2$eid[i], ]
  melanoma2$timepoint1[i] = tempdf$attending_1[1]
  if ("C439_8720" %in% tempdf$ICD_hist == TRUE){
    melanoma2$timepoint2[i] = tempdf$diag_date[tempdf$ICD_hist == "C439_8720"]
    melanoma2$event[i] = 1
  }else if ("C439_8720" %in% tempdf$ICD_hist == FALSE){
    melanoma2$timepoint2[i] = "2023.11.14."
    melanoma2$event[i] = 0
  }
}






```
Kaplan-Mayer estimate
```{r}
#Melanoma only dataframe, time: date of death(timepoint2)- diag date(timepoint1), event: death 1, not deaht 0.

melanoma_only$time = as.Date(as.character(melanoma_only$timepoint2))-as.Date(as.character(melanoma_only$timepoint))
melanoma_only$time = apply(X = melanoma_only, MARGIN = 1, FUN = function(x){
  as.Date(as.character(x[3]))-as.Date(as.character(x[2]))})
                           

fit_1=survfit(Surv(time, event), data=melanoma_only)
ggsurvplot(fit_1, pval = T, conf.int = T, risk.table = T, surv.median.line = "hv", linetype = "strata",
           xlab="Time in day")

#Incidencia, time: date of diagnosi - birthdate, event: persin has tumor 1, has not 0.

melanoma$time=as.Date(as.character(melanoma$timepoint2)) - as.Date(as.character(melanoma$timepoint1))

fit_2 = survfit(Surv(time, event), data=melanoma)
ggsurvplot(fit_2, pval = T, conf.int = T, surv.median.line = "hv",linetype = "strata",
           xlab="Time ond days")

#Melanoma 2, time= date of diagnosis - first attending, event= has tumor 1, has not 0
melanoma2 = as.Date(as.character(melanoma2$timepoint2)) - as.Date(as.character(melanoma2$timepoint1))
fit_3 = survfit(Surv(time, event), data=melanoma2)
ggsurvplot(fit_3, pval = T, conf.int = T, surv.median.line = "hv",linetype = "strata",
           xlab="Time ond days")





```

