---
title: "002 Cox models Incidence of tumors - CANGEN"
output: html_document
date: "2024-10-15"
---

Tumor and sex separately

#Setup

```{r}
setwd("/media/balazs/WorkL/balazs/Work/UKBiobank/")
library(survival, lib.loc = "/home/balazs/R/x86_64-pc-linux-gnu-library/4.3")
Packages <- c("tidyverse", "data.table", "magrittr", "tidycmprsk", "Rfast", "survminer", "ggsurvfit", "fastmatch", "future.apply", "ComplexHeatmap", "pbapply", "forestmodel", "clusterProfiler", "org.Hs.eg.db", "ggrepel", "ggsci", "scales")
#"fastmatch", "h2o", , , "protr", , , "networkD3", "ggpubr", "RColorBrewer", "Biostrings", , )
lapply(Packages, require, character.only = TRUE)
rm(Packages)
options(dplyr.summarise.inform = FALSE)
options(future.globals.maxSize= 891289600)

pal_npg("nrc")(9)
scales::show_col(pal_npg("nrc")(9))
pal_npg("nrc", alpha = 0.8)(9)
scales::show_col(pal_npg("nrc", alpha = 0.8)(9))
```

#Dataset

```{r}
ukb_data = readRDS("Objects/ukb_data.rds")
ukb_data$cancer_type[ukb_data$cancer_type == "Brain/CNS"] = "Brain"
ukb_data$cancer_type[ukb_data$cancer_type == "Hodgkin lymphoma"] = "HodgkinLymphoma"
ukb_data$cancer_type[ukb_data$cancer_type == "Multiple myeloma"] = "MultipleMyeloma"
ukb_data$cancer_type[ukb_data$cancer_type == "Non-Hodgkin lymphoma"] = "NonHodgkinLymphoma"
ukb_data$sex = factor(ukb_data$sex, levels = c(0,1), labels = c("female", "male"))

ptvs = grep("PTV", colnames(ukb_data), value = T)
ptvs = ptvs[!grepl("Genes", ptvs)]

tumors = sort(unique(ukb_data$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

tumor_freq_data = expand.grid(cancer_type = tumors, sex = c("female", "male"), stringsAsFactors = F)
tumor_freq_data$n = apply(tumor_freq_data, 1, function(x) {
  ukb_data %>% 
    filter(cancer_type == x[1], sex == x[2]) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    nrow()
})
tumor_freq_data %<>% 
  filter(n>=100) %>% 
  mutate(TS = paste(cancer_type, sex, sep = "_"), .before = "n")

nottumorous_all = ukb_data %>% 
  dplyr::filter(cancer_type == "No_cancer") %>%
  distinct(eid, .keep_all = T) %>% 
  mutate(time = case_when(
    death == T ~ as.numeric(date_of_death - birthdate),
    death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
  )) %>% 
  mutate(status = 1)

tumorous_all = ukb_data %>% 
  dplyr::filter(cancer_type %in% tumors) %>% 
  mutate(time = as.numeric((diag_date - birthdate))) %>% 
  mutate(status = 2)

rm(tumors)
```

#Cox models I.
Control for gpca1-10

```{r}
sapply(ptvs, function(x) dir.create(paste0("Plots/003/", x, "/")))

i=0

res = pblapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tumors_coxres = apply(tumor_freq_data, 1, function(t) {
    tumorous = tumorous_all %>% 
      filter(cancer_type == t[1], sex == t[2]) %>% 
      arrange(diag_date) %>% 
      distinct(eid, .keep_all = T)
    nottumorous = nottumorous_all %>% 
      filter(sex == t[2])
    tempdfU = bind_rows(tumorous, nottumorous)
    colnames(tempdfU)[fmatch(p, colnames(tempdfU))] = "PTVvar"
    tempdfU %<>% dplyr::select(eid, time, status, PTVvar, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
    res.cox <- coxph(Surv(time, status) ~ PTVvar + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = tempdfU, id = tempdfU$eid)
    fig = forest_model(model = res.cox)
    ggsave(paste0("Plots/003/", p, "/", t[3], ".jpg"), plot = fig, width = 30, height = 20, units = "cm", dpi = 150)
    as.numeric(rbind(summary(res.cox)$coefficients[,"coef"], summary(res.cox)$coefficients[,"Pr(>|z|)"]))
  })
  out = cbind(tumor_freq_data, ptv_type = p, t(tumors_coxres))
  colnames(out)[seq(6,ncol(out),2)] = c("coef_PTVvar", paste0("coef_gpca", 1:10))
  colnames(out)[seq(7,ncol(out),2)] = c("p_PTVvar", paste0("p_gpca", 1:10))
  out
})
rm(i)

resdf = bind_rows(res)
resdf$p_PTVvarCorr = unlist(lapply(ptvs, function(x) p.adjust(p = resdf$p_PTVvar[resdf$ptv_type == x], method = "BH")), use.names = F) #P-value correction
save(resdf, file = "Res/003/res_cox_model_sepgender")


```

##Heatmap

```{r}
load("Res/003/res_cox_model_sepgender")
ts = unique(resdf$TS)
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(ts), dimnames = list(ptvs, ts))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]] < 0.1, resdf$coef_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(ts), dimnames = list(ptvs, ts))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]] < 0.1, round(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]], digits = 4), NA)
  }
}

png(filename = "Plots/003/Heatmap_cox_model_sepgender_padj.png", width = 40, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })
draw(hm)
dev.off()

```

#Cox model II.
Control for frequent PTV affected TSGs

```{r}
load("Objects/overrep_ft_tsgs_TS01")
ptvs = grep("MAF", ptvs, value = T)

i=0

res = pblapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tumors_coxres = apply(tumor_freq_data, 1, function(t) {
    tumorous = tumorous_all %>% 
      filter(cancer_type == t[1], sex == t[2]) %>% 
      arrange(diag_date) %>% 
      distinct(eid, .keep_all = T)
    nottumorous = nottumorous_all %>% 
      filter(sex == t[2])
    tempdfU = bind_rows(tumorous, nottumorous)
    colnames(tempdfU)[fmatch(p, colnames(tempdfU))] = "PTVvar"
    tempdfU %<>% dplyr::select(eid, time, status, PTVvar, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10, Genes_PTV_MAF)
    
    if(length(overrep_tsgs_ensg[[t[3]]]) > 0) {
      genes = overrep_tsgs_ensg[[t[3]]]
      mat = future_sapply(genes, function(g) {
        grepl(g, tempdfU$Genes_PTV_MAF)
      })
      hugos = overrep_tsgs_hugo[[t[3]]]
      hugos = gsub("-", "_", hugos)
      colnames(mat) = hugos
      tempdfU = cbind(tempdfU, mat)
      rm(mat)
    }
    tempdfU %<>% dplyr::select(-Genes_PTV_MAF)
    gc()
    
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[4:ncol(tempdfU)], collapse = "+")))
    res.cox <- coxph(myformula, data = tempdfU, id = tempdfU$eid)
    fig = forest_model(model = res.cox)
    ggsave(paste0("Plots/003/", p, "/", t[3], "_freqtsgs.jpg"), plot = fig, width = 30, height = 20, units = "cm", dpi = 150)
    as.numeric(rbind(summary(res.cox)$coefficients[,"coef"], summary(res.cox)$coefficients[,"Pr(>|z|)"]))
  })
  m = max(lengths(tumors_coxres))
  tumors_coxres = lapply(tumors_coxres, function(z) {c(z, rep(NA, m-length(z)))})
  out = cbind(tumor_freq_data, ptv_type = p, do.call(rbind,tumors_coxres))
  colnames(out)[seq(6,ncol(out),2)] = c("coef_PTVvar", paste0("coef_gpca", 1:10), paste0("coef_ensg", 1:((m-22)/2)))
  colnames(out)[seq(7,ncol(out),2)] = c("p_PTVvar", paste0("p_gpca", 1:10), paste0("p_ensg", 1:((m-22)/2)))
  out
})
rm(i)

resdf = bind_rows(res)
resdf$p_PTVvarCorr = unlist(lapply(ptvs, function(x) p.adjust(p = resdf$p_PTVvar[resdf$ptv_type == x], method = "BH")), use.names = F) #P-value correction
save(resdf, file = "Res/003/res_cox_model_sepgender_freqtsgs")

```

##Heatmap

```{r}
load("Res/003/res_cox_model_sepgender_freqtsgs")
ts = unique(resdf$TS)
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(ts), dimnames = list(ptvs, ts))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]] < 0.1, resdf$coef_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(ts), dimnames = list(ptvs, ts))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]] < 0.1, round(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]], digits = 4), NA)
  }
}

png(filename = "Plots/003/Heatmap_cox_model_sepgender_freqtsgs_padj.png", width = 30, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })
draw(hm)
dev.off()

```

#Exclude patients with PTVs in sign. TSGs

```{r}
load("Objects/overrep_ft_tsgs_TS01")
ptvs = c("PTVtsg_MAF", "PTVtsg_MAF_g")
i=0

res = pblapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tumors_coxres = apply(tumor_freq_data, 1, function(t) {
    tumorous = tumorous_all %>% 
      filter(cancer_type == t[1], sex == t[2]) %>% 
      arrange(diag_date) %>% 
      distinct(eid, .keep_all = T)
    nottumorous = nottumorous_all %>% 
      filter(sex == t[2])
    tempdfU = bind_rows(tumorous, nottumorous)
    colnames(tempdfU)[fmatch(p, colnames(tempdfU))] = "PTVvar"
    tempdfU %<>% dplyr::select(eid, time, status, PTVvar, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10, Genes_PTV_MAF)
    
    if(length(overrep_tsgs_ensg[[t[3]]]) > 0) {
      genes = overrep_tsgs_ensg[[t[3]]]
      mat = future_sapply(genes, function(g) {
        grepl(g, tempdfU$Genes_PTV_MAF)
      })
      keep_ind = apply(mat, 1, function(z) !any(z))
      tempdfU = tempdfU[keep_ind,]
      rm(mat)
    }
    tempdfU %<>% dplyr::select(-Genes_PTV_MAF)
    gc()
    
    res.cox <- coxph(Surv(time, status) ~ PTVvar + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = tempdfU, id = tempdfU$eid)
    fig = forest_model(model = res.cox)
    ggsave(paste0("Plots/003/", p, "/", t[3], "_freqtsgs_filt.jpg"), plot = fig, width = 30, height = 20, units = "cm", dpi = 150)
    as.numeric(rbind(summary(res.cox)$coefficients[,"coef"], summary(res.cox)$coefficients[,"Pr(>|z|)"]))
  })
  out = cbind(tumor_freq_data, ptv_type = p, t(tumors_coxres))
  colnames(out)[seq(6,ncol(out),2)] = c("coef_PTVvar", paste0("coef_gpca", 1:10))
  colnames(out)[seq(7,ncol(out),2)] = c("p_PTVvar", paste0("p_gpca", 1:10))
  out
})
rm(i)

resdf = bind_rows(res)
resdf$p_PTVvarCorr = unlist(lapply(ptvs, function(x) p.adjust(p = resdf$p_PTVvar[resdf$ptv_type == x], method = "BH")), use.names = F) #P-value correction
save(resdf, file = "Res/003/res_cox_model_sepgender_freqtsgs_filt")

```

##Heatmap

```{r}
load("Res/003/res_cox_model_sepgender_freqtsgs_filt")
ts = unique(resdf$TS)
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(ts), dimnames = list(ptvs, ts))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]] < 0.1, resdf$coef_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(ts), dimnames = list(ptvs, ts))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]] < 0.1, round(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$TS == colnames(dataForHm)[j]], digits = 4), NA)
  }
}

png(filename = "Plots/003/Heatmap_cox_model_sepgender_freqtsgs_filt_padj.png", width = 40, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })
draw(hm)
dev.off()

```
