---
title: "002 Cox models Incidence of tumors - CAN"
output: html_document
date: "2024-10-15"
---

#Setup

```{r}
setwd("/media/balazs/WorkL/balazs/Work/UKBiobank/")

library(survival, lib.loc = "/home/balazs/R/x86_64-pc-linux-gnu-library/4.3")
Packages <- c("tidyverse", "data.table", "magrittr", "circlize", "ComplexHeatmap", "org.Hs.eg.db", "future.apply", "fastmatch", "forestmodel", "pbapply", "h2o")
#, "h2o", , , "protr", , , "networkD3", "ggpubr", "RColorBrewer", "Biostrings", "tidycmprsk", "Rfast", "survminer", "ggsurvfit", , , "clusterProfiler", , "ggrepel", "ggsci", "scales")
lapply(Packages, require, character.only = TRUE)
rm(Packages)
options(dplyr.summarise.inform = FALSE)

pal_npg("nrc")(9)
scales::show_col(pal_npg("nrc")(9))
pal_npg("nrc", alpha = 0.8)(9)
scales::show_col(pal_npg("nrc", alpha = 0.8)(9))
```

#Dataset

```{r}
ukb_data = readRDS("Objects/ukb_data.rds")
ukb_data$cancer_type[ukb_data$cancer_type == "Brain/CNS"] = "Brain"
ukb_data$cancer_type[ukb_data$cancer_type == "Hodgkin lymphoma"] = "HodgkinLymphoma"
ukb_data$cancer_type[ukb_data$cancer_type == "Multiple myeloma"] = "MultipleMyeloma"
ukb_data$cancer_type[ukb_data$cancer_type == "Non-Hodgkin lymphoma"] = "NonHodgkinLymphoma"
ukb_data$sex = factor(ukb_data$sex, levels = c(0,1), labels = c("female", "male"))

ptvs = grep("PTV", colnames(ukb_data), value = T)
ptvs = ptvs[grepl("MAF", ptvs)]
ptvs = ptvs[!grepl("Genes", ptvs)]

tumors = sort(unique(ukb_data$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

tumor_freq_data = as.data.frame(table(ukb_data$cancer_type, ukb_data$sex)) %>%
  set_colnames(c("cancer_type", "sex", "n")) %>% 
  mutate_if(is.factor, as.character) %>% 
  filter(cancer_type %in% tumors) %>% 
  pivot_wider(id_cols = cancer_type, names_from = sex, values_from = n) %>% 
  filter(female >= 50, male >= 50)

tumors = tumor_freq_data$cancer_type

nottumorous_all = ukb_data %>% 
  dplyr::filter(cancer_type == "No_cancer") %>%
  distinct(eid, .keep_all = T) %>% 
  mutate(time = case_when(
    death == T ~ as.numeric(date_of_death - birthdate),
    death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
  )) %>% 
  mutate(status = 1)

tumorous_all = ukb_data %>% 
  dplyr::filter(cancer_type %in% tumors) %>% 
  mutate(time = as.numeric((diag_date - birthdate))) %>% 
  mutate(status = 2)

#sapply(tumors, function(x) dir.create(paste0("Plots/002/", x, "/")))

```

#Cox models I.
Predictors: sex, PTV (cont. or cat.), gpca1-10

```{r}
i=0
res = pblapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tumors_coxres = pbsapply(tumors, function(t) {
    tumorous = tumorous_all %>% 
      filter(cancer_type == t) %>% 
      arrange(diag_date) %>% 
      distinct(eid, .keep_all = T)
    tempdfU = bind_rows(tumorous, nottumorous_all)
    colnames(tempdfU)[fmatch(p, colnames(tempdfU))] = "PTVvar"
    tempdfU %<>% dplyr::select(eid, time, status, PTVvar, sex, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
    res.cox <- coxph(Surv(time, status) ~ PTVvar + sex + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = tempdfU, id = tempdfU$eid)
    fig = forest_model(model = res.cox)
    ggsave(paste0("Plots/002/", t, "/cox_fp_", p, "_", t, ".jpg"), plot = fig, width = 30, height = 20, units = "cm", dpi = 150)
    as.numeric(rbind(summary(res.cox)$coefficients[,"coef"], summary(res.cox)$coefficients[,"Pr(>|z|)"]))
  })
  out = cbind(tumor_freq_data, ptv_type = p, t(tumors_coxres))
  colnames(out)[seq(5,ncol(out),2)] = c("coef_PTVvar", "coef_sexmale", paste0("coef_gpca", 1:10))
  colnames(out)[seq(6,ncol(out),2)] = c("p_PTVvar", "p_sexmale", paste0("p_gpca", 1:10))
  out
})


resdf = bind_rows(res)
resdf$p_PTVvarCorr = unlist(lapply(ptvs, function(x) p.adjust(p = resdf$p_PTVvar[resdf$ptv_type == x], method = "BH")), use.names = F) #P-value correction
save(resdf, file = "Res/002/res_cox_model_withgender")


# rf = h2o.randomForest(x = c("time", "PTVvar", "sex", "gpca1", "gpca2", "gpca3", "gpca4", "gpca5", "gpca6", "gpca7", "gpca8", "gpca9", "gpca10"),
#                       y = "status",
#                       training_frame = train, 
#                       validation_frame = valid,
#                       seed = 123, 
#                       nfolds = 5,
#                       balance_classes = T)

```

##Heatmap - based on corrected p (<0.1)

```{r}
load("Res/002/res_cox_model_withgender")

tumors = unique(resdf$cancer_type)
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.1, resdf$coef_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.1, round(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], digits = 4), NA)
  }
}

png(filename = "Plots/002/Heatmap_cox_model_withgender_padj.png", width = 30, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })
draw(hm)
dev.off()
```

##Heatmap - based on raw p (<0.05)

```{r}
load("Res/002/res_cox_model_withgender")

tumors = unique(resdf$cancer_type)
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.05, resdf$coef_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.05, round(resdf$p_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], digits = 4), NA)
  }
}

png(filename = "Plots/002/Heatmap_cox_model_withgender_rawP.png", width = 30, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })
draw(hm)
dev.off()

```

#Cox models II.

```{r}
load("Objects/overrep_ft_01_tsgs_tumors")
rm(ukb_data)

i=0
res = pblapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tumors_coxres = pbsapply(tumors, function(t) {
    tumorous = tumorous_all %>% 
      filter(cancer_type == t) %>% 
      arrange(diag_date) %>% 
      distinct(eid, .keep_all = T)
    tempdfU = bind_rows(tumorous, nottumorous_all)
    colnames(tempdfU)[fmatch(p, colnames(tempdfU))] = "PTVvar"
    tempdfU %<>% dplyr::select(eid, time, status, PTVvar, sex, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10, Genes_PTV_MAF)
    
    if(length(overrep_tsgs_ensg[[t]]) > 0) {
      genes = overrep_tsgs_ensg[[t]]
      mat = future_sapply(genes, function(g) {
        grepl(g, tempdfU$Genes_PTV_MAF)
      })
      hugos = overrep_tsgs_hugo[[t]]
      hugos = gsub("-", "_", hugos)
      colnames(mat) = hugos
      tempdfU = cbind(tempdfU, mat)
      rm(mat)
    }
    tempdfU %<>% dplyr::select(-Genes_PTV_MAF)
    gc()
    
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[4:ncol(tempdfU)], collapse = "+")))
    res.cox <- coxph(myformula, data = tempdfU, id = tempdfU$eid)
    
    fig = forest_model(model = res.cox)
    ggsave(paste0("Plots/002/", t, "/cox_fp_", p, "_", t, "_freqtsgs.jpg"), plot = fig, width = 20, height = 30, units = "cm", dpi = 150)
    as.numeric(rbind(summary(res.cox)$coefficients[,"coef"], summary(res.cox)$coefficients[,"Pr(>|z|)"]))
  })
  m = max(lengths(tumors_coxres))
  tumors_coxres = lapply(tumors_coxres, function(z) {c(z, rep(NA, m-length(z)))})
  
  out = cbind(tumor_freq_data, ptv_type = p, do.call(rbind,tumors_coxres))
  colnames(out)[seq(5,ncol(out),2)] = c("coef_PTVvar", "coef_sexmale", paste0("coef_gpca", 1:10), paste0("coef_ensg", 1:((ncol(out)-28)/2)))
  colnames(out)[seq(6,ncol(out),2)] = c("p_PTVvar", "p_sexmale", paste0("p_gpca", 1:10), paste0("p_ensg", 1:((ncol(out)-28)/2)))
  out$p_PTVvarCorr = p.adjust(p = out$p_PTVvar, method = "BH")
  rownames(out) = NULL
  out
})

resdf = bind_rows(res)
save(resdf, file = "Res/002/res_cox_model_withgender_freqtsgs")

```


##Heatmap - based on corrected p (<0.1)

```{r}
load("Res/002/res_cox_model_withgender_freqtsgs")

tumors = unique(resdf$cancer_type)
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.1, resdf$coef_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.1, round(resdf$p_PTVvarCorr[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], digits = 4), NA)
  }
}

png(filename = "Plots/002/Heatmap_cox_model_withgender_freqtsgs_padj.png", width = 30, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })
draw(hm)
dev.off()

```

##Heatmap - based on raw p (<0.05)

```{r}
load("Res/002/res_cox_model_withgender_freqtsgs")

tumors = unique(resdf$cancer_type)
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.05, resdf$coef_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.05, round(resdf$p_PTVvar[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], digits = 4), NA)
  }
}

png(filename = "Plots/002/Heatmap_cox_model_withgender_freqtsgs_rawP.png", width = 30, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })
draw(hm)
dev.off()

```

