---
title: "B_000_Create_subdatasets"
output: html_document
date: "2025-02-25"
---

#Setup

```{r}
setwd("/media/balazs/WorkL/balazs/Work/UKBiobank/")
#library(survival, lib.loc = "/home/balazs/R/x86_64-pc-linux-gnu-library/4.3")
Packages <- c("tidyverse", "fastmatch", "data.table", "magrittr")
#"survival", "pbapply", "forestmodel", "gridExtra", , , "clusterProfiler", "org.Hs.eg.db", "hgnc", "future.apply", , "Rfast", , , , , "tidycmprsk", , "survminer", "ggsurvfit", , , "ComplexHeatmap", , , , "ggrepel", "ggsci", "scales", , "circlize" "fastmatch", "h2o", , , "protr", , , "networkD3", "ggpubr", , "Biostrings", , )
lapply(Packages, require, character.only = TRUE)
rm(Packages)
options(dplyr.summarise.inform = FALSE)

# pal_npg("nrc")(9)
# scales::show_col(pal_npg("nrc")(9))
# pal_npg("nrc", alpha = 0.8)(9)
# scales::show_col(pal_npg("nrc", alpha = 0.8)(9))
```


#Tumorous datasets

```{r}
ukb_data_raw = readRDS("Objects/ukb_data.rds")
geg = fread("Variables/22006.txt") #caucasians
ukb_dataF = ukb_data_raw %>% filter(eid %fin% as.character(geg$eid)) #425,654 - only caucasians
rm(geg)

ukb_dataF %<>% filter(s.color != "Black") #425,530 - exclude black color skin

ukb_dataF$sex = factor(ukb_dataF$sex, levels = c(0,1), labels = c("female", "male"))

#Death type
load("Objects/icd_mapping")
ukb_dataF$death_type = icd_mapping$cancer_type[fmatch(substr(ukb_dataF$cause_of_death,1,3), icd_mapping$ICD10)]
#Some controversial patients
ukb_dataF %>% filter(cancer_type == "No_cancer") %>% filter(substr(cause_of_death,1,1) == "C") %>% nrow()
ukb_dataF %>% filter(cancer_type == "No_cancer") %>% filter(substr(cause_of_death,1,1) == "C") %>% pull(eid) -> tempeids
View(ukb_dataF[ukb_dataF$eid %fin% tempeids, c(1:23,64:86)])
View(table(ukb_dataF$death_type[ukb_dataF$eid %fin% tempeids]))
ukb_dataF %<>% filter(!eid %in% tempeids) #424,260
rm(tempeids, icd_mapping)
View(ukb_dataF[, c(1:23,64:86)])

ukb_dataF$cancer_type = gsub("/| |-", "", ukb_dataF$cancer_type)
ukb_dataF$death_type = gsub("/| |-", "", ukb_dataF$death_type)

sel_gpcas = paste0("gpca", 1:40)
ukb_dataF %<>% dplyr::select(eid, birthdate, sex, death, date_of_death, cause_of_death, death_type, diag_date, cancer_type, all_of(sel_gpcas)) #424,260 #49 columns
ukb_dataF %<>% filter_at(.vars = vars(starts_with("gpca")), .vars_predicate = any_vars(!is.na(.))) #424,260
rm(sel_gpcas)
```

#Non-tumorous dataset

```{r}
nottumorous_all = ukb_dataF %>% dplyr::filter(cancer_type == "No_cancer")
length(unique(nottumorous_all$eid)) == nrow(nottumorous_all)
#mutate(time = case_when(
#    death == T ~ as.numeric(date_of_death - birthdate),
#    death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
#  ))
nottumorous_female = ukb_dataF %>% dplyr::filter(cancer_type == "No_cancer", sex == "female")
nottumorous_male = ukb_dataF %>% dplyr::filter(cancer_type == "No_cancer", sex == "male")
saveRDS(nottumorous_all, file = "Objects/000_Sub_datasets/nottumorous_all.rds")
saveRDS(nottumorous_female, file = "Objects/000_Sub_datasets/nottumorous_female.rds")
saveRDS(nottumorous_male, file = "Objects/000_Sub_datasets/nottumorous_male.rds")
rm(nottumorous_all, nottumorous_female, nottumorous_male)
```

#Tumorous

```{r}
tumors = sort(unique(ukb_dataF$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

tumor_freq_data = expand.grid(cancer_type = tumors, sex = c("female", "male"), stringsAsFactors = F)
tumor_freq_data$n = apply(tumor_freq_data, 1, function(x) {
  ukb_dataF %>% 
    filter(cancer_type == x[1], sex == x[2]) %>% 
    pull(eid) %>% 
    unique() %>% 
    length()
})
tumor_freq_data %<>% 
  filter(n>=100) %>% 
  mutate(TS = paste(cancer_type, sex, sep = "_"), .before = "n") #42
save(tumor_freq_data, file = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/tumor_freq_data")

tumorous_all = ukb_dataF %>% 
  dplyr::filter(cancer_type %in% tumors)
# tumorous_all$death_type[is.na(tumorous_all$death_type)] = "untyped"
# tdf = tumorous_all[tumorous_all$eid %in% tumorous_all$eid[duplicated(tumorous_all$eid)],]
# tdf %>% group_by(eid, death_type,) %>% summarise(n = n()) %>% View() #7853
# tdf %>% group_by(eid, death_type,) %>% summarise(n = n()) %>% pull(eid) %>% unique() %>% length()
# rm(tdf)

tumorous_all %<>% 
  arrange(diag_date) %>% 
  distinct(eid, .keep_all = T)

#  mutate(time = as.numeric((diag_date - birthdate))) %>% 
#  mutate(status = 2)

tumorous_female = ukb_dataF %>% dplyr::filter(cancer_type %in% tumors, sex == "female") %>% arrange(diag_date) %>% distinct(eid, .keep_all = T)
tumorous_male = ukb_dataF %>% dplyr::filter(cancer_type %in% tumors, sex == "male") %>% arrange(diag_date) %>% distinct(eid, .keep_all = T)

saveRDS(tumorous_all, file = "Objects/000_Sub_datasets/tumorous_all.rds")
saveRDS(tumorous_female, file = "Objects/000_Sub_datasets/tumorous_female.rds")
saveRDS(tumorous_male, file = "Objects/000_Sub_datasets/tumorous_male.rds")
rm(tumorous_all, tumorous_female, tumorous_male)
```

##Tumors separately

```{r}
lapply(tumors, function(t) {
  tumorous = ukb_dataF %>% dplyr::filter(cancer_type == t) %>% arrange(diag_date) %>% distinct(eid, .keep_all = T)
  saveRDS(tumorous, file = paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", t, ".rds"))
})

```

#Gender-tumor pairs
##Dataset creation

```{r}
apply(tumor_freq_data, 1, function(ts) {
  tumorous = ukb_dataF %>% filter(cancer_type == ts[1], sex == ts[2]) %>% arrange(diag_date) %>% distinct(eid, .keep_all = T)
  saveRDS(tumorous, file = paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", ts[3], ".rds"))
})

```
