---
title: "B_014_Tumor_incidence_all_GO_terms"
output: html_document
date: "2024-12-12"
---

#Setup

```{r}
setwd("/media/balazs/WorkL/balazs/Work/UKBiobank/")
#library(survival, lib.loc = "/home/balazs/R/x86_64-pc-linux-gnu-library/4.3")
Packages <- c("tidyverse", "data.table", "magrittr", "Rfast", "fastmatch", "future.apply", "survival", "gridExtra", "pbapply", "forestmodel")
#"tidycmprsk", , "survminer", "ggsurvfit", , , "ComplexHeatmap", , , "clusterProfiler", "org.Hs.eg.db", "ggrepel", "ggsci", "scales", , "circlize" "fastmatch", "h2o", , , "protr", , , "networkD3", "ggpubr", , "Biostrings", , )
lapply(Packages, require, character.only = TRUE)
rm(Packages)
options(dplyr.summarise.inform = FALSE)

# pal_npg("nrc")(9)
# scales::show_col(pal_npg("nrc")(9))
# pal_npg("nrc", alpha = 0.8)(9)
# scales::show_col(pal_npg("nrc", alpha = 0.8)(9))
```

#Gender-tumor pairs
##Dataset creation

```{r}
ukb_data_raw = readRDS("Objects/ukb_data.rds")
geg = fread("Variables/22006.txt") #caucasians
ukb_dataF = ukb_data_raw %>% filter(eid %fin% as.character(geg$eid)) #425,654
rm(geg)

ukb_dataF %<>% filter(s.color != "Black") #425,530

ukb_dataF$sex = factor(ukb_dataF$sex, levels = c(0,1), labels = c("female", "male"))
sel_gpcas = paste0("gpca", 1:20)

ukb_dataF$cancer_type[ukb_dataF$cancer_type == "Brain/CNS"] = "Brain"
ukb_dataF$cancer_type[ukb_dataF$cancer_type == "Hodgkin lymphoma"] = "HodgkinLymphoma"
ukb_dataF$cancer_type[ukb_dataF$cancer_type == "Multiple myeloma"] = "MultipleMyeloma"
ukb_dataF$cancer_type[ukb_dataF$cancer_type == "Non-Hodgkin lymphoma"] = "NonHodgkinLymphoma"

ukb_dataF %<>% dplyr::select(eid, birthdate, sex, date_of_death, death, diag_date, cancer_type, all_of(sel_gpcas))
ukb_dataF %<>% filter_at(.vars = vars(starts_with("gpca")), .vars_predicate = any_vars(!is.na(.)))

tumors = sort(unique(ukb_dataF$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

tumor_freq_data = expand.grid(cancer_type = tumors, sex = c("female", "male"), stringsAsFactors = F)
tumor_freq_data$n = apply(tumor_freq_data, 1, function(x) {
  ukb_dataF %>% 
    filter(cancer_type == x[1], sex == x[2]) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    nrow()
})
tumor_freq_data %<>% 
  filter(n>=100) %>% 
  mutate(TS = paste(cancer_type, sex, sep = "_"), .before = "n") #42
save(tumor_freq_data, file = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/tumor_freq_data")
tumors = unique(tumor_freq_data$cancer_type) #25

nottumorous_all = ukb_dataF %>% 
  dplyr::filter(cancer_type == "No_cancer") %>%
  distinct(eid, .keep_all = T) %>% 
  mutate(time = case_when(
    death == T ~ as.numeric(date_of_death - birthdate),
    death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
  )) %>% 
  mutate(status = 1)

tumorous_all = ukb_dataF %>% 
  dplyr::filter(cancer_type %in% tumors) %>% 
  mutate(time = as.numeric((diag_date - birthdate))) %>% 
  mutate(status = 2)

rm(tumors, ukb_data_raw, ukb_dataF)
intersect(tumorous_all$eid, nottumorous_all$eid)

# apply(tumor_freq_data, 1, function(ts) {
#     tumorous = tumorous_all %>% 
#       filter(cancer_type == ts[1], sex == ts[2]) %>% 
#       arrange(diag_date) %>% 
#       distinct(eid, .keep_all = T)
#     nottumorous = nottumorous_all %>% 
#       filter(sex == ts[2])
#     tempdfU = bind_rows(tumorous, nottumorous)
#     saveRDS(tempdfU, file = paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/dfs/", ts[3], ".rds"))
# })
rm(nottumorous_all, tumorous_all, sel_gpcas)
```

##Cox model

```{r}
load("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/tumor_freq_data")
ptvb_MAF104 = fread("PTVvars/MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv")
ptv_dataDF = data.frame(eid = ptvb_MAF104$Patient.ID)
rm(ptvb_MAF104)

goID = list.files("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/013/PTV_GO/")
goID = gsub(".rds", "", goID)

plan(multisession(workers = 8))

for(i in 1631:length(goID)) {
  print(paste0(i, "_", Sys.time()))
  ptv_data = readRDS(paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/013/PTV_GO/", goID[i], ".rds"))
  ptv_dataDF$PTV = ptv_data
  coxres = future_apply(tumor_freq_data, 1, function(ts) {
    tempdfU = readRDS(paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/dfs/", ts[3], ".rds"))
    ukb = tempdfU %>% left_join(ptv_dataDF, by = "eid")
    ukb$PTVG = ifelse(ukb$PTV == 0, 0, 1)
    if(length(unique(ukb$PTVG)) > 1) {ukb$PTVG = as.factor(ukb$PTVG)}
    res.cox <- coxph(Surv(time, status) ~ PTVG + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10 + gpca11 + gpca12 + gpca13 + gpca14 + gpca15 + gpca16 + gpca17 + gpca18 + gpca19 + gpca20, data = ukb, id = ukb$eid)
    o = as.numeric(rbind(summary(res.cox)$coefficients[,"exp(coef)"], summary(res.cox)$coefficients[,"Pr(>|z|)"]))
  })
  out = cbind(tumor_freq_data, ptv_type = goID[i], t(coxres))
  colnames(out)[seq(6,ncol(out),2)] = c("coefPTV", paste0("coef_gpca", 1:20))
  colnames(out)[seq(7,ncol(out),2)] = c("pPTVG", paste0("p_gpca", 1:20))
  out$padjPTVG = p.adjust(out$pPTVG, method = "fdr")
  saveRDS(object = out, file = paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/coxres/", goID[i], ".rds"))
  gc()
}
rm(coxres, out, i, ptv_data)

```

#Results

```{r}
goID = list.files("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/coxres/")
goID = gsub(".rds", "", goID)
res = bind_rows(lapply(1:length(goID), function(i) {
  dat = readRDS(paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/coxres/", goID[i], ".rds"))
  dat
}))
res$goInd = as.character(sapply(res$ptv_type, function(x) strsplit(x, "_")[[1]][1]))
load("Objects/go_desc_list")
go_desc_list = go_desc_list[lengths(go_desc_list) >= 5] #7462
res$genes = sapply(res$goInd, function(x) paste0(go_desc_list[[as.numeric(x)]], collapse = ";"))
res$goInd = as.numeric(res$goInd)

# ind = res %>% filter(padjPTVG < 0.05) %>% pull(goInd) %>% unique() %>% as.numeric()
# sort(unique(unlist(go_desc_list[ind], use.names = F)))
res %>% filter(padjPTVG < 0.05) %>% pull(ptv_type) %>% table() %>% as.data.frame() %>% View()
res %>% filter(cancer_type == "Melanoma") %>% filter(pPTVG < 0.05) %>% View()

#ts = unique(res$TS)
#Cox model, forest plot
ptvb_MAF104 = fread("PTVvars/MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv")
ptv_dataDF = data.frame(eid = ptvb_MAF104$Patient.ID)
rm(ptvb_MAF104)

MelSign = res %>% filter(cancer_type == "Melanoma") %>% filter(pPTVG < 0.01) %>% arrange(padjPTVG)

plots = pbapply(MelSign[,c("TS", "ptv_type", "goInd")], 1, function(x) {
  ptv_data = readRDS(paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/013/PTV_GO/", x[2], ".rds"))
  ptv_dataDF$PTV = ptv_data
  tempdfU = readRDS(paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/dfs/", x[1], ".rds"))
  ukb = tempdfU %>% left_join(ptv_dataDF, by = "eid")
  ukb$PTVG = ifelse(ukb$PTV == 0, 0, 1)
  ukb$PTVG = as.factor(ukb$PTVG)
  res.cox <- coxph(Surv(time, status) ~ PTVG + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10 + gpca11 + gpca12 + gpca13 + gpca14 + gpca15 + gpca16 + gpca17 + gpca18 + gpca19 + gpca20, 
                   data = ukb, 
                   id = ukb$eid)
  genelist = go_desc_list[[as.numeric(x[3])]]
  labGenes = paste0(unlist(lapply(split(genelist, ceiling(seq_along(genelist)/10)), function(y) paste0(paste(y, collapse = ";"), "\n")), use.names = F), collapse = "")
  forest_model(model = res.cox, show_global_p = 'bottom') + labs(title = paste0(x[1], "\n", x[2]), caption = labGenes) + theme(plot.caption = element_text(hjust = 0))
})
rm(tempind, tempgo, ptv_data, tempdfU, ukb, res.cox, genelist, labGenes, x)
table(ukb$status, ukb$PTV)


ggsave(
  filename = "/media/balazs/WorkL/balazs/Work/UKBiobank/Plots/015/Melanoma_all_p001_Sign_Gene_Sets_PTV.pdf", 
  plot = marrangeGrob(plots, nrow=1, ncol=1), 
  width = 15, height = 9
)

list.files("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/013/PTV_GO/")[grep("antigen", list.files("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/013/PTV_GO/"))]



load("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/tumor_freq_data")
knitr::kable(tumor_freq_data)

```

