---
title: "GSEA C7 gene sets"
output: html_document
date: "2025-02-07"
---

#Setup

```{r}
setwd("/media/balazs/WorkL/balazs/Work/UKBiobank/")
#library(survival, lib.loc = "/home/balazs/R/x86_64-pc-linux-gnu-library/4.3")
Packages <- c("tidyverse", "data.table", "magrittr", "clusterProfiler", "org.Hs.eg.db", "hgnc", "future.apply", "fastmatch", "survival", "pbapply", "forestmodel", "gridExtra", "ggpubr")
#"Rfast", , , , , "tidycmprsk", , "survminer", "ggsurvfit", , , "ComplexHeatmap", , , , "ggrepel", "ggsci", "scales", , "circlize" "fastmatch", "h2o", , , "protr", , , "networkD3", , , "Biostrings", , )
lapply(Packages, require, character.only = TRUE)
rm(Packages)
options(dplyr.summarise.inform = FALSE)

# pal_npg("nrc")(9)
# scales::show_col(pal_npg("nrc")(9))
# pal_npg("nrc", alpha = 0.8)(9)
# scales::show_col(pal_npg("nrc", alpha = 0.8)(9))
```


```{r}
plan(multisession(workers = 4))
gseaGeneSets = read.gmt("Raw/c7.all.v2024.1.Hs.symbols.gmt")
gseaGeneSetsID = sort(unique(as.character(gseaGeneSets$term)))
geneSets = future_lapply(gseaGeneSetsID, function(x) gseaGeneSets %>% filter(term == x) %>% pull(gene))
#table(lengths(geneSets))
geneIDmatch = bitr(geneID = sort(unique(gseaGeneSets$gene)), fromType = "SYMBOL", toType = "ENSEMBL", OrgDb = "org.Hs.eg.db")
names(geneSets) = gseaGeneSetsID
geneSetsENS = lapply(geneSets, function(x) geneIDmatch$ENSEMBL[fmatch(x, geneIDmatch$SYMBOL)])
names(geneSetsENS) = gseaGeneSetsID

save(geneSets, geneSetsENS, file = "Objects/017/gsea_c7_genesets")
load("Objects/017/gsea_c7_genesets")
table(lengths(geneSets))
```

#Calculate PTV burden

```{r}
ptvb_MAF104 = fread("PTVvars/MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv")
ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes"))

ukb_ptvENSG = as.list(ptvb_MAF104$ptvgenes)
ukb_ptvENSG = lapply(ukb_ptvENSG, function(x) unique(unlist(strsplit(x, ","), use.names = F)))
names(ukb_ptvENSG) = ptvb_MAF104$eid
rm(ptvb_MAF104)

plan(multisession(workers = 4))
for(i in 1:length(geneSetsENS)) {
  print(i)
  tempensgs = geneSetsENS[[i]]
  ptv_data = unname(future_sapply(ukb_ptvENSG, function(u) {
    sum(u %fin% tempensgs)
  }))
  saveRDS(object = ptv_data, file = paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/017/PTV_GSEA/", i, "_", names(geneSetsENS)[i], ".rds"))
}
rm(i, ptv_data, tempensgs)
gc()

```

#Cox models

```{r}
load("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/tumor_freq_data")
ptvb_MAF104 = fread("PTVvars/MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv")
ptv_dataDF = data.frame(eid = ptvb_MAF104$Patient.ID)
rm(ptvb_MAF104)

gseaID = list.files("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/017/PTV_GSEA/")
gseaID = gsub(".rds", "", gseaID)
sel_gpcas = paste0("gpca", 1:20)

plan(multisession(workers = 8))

for(i in 1:length(gseaID)) {
  print(paste0(i, "_", Sys.time()))
  ptv_data = readRDS(paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/017/PTV_GSEA/", gseaID[i], ".rds"))
  ptv_dataDF$PTV = ptv_data
  coxres = future_apply(tumor_freq_data, 1, function(ts) {
    tempdfU = readRDS(paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/014/dfs/", ts[3], ".rds"))
    ukb = tempdfU %>% left_join(ptv_dataDF, by = "eid")
    ukb$PTVG = ifelse(ukb$PTV == 0, 0, 1)
    if(length(unique(ukb$PTVG)) > 1) {ukb$PTVG = as.factor(ukb$PTVG)}
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(c("PTVG", sel_gpcas), collapse = "+")))
    res.cox <- coxph(myformula, data = ukb, id = ukb$eid)
    as.numeric(rbind(summary(res.cox)$coefficients[,"exp(coef)"], summary(res.cox)$coefficients[,"Pr(>|z|)"]))
  })
  out = cbind(tumor_freq_data, ptv_type = gseaID[i], t(coxres))
  colnames(out)[seq(6,ncol(out),2)] = c("coefPTV", paste0("coef_gpca", 1:20))
  colnames(out)[seq(7,ncol(out),2)] = c("pPTVG", paste0("p_gpca", 1:20))
  out$padjPTVG = p.adjust(out$pPTVG, method = "fdr")
  saveRDS(object = out, file = paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/017/coxres/", gseaID[i], ".rds"))
  gc()
}
rm(coxres, out, i, ptv_data)

```

#Results

```{r}
load("Objects/017/gsea_c7_genesets")
gseaGeneSetsID = list.files("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/017/coxres/")
gseaGeneSetsID = gsub(".rds", "", gseaGeneSetsID)
res = bind_rows(lapply(1:length(gseaGeneSetsID), function(i) {
  dat = readRDS(paste0("/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/017/coxres/", gseaGeneSetsID[i], ".rds"))
  dat
}))
res$gseaInd = as.character(sapply(res$ptv_type, function(x) strsplit(x, "_")[[1]][1]))

res$genesHugo = sapply(res$gseaInd, function(x) paste0(geneSets[[as.numeric(x)]], collapse = ";"))
res$genesENS = sapply(res$gseaInd, function(x) paste0(geneSetsENS[[as.numeric(x)]], collapse = ";"))
res$gseaInd = as.numeric(res$gseaInd)

saveRDS(res, file = "Res/017/res_gsea_c7.rds")
#genesFreq = readRDS("Res/010/genesFreq_all_104.rds")


```

#Melanoma

```{r}
source("/home/balazs/mygit/ukb_tumor/scripts/B_Incidence_functions.R")
res = readRDS("Res/017/res_gsea_c7.rds")
genes = res %>% 
  arrange(pPTVG) %>% 
  filter(coefPTV > 1) %>% 
  filter(TS == "Melanoma_female") %>% 
  dplyr::slice(1) %>% 
  pull(genesENS) %>% 
  strsplit(";") %>% 
  unlist()

res %>% 
  arrange(pPTVG) %>% 
  filter(coefPTV > 1) %>% 
  filter(TS == "Melanoma_female") %>% 
  dplyr::slice(1) %>% 
  pull(ptv_type)

fun_TumorIncForestPlot(tumor = "Melanoma", gender = "female", geneset = genes)

#res_fishtest = readRDS("Res/010/res_fishtest_104.rds")

#All common terms
res %>% filter(grepl("Melanoma", cancer_type)) %>% filter(pPTVG < 0.2, coefPTV > 1) -> tempdf
tempdf$ptv_type[duplicated(tempdf$ptv_type)] -> gse_terms

plots = lapply(gse_terms, function(g) {
  genes = res %>% filter(ptv_type == g) %>% dplyr::slice(1) %>% pull(genesENS) %>% strsplit(";") %>% unlist()
  grid.arrange(fun_TumorIncForestPlot(tumor = "Melanoma", gender = "female", geneset = genes), fun_TumorIncForestPlot(tumor = "Melanoma", gender = "male", geneset = genes), ncol=2, top = g)
})

ggsave(
  filename = "Plots/017/Melanoma_Common_Hits_pLowerThan02_coefHigherThan1.pdf", 
  plot = marrangeGrob(plots, nrow = 1, ncol = 1), 
  width = 15, height = 9
)

```

#Hot tumors vs. nonim tumors

```{r}
source("/home/balazs/mygit/ukb_tumor/scripts/B_Incidence_functions.R")
res = readRDS("Res/017/res_gsea_c7.rds")

resF = res %>% 
  filter(pPTVG < 0.1) %>%
  filter(TS %in% c("Melanoma_female", "Melanoma_male", "Lung_female", "Lung_male", "Bladder_female", "Bladder_male", "Kidney_female", "Kidney_male", "Brain_female", "Brain_male", "Ovary_female", "Pancreas_female", "Pancreas_male")) %>% 
  mutate(g = ifelse(TS %in% c("Melanoma_female", "Melanoma_male", "Lung_female", "Lung_male", "Bladder_female", "Bladder_male", "Kidney_female", "Kidney_male"), "hot", "cold"), .before = cancer_type)

gseTermsF = unique(resF$ptv_type)
plan(multisession(workers = 8))
compDF = t(future_sapply(gseTermsF, function(x) {
  c(resF %>% filter(ptv_type == x, g == "hot", coefPTV > 1) %>% nrow(),
    resF %>% filter(ptv_type == x, g == "hot", coefPTV > 1, pPTVG < 0.05) %>% nrow(),
    resF %>% filter(ptv_type == x, g == "hot", coefPTV < 1) %>% nrow(),
    resF %>% filter(ptv_type == x, g == "hot", coefPTV < 1, pPTVG < 0.05) %>% nrow(),
    resF %>% filter(ptv_type == x, g == "cold", coefPTV > 1) %>% nrow(),
    resF %>% filter(ptv_type == x, g == "cold", coefPTV > 1, pPTVG < 0.05) %>% nrow(),
    resF %>% filter(ptv_type == x, g == "cold", coefPTV < 1) %>% nrow(),
    resF %>% filter(ptv_type == x, g == "cold", coefPTV < 1, pPTVG < 0.05) %>% nrow())
})) #30 sec
colnames(compDF) = c("over_hot_01", "over_hot_005", "under_hot_01", "under_hot_005",
                     "over_cold_01", "over_cold_005", "under_cold_01", "under_cold_005")
compDF = cbind.data.frame(id = gseTermsF, compDF)

compDF %>% filter(over_hot_01 >= 3, under_hot_01 == 0, over_cold_01 == 0) %>% View()
compDF %>% filter(over_hot_01 >= 3, under_hot_01 == 0, over_cold_01 == 0) %>% pull(id) -> gse_terms

plots_all = future_lapply(gse_terms, function(g) {
  genes = resF$genesENS[resF$ptv_type == g][1] %>% strsplit(";") %>% unlist()
  fig_hot_all = fun_TumorIncForestPlot(tumor = c("Melanoma", "Lung", "Bladder", "Kidney"), gender = "all", geneset = genes)
  fig_cold_all = fun_TumorIncForestPlot(tumor = c("BrainCNS", "Ovary", "Pancreas"), gender = "all", geneset = genes)
  grid.arrange(fig_hot_all, fig_cold_all, ncol = 2, nrow = 1, top = g)
})

ggsave(
  filename = "/media/balazs/WorkL/balazs/Work/UKBiobank/Plots/017/Hot_vs_cold_tumors_28terms.pdf", 
  plot = marrangeGrob(plots_all, nrow=1, ncol=1), 
  width = 15, height = 9
)


plots_all_2 = future_lapply(gse_terms, function(g) {
  genes = resF$genesENS[resF$ptv_type == g][1] %>% strsplit(";") %>% unlist()
  fig_hot_sep = ggarrange(plotlist = lapply(c("Melanoma_all", "Lung_all", "Bladder_all", "Kidney_all", 
                                              "Melanoma_female", "Melanoma_male", "Lung_female", "Lung_male", "Bladder_female", "Bladder_male", "Kidney_female", "Kidney_male"), function(z) {
                                                fun_TumorIncForestPlot(tumor = strsplit(z, "_")[[1]][1], gender = strsplit(z, "_")[[1]][2], geneset = genes)
                                              }), ncol = 4, nrow = 3)
  fig_cold_sep = ggarrange(plotlist = lapply(c("BrainCNS_all", "Pancreas_all", 
                                             "BrainCNS_female", "BrainCNS_male", "Ovary_female", "Pancreas_female", "Pancreas_male"), function(z) {
                                               fun_TumorIncForestPlot(tumor = strsplit(z, "_")[[1]][1], gender = strsplit(z, "_")[[1]][2], geneset = genes)
                                             }), ncol = 4, nrow = 2)
  grid.arrange(fig_hot_sep, fig_cold_sep, ncol = 1, nrow = 2, top = g)
})

ggsave(
  filename = "/media/balazs/WorkL/balazs/Work/UKBiobank/Plots/017/Hot_vs_cold_tumors_28terms_sep.pdf", 
  plot = marrangeGrob(plots_all_2, nrow=1, ncol=1), 
  width = 29, height = 21
)

library(tidyverse)
library(rvest)

gse_terms_data = list()
gse_terms_gene_data = list()
for(i in 1:length(gse_terms)) {
  print(i)
  gt = strsplit(gse_terms[i], "_")[[1]]
  gt = paste(gt[2:length(gt)], collapse = "_")
  url <-  paste0("https://www.gsea-msigdb.org/gsea/msigdb/human/geneset/", gt,".html")
  df <- url %>% read_html() %>% html_nodes("table") %>% html_table(fill = T)
  gse_terms_data[[i]] = df[[2]] %>% dplyr::slice(1:4) %>% dplyr::pull(X2)
  gse_terms_gene_data[[i]] = df[[3]] %>% as.data.frame()
}
rm(i, gt, url, df)

gse_terms_data = as.data.frame(do.call(rbind, gse_terms_data))
colnames(gse_terms_data) = c("Standard_name", "Systematic_name", "Brief_description", "Full_description")
gse_terms_data = cbind.data.frame(id = gse_terms, gse_terms_data)
names(gse_terms_gene_data) = gse_terms

tdf = t(future_sapply(gse_terms_data$id, function(g) {
  genes = resF$genesENS[resF$ptv_type == g][1] %>% strsplit(";") %>% unlist()
  cox_hot = fun_TumorIncCoxModel(tumor = c("Melanoma", "Lung", "Bladder", "Kidney"), gender = "all", geneset = genes)
  cox_cold = fun_TumorIncCoxModel(tumor = c("BrainCNS", "Ovary", "Pancreas"), gender = "all", geneset = genes)
  c(cox_hot, cox_cold)
}))
colnames(tdf) = c("hot_coxHR", "hot_coxP", "cold_coxHR", "cold_coxP")
gse_terms_data = cbind.data.frame(gse_terms_data, tdf)
rownames(gse_terms_data) = NULL
saveRDS(gse_terms_data, file = "Res/017/gse_terms_data_hot_vs_cold.rds")

View(gse_terms_gene_data[["55_FRANCO_BLOOD_SANOFI_PASTEUR_SA_INACTIVATED_INFLUENZA_VACCINE_CORRELATED_WITH_ANTIBODY_RESPONSE_AGE_18_40YO_14DY_POSITIVE"]])

res_fishtest = readRDS("Res/010/res_fishtest_104.rds")
res_fishtest %>% filter(SYMBOL %in% gse_terms_gene_data[["55_FRANCO_BLOOD_SANOFI_PASTEUR_SA_INACTIVATED_INFLUENZA_VACCINE_CORRELATED_WITH_ANTIBODY_RESPONSE_AGE_18_40YO_14DY_POSITIVE"]][,"GeneSymbol"]) %>% filter(category %in% c("Melanoma", "Lung", "Bladder", "Kidney", "Brain", "Ovary", "Pancreas")) %>% View()


fun_TumorIncCoxModel(tumor = "Lung", gender = "male", geneset = unlist(strsplit(resF$genesENS[resF$ptv_type == "55_FRANCO_BLOOD_SANOFI_PASTEUR_SA_INACTIVATED_INFLUENZA_VACCINE_CORRELATED_WITH_ANTIBODY_RESPONSE_AGE_18_40YO_14DY_POSITIVE"][1], ";")))
fun_TumorIncFishTest(tumor = "Lung", gender = "male", geneset = unlist(strsplit(resF$genesENS[resF$ptv_type == "55_FRANCO_BLOOD_SANOFI_PASTEUR_SA_INACTIVATED_INFLUENZA_VACCINE_CORRELATED_WITH_ANTIBODY_RESPONSE_AGE_18_40YO_14DY_POSITIVE"][1], ";")))
fun_TumorIncForestPlot(tumor = "Lung", gender = "male", geneset = unlist(strsplit(resF$genesENS[resF$ptv_type == "55_FRANCO_BLOOD_SANOFI_PASTEUR_SA_INACTIVATED_INFLUENZA_VACCINE_CORRELATED_WITH_ANTIBODY_RESPONSE_AGE_18_40YO_14DY_POSITIVE"][1], ";")))
fun_TumorIncStat(tumor = "Lung", gender = "male", geneset = unlist(strsplit(resF$genesENS[resF$ptv_type == "55_FRANCO_BLOOD_SANOFI_PASTEUR_SA_INACTIVATED_INFLUENZA_VACCINE_CORRELATED_WITH_ANTIBODY_RESPONSE_AGE_18_40YO_14DY_POSITIVE"][1], ";")))
fun_TumorSurvCoxDS(tumor = "Lung", gender = "male", geneset = unlist(strsplit(resF$genesENS[resF$ptv_type == "55_FRANCO_BLOOD_SANOFI_PASTEUR_SA_INACTIVATED_INFLUENZA_VACCINE_CORRELATED_WITH_ANTIBODY_RESPONSE_AGE_18_40YO_14DY_POSITIVE"][1], ";")))

```


```{r}
#Between gender
res %>% 
  filter(ptv_type %in% tempids, TS %in% hot_tumors) %>% 
  ggplot(mapping = aes(x = sex, y = coefPTV)) + 
  geom_boxplot() +
  facet_wrap(~ptv_type)

res %>% 
  filter(ptv_type %in% grep("BCELL", tempids, value = T), TS %in% hot_tumors) %>% 
  ggplot(mapping = aes(x = sex, y = coefPTV, color = cancer_type)) + 
  geom_point() +
  facet_wrap(~ptv_type)

```



##All tumors

```{r}
ids = unique(res$ptv_type)
resF = res %>% filter(pPTVG < 0.1)
plan(multisession(workers = 8))
comp_tumors = t(future_sapply(ids, function(x) {
  c(resF %>% filter(ptv_type == x, coefPTV > 1) %>% nrow(),
    resF %>% filter(ptv_type == x, coefPTV > 1, pPTVG < 0.05) %>% nrow(),
    resF %>% filter(ptv_type == x, coefPTV < 1) %>% nrow(),
    resF %>% filter(ptv_type == x, coefPTV < 1, pPTVG < 0.05) %>% nrow())
}))
colnames(comp_tumors) = c("over_01", "over_005", "under_01", "under_005")
comp_tumors = cbind.data.frame(id = ids, comp_tumors)

comp_tumors %>% filter(over_01 >= 10) %>% View()

```

