---
title: "B_024_PTV_burden_influvac_genesets"
output: html_document
date: "2025-04-28"
---

```{r}
setwd("/media/balazs/WorkL/balazs/Work/UKBiobank/")
#library(survival, lib.loc = "/home/balazs/R/x86_64-pc-linux-gnu-library/4.3")
Packages <- c("tidyverse", "data.table", "magrittr", "future.apply", "fastmatch", "clusterProfiler", "org.Hs.eg.db", "stringi")
#, "hgnc", , , "survival", "pbapply", "forestmodel", "gridExtra", "ggpubr", "rvest", "Rfast", , , , , "tidycmprsk", , "survminer", "ggsurvfit", , , "ComplexHeatmap", , , , "ggrepel", "ggsci", "scales", , "circlize" "fastmatch", "h2o", , , "protr", , , "networkD3", , , "Biostrings", ,
lapply(Packages, require, character.only = TRUE)
rm(Packages)
options(dplyr.summarise.inform = FALSE)

# pal_npg("nrc")(9)
# scales::show_col(pal_npg("nrc")(9))
# pal_npg("nrc", alpha = 0.8)(9)
# scales::show_col(pal_npg("nrc", alpha = 0.8)(9))
options(future.globals.maxSize= 2147483648)
source("/home/balazs/mygit/ukb_tumor/scripts/B_Incidence_functions.R")
plan(multisession(workers = 4))
```

#Common object

```{r}
ptvb_MAF104 = fread("PTVvars/MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv")
ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes"))

ukb_ptvENSG = as.list(ptvb_MAF104$ptvgenes)
ukb_ptvENSG = lapply(ukb_ptvENSG, function(x) unique(unlist(strsplit(x, ","), use.names = F)))
names(ukb_ptvENSG) = ptvb_MAF104$eid
rm(ptvb_MAF104)

```

#Konstorum

```{r}
geneset_raw = fread("Influenza_objects/geneset_Konstorum_UP_highresp.txt")
geneset_raw = fread("Influenza_objects/geneset_Konstorum_UP_lowresp.txt")

geneset_raw$Transcript = gsub("\\..*", "", geneset_raw$Transcript)

tempensgs = geneset_raw$Transcript
ptv_data = future_sapply(ukb_ptvENSG, function(u) {
  sum(u %fin% tempensgs)
})
table(ptv_data)
saveRDS(ptv_data, file = "Objects/024/ptvb_Konstorum_HR.rds")
saveRDS(ptv_data, file = "Objects/024/ptvb_Konstorum_LR.rds")

```

##Both

```{r}
geneset_raw1 = fread("Influenza_objects/geneset_Konstorum_UP_highresp.txt")
geneset_raw2 = fread("Influenza_objects/geneset_Konstorum_UP_lowresp.txt")
geneset_raw = rbind(geneset_raw1, geneset_raw2)
rm(geneset_raw1, geneset_raw2)

geneset_raw$Transcript = gsub("\\..*", "", geneset_raw$Transcript)

tempensgs = unique(geneset_raw$Transcript)
ptv_data = future_sapply(ukb_ptvENSG, function(u) {
  sum(u %fin% tempensgs)
})
table(ptv_data)
saveRDS(ptv_data, file = "Objects/024/ptvb_Konstorum_HR_LR.rds")

```

#Rogers

```{r}
geneset_rogers = fread("Influenza_objects/geneset_Rogers.txt")
hugo_symbols_unique_rogers = unique(geneset_rogers$Gene)
gene_match_rogers = bitr(geneID = hugo_symbols_unique_rogers, fromType = "SYMBOL", toType = "ENSEMBL", OrgDb = "org.Hs.eg.db")

ensgs_10 = gene_match_rogers$ENSEMBL[match(geneset_rogers$Gene[1:10], gene_match_rogers$SYMBOL)]
ensgs_10 = ensgs_10[!is.na(ensgs_10)]
ensgs_50 = gene_match_rogers$ENSEMBL[match(geneset_rogers$Gene[1:50], gene_match_rogers$SYMBOL)]
ensgs_50 = ensgs_50[!is.na(ensgs_50)]
ensgs_100 = gene_match_rogers$ENSEMBL[match(geneset_rogers$Gene[1:100], gene_match_rogers$SYMBOL)]
ensgs_100 = ensgs_100[!is.na(ensgs_100)]

ptv_data = future_sapply(ukb_ptvENSG, function(u) {
  sum(u %fin% ensgs_100)
})
table(ptv_data)
saveRDS(ptv_data, file = "Objects/024/ptvb_Rogers_first10.rds")
saveRDS(ptv_data, file = "Objects/024/ptvb_Rogers_first50.rds")
saveRDS(ptv_data, file = "Objects/024/ptvb_Rogers_first100.rds")
```

#Gene sets

```{r}
genesets = expand.grid(Franco = c("yes", "no"), Konstorum_HR = c("yes", "no"), Konstorum_LR = c("yes", "no"), Rogers = c(0,10,50,100), stringsAsFactors = F)
genesets %<>% filter(!(Franco == "no" & Konstorum_HR == "no" & Konstorum_LR == "no" & Rogers == 0))

res = readRDS("Res/017/res_gsea_c7.rds")
FRANCOensgs = unlist(strsplit(res$genesENS[res$ptv_type == "55_FRANCO_BLOOD_SANOFI_PASTEUR_SA_INACTIVATED_INFLUENZA_VACCINE_CORRELATED_WITH_ANTIBODY_RESPONSE_AGE_18_40YO_14DY_POSITIVE"][1], ";"))
rm(res)

geneset_rogers = fread("Influenza_objects/geneset_Rogers.txt")
hugo_symbols_unique_rogers = unique(geneset_rogers$Gene)
gene_match_rogers = bitr(geneID = hugo_symbols_unique_rogers, fromType = "SYMBOL", toType = "ENSEMBL", OrgDb = "org.Hs.eg.db")
rm(hugo_symbols_unique_rogers)

genesets$genes = apply(genesets, 1, function(x) {
  tempgenes = NULL
  if(x[1] == "yes") {
    tempgenes = FRANCOensgs
  }
  if(x[2] == "yes") {
    tempdf = fread("Influenza_objects/geneset_Konstorum_UP_highresp.txt")
    tempgenes = unique(c(tempgenes, gsub("\\..*", "", tempdf$Transcript)))
    rm(tempdf)
  }
  if(x[3] == "yes") {
    tempdf = fread("Influenza_objects/geneset_Konstorum_UP_lowresp.txt")
    tempgenes = unique(c(tempgenes, gsub("\\..*", "", tempdf$Transcript)))
    rm(tempdf)
  }
  if(as.numeric(x[4]) > 0) {
    tempensgs = gene_match_rogers$ENSEMBL[match(geneset_rogers$Gene[1:as.numeric(x[4])], gene_match_rogers$SYMBOL)]
    tempensgs = tempensgs[!is.na(tempensgs)]
    tempgenes = unique(c(tempgenes, tempensgs))
  }
  paste0(tempgenes, collapse = ";")
})
genesets$geneset_size = sapply(genesets$genes, function(x) length(strsplit(x, ";")[[1]]))

save(genesets, file = "Objects/024/genesets_data_0")

```


#Univariate models
##Lung and bladder

```{r}
load("Objects/024/genesets_data_0")
genesets$lung_incCoxHR = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$lung_incCoxP = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])
genesets$bladder_incCoxHR = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "Bladder", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$bladder_incCoxP = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "Bladder", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])

fun_TumorIncForestPlot(tumor = c("Lung", "Bladder"), gender = "male", geneset = strsplit(genesets$genes[5], ";")[[1]])
fun_TumorIncForestPlot(tumor = c("Lung", "Bladder"), gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])
fun_TumorIncForestPlot(tumor = c("Lung", "Bladder"), gender = "male", geneset = strsplit(genesets$genes[14], ";")[[1]])

#OS
genesets$lung_OSCoxHR = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxOS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$lung_OSCoxP = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxOS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])
genesets$bladder_OSCoxHR = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxOS(tumor = "Bladder", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"]) #NO
genesets$bladder_OSCoxP = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxOS(tumor = "Bladder", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"]) #NO

fun_TumorSurvPlotOS(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])
fun_TumorSurvPlotOS(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[14], ";")[[1]])

#DS
genesets$lung_DSCoxHR = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxDS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$lung_DSCoxP = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxDS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])
genesets$bladder_DSCoxHR = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxDS(tumor = "Bladder", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"]) #NO
genesets$bladder_DSCoxP = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxDS(tumor = "Bladder", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"]) #NO

fun_TumorSurvPlotDS(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])
fun_TumorSurvPlotDS(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[14], ";")[[1]])

save(genesets, file = "Objects/024/genesets_data_EXT1")
load("Objects/024/genesets_data_EXT1")
```


#Multivariate models with smoking data

##Smoking data

```{r}
smoking_data = fread("/media/balazs/WorkL/balazs/Work/UKBiobank/Variables/20116.txt")
smoking_data %<>% mutate(smoking_status1 = case_when(
  .$value == -3 ~ "PreferNotToAnswer",
  .$value == 0 ~ "never",
  .$value == 1 ~ "previous",
  .$value == 2 ~ "current"
))
table(smoking_data$value, smoking_data$smoking_status1)

smoking_data %<>% 
  select(eid, UKB_column_name, smoking_status1) %>% 
  pivot_wider(id_cols = eid, names_from = UKB_column_name, values_from = smoking_status1) %>% 
  unite(col = "smst_unite", c("20116-0.0", "20116-1.0", "20116-2.0", "20116-3.0"), sep = "", remove = F, na.rm = T) %>% 
  mutate(smoking_status = case_when(
    stri_detect_fixed(pattern = "current", smst_unite) | stri_detect_fixed(pattern = "Current", smst_unite) ~ "current",
    stri_detect_fixed(pattern = "previous", smst_unite) | stri_detect_fixed(pattern = "Previous", smst_unite) ~ "previous",
    stri_detect_fixed(pattern = "never", smst_unite) | stri_detect_fixed(pattern = "Never", smst_unite) ~ "never"
  ), .after = eid) %>% 
  select(eid, smoking_status) %>% 
  transform(smoking_status = factor(smoking_status, levels = c("never", "previous", "current"))) %>% 
  transform(eid = as.character(eid)) %>% 
  unique()
table(smoking_data$smoking_status)
saveRDS(smoking_data, file = "Objects/024/smoking_status.rds")
```


##Functions

```{r}
fun_TumorIncForestPlot = function(tumor = "all", 
                                  control = "nottumorous", 
                                  gender = "all", 
                                  geneset = c("ENSG00000104804"), 
                                  ptv_burden_cat = TRUE, 
                                  gpca_nb = 10, 
                                  dataset_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", 
                                  ptv_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/PTVvars/") {
  if(control == "nottumorous" & gender == "all") {
    control_data = readRDS(paste0(dataset_dir, "nottumorous_all.rds"))
  } else if(control == "nottumorous" & gender == "female") {
    control_data = readRDS(paste0(dataset_dir, "nottumorous_female.rds"))
  } else if(control == "nottumorous" & gender == "male") {
    control_data = readRDS(paste0(dataset_dir, "nottumorous_male.rds"))
  }
  m = max(control_data$date_of_death, na.rm = T)
  control_data %<>% 
    mutate(time = case_when(
      death == T ~ as.numeric(date_of_death - birthdate),
      death == F ~ as.numeric(m - birthdate)
    )) %>% 
    mutate(status = 0)
  tumor_data = bind_rows(lapply(tumor, function(tmr) {
    if(tmr == "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_all.rds"))
    } else if(tmr == "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_", gender, ".rds"))
    } else if(tmr != "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, ".rds"))
    } else if(tmr != "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, "_", gender, ".rds"))
    }
  }))
  tumor_data %<>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric((diag_date - birthdate))) %>% 
    mutate(status = 1)
  tempdf = rbind(tumor_data, control_data)
  rm(tumor_data, control_data)
  tempdf$smoking_status = smoking_data$smoking_status[match(tempdf$eid, smoking_data$eid)]
  ptvb_MAF104 = fread(paste0(ptv_dir, "MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv"))
  ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes")) %>% filter(eid %fin% tempdf$eid)
  ptvb_MAF104$PTVb = sapply(ptvb_MAF104$ptvgenes, function(x) sum(unique(unlist(strsplit(x, ","), use.names = F)) %fin% geneset))
  tempdf %<>% left_join(ptvb_MAF104, by = "eid") %>% dplyr::select(-ptvgenes)
  if(ptv_burden_cat == T) {tempdf$PTVb = as.factor(ifelse(tempdf$PTVb == 0, 0, 1))}
  sel_gpcas = paste0("gpca", 1:gpca_nb)
  tempdf %<>% dplyr::select(eid, time, status, PTVb, sex, smoking_status, all_of(sel_gpcas))
  if(gender %in% c("female", "male")) {
    tempdf %<>% dplyr::select(-sex)
  }
  if(length(unique(tempdf$PTVb)) == 1) {
    tempdf %<>% dplyr::select(-PTVb)
  }
  if("PTVb" %in% colnames(tempdf)) {
    case_n_ptvb_1 = tempdf %>% filter(status == 1, PTVb == 1) %>% nrow()
  } else {
    case_n_ptvb_1 = 0
  }
  tt = paste0(paste0(tumor, collapse = ", "), ", ", paste0(gender, collapse = ", "), ". Geneset size: ", length(geneset), "\nTumorous patients (PTV=1): ", case_n_ptvb_1)
  myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdf)[4:ncol(tempdf)], collapse = "+")))
  res.cox <- coxph(myformula, data = tempdf, id = tempdf$eid)
  fm = forest_model(model = res.cox, return_data = T)
  fm$plot + labs(title = tt)
}

fun_TumorIncCoxModel = function(tumor = "all", 
                                control = "nottumorous", 
                                gender = "all", 
                                geneset = c("ENSG00000104804"), 
                                ptv_burden_cat = TRUE, 
                                gpca_nb = 10, 
                                dataset_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", 
                                ptv_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/PTVvars/") {
  if(control == "nottumorous" & gender == "all") {
    control_data = readRDS(paste0(dataset_dir, "nottumorous_all.rds"))
  } else if(control == "nottumorous" & gender == "female") {
    control_data = readRDS(paste0(dataset_dir, "nottumorous_female.rds"))
  } else if(control == "nottumorous" & gender == "male") {
    control_data = readRDS(paste0(dataset_dir, "nottumorous_male.rds"))
  }
  m = max(control_data$date_of_death, na.rm = T)
  control_data %<>% 
    mutate(time = case_when(
      death == T ~ as.numeric(date_of_death - birthdate),
      death == F ~ as.numeric(m - birthdate)
    )) %>% 
    mutate(status = 0)
  tumor_data = bind_rows(lapply(tumor, function(tmr) {
    if(tmr == "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_all.rds"))
    } else if(tmr == "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_", gender, ".rds"))
    } else if(tmr != "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, ".rds"))
    } else if(tmr != "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, "_", gender, ".rds"))
    }
  }))
  tumor_data %<>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric((diag_date - birthdate))) %>% 
    mutate(status = 1)
  tempdf = rbind(tumor_data, control_data)
  rm(tumor_data, control_data)
  tempdf$smoking_status = smoking_data$smoking_status[match(tempdf$eid, smoking_data$eid)]
  ptvb_MAF104 = fread(paste0(ptv_dir, "MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv"))
  ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes")) %>% filter(eid %fin% tempdf$eid)
  ptvb_MAF104$PTVb = sapply(ptvb_MAF104$ptvgenes, function(x) sum(unique(unlist(strsplit(x, ","), use.names = F)) %fin% geneset))
  tempdf %<>% left_join(ptvb_MAF104, by = "eid") %>% dplyr::select(-ptvgenes)
  if(ptv_burden_cat == T) {tempdf$PTVb = as.factor(ifelse(tempdf$PTVb == 0, 0, 1))}
  sel_gpcas = paste0("gpca", 1:gpca_nb)
  tempdf %<>% dplyr::select(eid, time, status, PTVb, sex, smoking_status, all_of(sel_gpcas))
  if(gender %in% c("female", "male")) {
    tempdf %<>% dplyr::select(-sex)
  }
  if(length(unique(tempdf$PTVb)) == 1) {
    tempdf %<>% dplyr::select(-PTVb)
  }
  if("PTVb" %in% colnames(tempdf)) {
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdf)[4:ncol(tempdf)], collapse = "+")))
    res.cox <- coxph(myformula, data = tempdf, id = tempdf$eid)
    out = summary(res.cox)$coefficients[grep("PTV", rownames(summary(res.cox)$coefficients), value = T),c("exp(coef)","Pr(>|z|)")]
  } else {
    out = c(NA, NA)
  }
  names(out) = c("HR", "Pvalue")
  out
}


```


##Incidence

```{r}
load("Objects/024/genesets_data_0")

genesets$lung_incCoxHR = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$lung_incCoxP = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])
genesets$bladder_incCoxHR = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "Bladder", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$bladder_incCoxP = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "Bladder", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])
genesets$all_incCoxHR = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "all", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$all_incCoxP = future_sapply(genesets$genes, function(x) fun_TumorIncCoxModel(tumor = "all", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])

save(genesets, file = "Objects/024/genesets_data_EXT2")

fun_TumorIncForestPlot(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])
fun_TumorIncForestPlot(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[14], ";")[[1]])
fun_TumorIncForestPlot(tumor = c("Lung", "Bladder"), gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])
fun_TumorIncForestPlot(tumor = c("Lung", "Bladder"), gender = "male", geneset = strsplit(genesets$genes[5], ";")[[1]])
fun_TumorIncForestPlot(tumor = "all", gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])
fun_TumorIncForestPlot(tumor = "all", gender = "male", geneset = strsplit(genesets$genes[1], ";")[[1]])

ensgs = strsplit(genesets$genes[7], ";")[[1]]
res_MISS1gene_alltumor = cbind.data.frame(ENSG = ensgs, t(future_sapply(ensgs, function(ensg) {
  g = dplyr::setdiff(ensgs, ensg)
  fun_TumorIncCoxModel(tumor = "all", gender = "male", geneset = g)
})))






```

##OS 
###Functions

```{r}
fun_TumorSurvPlotOS = function(tumor = "all", 
                               gender = "all", 
                               geneset = c("ENSG00000104804"), 
                               ptv_burden_cat = TRUE, 
                               dataset_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", 
                               ptv_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/PTVvars/") {
  tumor_data = bind_rows(lapply(tumor, function(tmr) {
    if(tmr == "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_all.rds"))
    } else if(tmr == "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_", gender, ".rds"))
    } else if(tmr != "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, ".rds"))
    } else if(tmr != "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, "_", gender, ".rds"))
    }
  }))
  ptvb_MAF104 = fread(paste0(ptv_dir, "MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv"))
  ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes")) %>% filter(eid %fin% tumor_data$eid)
  ptvb_MAF104$PTVb = sapply(ptvb_MAF104$ptvgenes, function(x) sum(unique(unlist(strsplit(x, ","), use.names = F)) %fin% geneset))
  tumor_data %<>% left_join(ptvb_MAF104, by = "eid") %>% dplyr::select(-ptvgenes)
  if(ptv_burden_cat == T) {tumor_data$PTVb = as.factor(ifelse(tumor_data$PTVb == 0, 0, 1))}
  m = max(tumor_data$date_of_death, na.rm = T)
  tumorous_d = tumor_data %>%
    filter(death == T) %>%
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumor_data %>% 
    filter(death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(m - diag_date))
  survdf = bind_rows(tumorous_d, tumorous_alive)
  survdf$surv_event = as.numeric(ifelse(survdf$death == T, 1, 0))
  survdf$smoking_status = smoking_data$smoking_status[match(survdf$eid, smoking_data$eid)]
  survdf %<>% filter(smoking_status == "never") #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  if(length(unique(survdf$PTVb)) == 1) {
    print("No tumorous patients with geneset specific PTV")
  } else {
    dead_n_ptvb_1 = survdf %>% dplyr::filter(surv_event == 1, PTVb == 1) %>% nrow()
    alive_n_ptvb_1 = survdf %>% dplyr::filter(surv_event == 0, PTVb == 1) %>% nrow()
    tt = paste0(paste0(tumor, collapse = ", "), ", ", paste0(gender, collapse = ", "), ". Geneset size: ", length(geneset), "\nDead patients (PTV=1): ", dead_n_ptvb_1, ". Alive patients (PTV=1): ", alive_n_ptvb_1)
    survfit2(Surv(surv_time, surv_event) ~ PTVb, data = survdf) %>% 
      ggsurvfit() +
      labs(
        x = "Days",
        y = "Overall survival probability"
      ) + 
      add_confidence_interval() +
      add_pvalue(location = c("annotation")) +
      add_risktable() +
      labs(title = tt)
  }
}

fun_TumorSurvCoxOS = function(tumor = "all", 
                              gender = "all", 
                              geneset = c("ENSG00000104804"), 
                              ptv_burden_cat = TRUE, 
                              gpca_nb = 10, 
                              dataset_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", 
                              ptv_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/PTVvars/") {
  tumor_data = bind_rows(lapply(tumor, function(tmr) {
    if(tmr == "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_all.rds"))
    } else if(tmr == "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_", gender, ".rds"))
    } else if(tmr != "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, ".rds"))
    } else if(tmr != "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, "_", gender, ".rds"))
    }
  }))
  ptvb_MAF104 = fread(paste0(ptv_dir, "MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv"))
  ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes")) %>% filter(eid %fin% tumor_data$eid)
  ptvb_MAF104$PTVb = sapply(ptvb_MAF104$ptvgenes, function(x) sum(unique(unlist(strsplit(x, ","), use.names = F)) %fin% geneset))
  tumor_data %<>% left_join(ptvb_MAF104, by = "eid") %>% dplyr::select(-ptvgenes)
  if(ptv_burden_cat == T) {tumor_data$PTVb = as.factor(ifelse(tumor_data$PTVb == 0, 0, 1))}
  m = max(tumor_data$date_of_death, na.rm = T)
  tumorous_d = tumor_data %>%
    filter(death == T) %>%
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumor_data %>% 
    filter(death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(m - diag_date))
  survdf = bind_rows(tumorous_d, tumorous_alive)
  survdf$surv_event = as.numeric(ifelse(survdf$death == T, 1, 0))
  survdf$smoking_status = smoking_data$smoking_status[match(survdf$eid, smoking_data$eid)]
  survdf %<>% filter(smoking_status == "never") #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  sel_gpcas = paste0("gpca", 1:gpca_nb)
  survdf %<>% dplyr::select(eid, surv_time, surv_event, PTVb, sex, age, all_of(sel_gpcas))
  if(gender %in% c("female", "male")) {
    survdf %<>% dplyr::select(-sex)
  }
  if(length(unique(survdf$PTVb)) == 1) {
    survdf %<>% dplyr::select(-PTVb)
  }
  if("PTVb" %in% colnames(survdf)) {
    myformula = as.formula(paste('Surv(surv_time, surv_event) ~ ', paste0(colnames(survdf)[4:ncol(survdf)], collapse = "+")))
    res.cox = survival::coxph(myformula, data = as.data.frame(survdf))
    out = summary(res.cox)$coefficients[grep("PTV", rownames(summary(res.cox)$coefficients), value = T),c("exp(coef)","Pr(>|z|)")]
  } else {
    out = c(NA, NA)
  }
  names(out) = c("HR", "Pvalue")
  out
}



fun_TumorSurvChisquareOS = function(tumor = "all", 
                              gender = "all", 
                              geneset = c("ENSG00000104804"), 
                              ptv_burden_cat = TRUE, 
                              gpca_nb = 10, 
                              dataset_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", 
                              ptv_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/PTVvars/") {
  tumor_data = bind_rows(lapply(tumor, function(tmr) {
    if(tmr == "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_all.rds"))
    } else if(tmr == "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_", gender, ".rds"))
    } else if(tmr != "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, ".rds"))
    } else if(tmr != "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, "_", gender, ".rds"))
    }
  }))
  ptvb_MAF104 = fread(paste0(ptv_dir, "MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv"))
  ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes")) %>% filter(eid %fin% tumor_data$eid)
  ptvb_MAF104$PTVb = sapply(ptvb_MAF104$ptvgenes, function(x) sum(unique(unlist(strsplit(x, ","), use.names = F)) %fin% geneset))
  tumor_data %<>% left_join(ptvb_MAF104, by = "eid") %>% dplyr::select(-ptvgenes)
  if(ptv_burden_cat == T) {tumor_data$PTVb = as.factor(ifelse(tumor_data$PTVb == 0, 0, 1))}
  m = max(tumor_data$date_of_death, na.rm = T)
  tumorous_d = tumor_data %>%
    filter(death == T) %>%
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumor_data %>% 
    filter(death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(m - diag_date))
  survdf = bind_rows(tumorous_d, tumorous_alive)
  survdf$surv_event = as.numeric(ifelse(survdf$death == T, 1, 0))
  survdf$smoking_status = smoking_data$smoking_status[match(survdf$eid, smoking_data$eid)]
  survdf %<>% filter(smoking_status == "never") #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  sel_gpcas = paste0("gpca", 1:gpca_nb)
  survdf %<>% dplyr::select(eid, surv_time, surv_event, PTVb)
  if(length(unique(survdf$PTVb)) == 1) {
    survdf %<>% dplyr::select(-PTVb)
    out = NA
  } else {
    out = survdiff(Surv(surv_time, surv_event) ~ PTVb, data = survdf)$p
  }
  names(out) = "Pvalue"
  out
}


```

###Plots

```{r}
fun_TumorSurvPlotOS(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])
fun_TumorSurvCoxOS(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])
fun_TumorSurvChisquareOS(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[7], ";")[[1]])

genesets$lung_OSChisquareP = future_sapply(genesets$genes, function(x) fun_TumorSurvChisquareOS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]]))
genesets$lung_OSCoxHR = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxOS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$lung_OSCoxP = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxOS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])
```

##DSS
###Functions

```{r}
fun_TumorSurvPlotDS = function(tumor = "all", 
                               gender = "all", 
                               geneset = c("ENSG00000104804"), 
                               ptv_burden_cat = TRUE, 
                               dataset_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", 
                               ptv_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/PTVvars/") {
  tumor_data = bind_rows(lapply(tumor, function(tmr) {
    if(tmr == "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_all.rds"))
    } else if(tmr == "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_", gender, ".rds"))
    } else if(tmr != "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, ".rds"))
    } else if(tmr != "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, "_", gender, ".rds"))
    }
  }))
  ptvb_MAF104 = fread(paste0(ptv_dir, "MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv"))
  ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes")) %>% filter(eid %fin% tumor_data$eid)
  ptvb_MAF104$PTVb = sapply(ptvb_MAF104$ptvgenes, function(x) sum(unique(unlist(strsplit(x, ","), use.names = F)) %fin% geneset))
  tumor_data %<>% left_join(ptvb_MAF104, by = "eid") %>% dplyr::select(-ptvgenes)
  if(ptv_burden_cat == T) {tumor_data$PTVb = as.factor(ifelse(tumor_data$PTVb == 0, 0, 1))}
  m = max(tumor_data$date_of_death, na.rm = T)
  tumorous_d = tumor_data %>%
    filter(death == T & death_type == cancer_type) %>%
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumor_data %>% 
    filter(death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(m - diag_date))
  survdf = bind_rows(tumorous_d, tumorous_alive)
  survdf$surv_event = as.numeric(ifelse(survdf$death == T, 1, 0))
  survdf$smoking_status = smoking_data$smoking_status[match(survdf$eid, smoking_data$eid)]
  survdf %<>% filter(smoking_status == "never") #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  if(length(unique(survdf$PTVb)) == 1) {
    print("No tumorous patients with geneset specific PTV")
  } else {
    dead_n_ptvb_1 = survdf %>% dplyr::filter(surv_event == 1, PTVb == 1) %>% nrow()
    alive_n_ptvb_1 = survdf %>% dplyr::filter(surv_event == 0, PTVb == 1) %>% nrow()
    tt = paste0(paste0(tumor, collapse = ", "), ", ", paste0(gender, collapse = ", "), ". Geneset size: ", length(geneset), "\nDead patients (PTV=1): ", dead_n_ptvb_1, ". Alive patients (PTV=1): ", alive_n_ptvb_1)
    survfit2(Surv(surv_time, surv_event) ~ PTVb, data = survdf) %>% 
      ggsurvfit() +
      labs(
        x = "Days",
        y = "Disease specific survival probability"
      ) + 
      add_confidence_interval() +
      add_pvalue(location = c("annotation")) +
      add_risktable() +
      labs(title = tt)
  }
}

fun_TumorSurvCoxDS = function(tumor = "all", 
                              gender = "all", 
                              geneset = c("ENSG00000104804"), 
                              ptv_burden_cat = TRUE, 
                              gpca_nb = 10, 
                              dataset_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", 
                              ptv_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/PTVvars/") {
  tumor_data = bind_rows(lapply(tumor, function(tmr) {
    if(tmr == "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_all.rds"))
    } else if(tmr == "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_", gender, ".rds"))
    } else if(tmr != "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, ".rds"))
    } else if(tmr != "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, "_", gender, ".rds"))
    }
  }))
  ptvb_MAF104 = fread(paste0(ptv_dir, "MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv"))
  ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes")) %>% filter(eid %fin% tumor_data$eid)
  ptvb_MAF104$PTVb = sapply(ptvb_MAF104$ptvgenes, function(x) sum(unique(unlist(strsplit(x, ","), use.names = F)) %fin% geneset))
  tumor_data %<>% left_join(ptvb_MAF104, by = "eid") %>% dplyr::select(-ptvgenes)
  if(ptv_burden_cat == T) {tumor_data$PTVb = as.factor(ifelse(tumor_data$PTVb == 0, 0, 1))}
  m = max(tumor_data$date_of_death, na.rm = T)
  tumorous_d = tumor_data %>%
    filter(death == T & death_type == cancer_type) %>%
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumor_data %>% 
    filter(death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(m - diag_date))
  survdf = bind_rows(tumorous_d, tumorous_alive)
  survdf$surv_event = as.numeric(ifelse(survdf$death == T, 1, 0))
  survdf$smoking_status = smoking_data$smoking_status[match(survdf$eid, smoking_data$eid)]
  survdf %<>% filter(smoking_status == "never") #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  sel_gpcas = paste0("gpca", 1:gpca_nb)
  survdf %<>% dplyr::select(eid, surv_time, surv_event, PTVb, sex, age, all_of(sel_gpcas))
  if(gender %in% c("female", "male")) {
    survdf %<>% dplyr::select(-sex)
  }
  if(length(unique(survdf$PTVb)) == 1) {
    survdf %<>% dplyr::select(-PTVb)
  }
  if("PTVb" %in% colnames(survdf)) {
    myformula = as.formula(paste('Surv(surv_time, surv_event) ~ ', paste0(colnames(survdf)[4:ncol(survdf)], collapse = "+")))
    res.cox = survival::coxph(myformula, data = as.data.frame(survdf))
    out = summary(res.cox)$coefficients[grep("PTV", rownames(summary(res.cox)$coefficients), value = T),c("exp(coef)","Pr(>|z|)")]
  } else {
    out = c(NA, NA)
  }
  names(out) = c("HR", "Pvalue")
  out
}

fun_TumorSurvChisquareDS = function(tumor = "all", 
                              gender = "all", 
                              geneset = c("ENSG00000104804"), 
                              ptv_burden_cat = TRUE, 
                              gpca_nb = 10, 
                              dataset_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/Objects/000_Sub_datasets/", 
                              ptv_dir = "/media/balazs/WorkL/balazs/Work/UKBiobank/PTVvars/") {
  tumor_data = bind_rows(lapply(tumor, function(tmr) {
    if(tmr == "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_all.rds"))
    } else if(tmr == "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, "tumorous_", gender, ".rds"))
    } else if(tmr != "all" & gender == "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, ".rds"))
    } else if(tmr != "all" & gender != "all") {
      tmr_data = readRDS(paste0(dataset_dir, tmr, "_", gender, ".rds"))
    }
  }))
  ptvb_MAF104 = fread(paste0(ptv_dir, "MAF10_4_all_retained_variants_PTVBurden_final_Shetscores.tsv"))
  ptvb_MAF104 %<>% dplyr::select(Patient.ID, Genes) %>% set_colnames(c("eid", "ptvgenes")) %>% filter(eid %fin% tumor_data$eid)
  ptvb_MAF104$PTVb = sapply(ptvb_MAF104$ptvgenes, function(x) sum(unique(unlist(strsplit(x, ","), use.names = F)) %fin% geneset))
  tumor_data %<>% left_join(ptvb_MAF104, by = "eid") %>% dplyr::select(-ptvgenes)
  if(ptv_burden_cat == T) {tumor_data$PTVb = as.factor(ifelse(tumor_data$PTVb == 0, 0, 1))}
  m = max(tumor_data$date_of_death, na.rm = T)
  tumorous_d = tumor_data %>%
    filter(death == T & death_type == cancer_type) %>%
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumor_data %>% 
    filter(death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(surv_time = as.numeric(m - diag_date))
  survdf = bind_rows(tumorous_d, tumorous_alive)
  survdf$surv_event = as.numeric(ifelse(survdf$death == T, 1, 0))
  survdf$smoking_status = smoking_data$smoking_status[match(survdf$eid, smoking_data$eid)]
  survdf %<>% filter(smoking_status == "never") #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  sel_gpcas = paste0("gpca", 1:gpca_nb)
  survdf %<>% dplyr::select(eid, surv_time, surv_event, PTVb)
  if(length(unique(survdf$PTVb)) == 1) {
    survdf %<>% dplyr::select(-PTVb)
    out = NA
  } else {
    out = survdiff(Surv(surv_time, surv_event) ~ PTVb, data = survdf)$p
  }
  names(out) = "Pvalue"
  out
}

```

###Plots

```{r}
genesets$lung_DSChisquareP = future_sapply(genesets$genes, function(x) fun_TumorSurvChisquareDS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]]))
genesets$lung_DSCoxHR = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxDS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["HR"])
genesets$lung_DSCoxP = future_sapply(genesets$genes, function(x) fun_TumorSurvCoxDS(tumor = "Lung", gender = "male", geneset = strsplit(x, ";")[[1]])["Pvalue"])

fun_TumorSurvPlotDS(tumor = "Lung", gender = "male", geneset = strsplit(genesets$genes[14], ";")[[1]])

save(genesets, file = "Objects/024/genesets_data_EXT2")
```


