---
title: "Cox models - incidence of tumors"
author: "Balazs Koncz"
date: "2024-10-08"
output: html_document
---

#Setup

```{r}
setwd("/media/balazs/WorkL/balazs/Work/UKBiobank/") #asdf
library(survival, lib.loc = "/home/balazs/R/x86_64-pc-linux-gnu-library/4.3")
Packages <- c("tidyverse", "data.table", "magrittr", "tidycmprsk", "Rfast", "survminer", "ggsurvfit", "fastmatch", "future.apply", "ComplexHeatmap", "pbapply", "forestmodel", "clusterProfiler", "org.Hs.eg.db")
#"fastmatch", "h2o", , , "protr", , , "networkD3", "ggpubr", "RColorBrewer", "Biostrings", , "ggrepel")
lapply(Packages, require, character.only = TRUE)
rm(Packages)
options(dplyr.summarise.inform = FALSE)
```

#libraries
```{r}
library(ggpubr)
library(fastmatch)
library(readxl)
library(forcats)
library(survival)
library(survminer)
library(grid)
library(gridExtra)
library(data.table)
library(caret)
library(tidyverse)
library(future.apply)
library(magrittr)
library(tidycmprsk)
library(ggsurvfit)
library(patchwork)
library(cowplot)
library(gt)
library(gtsummary)
options(dplyr.summarise.inform = F)
library(devtools)

```


#Incidence of tumors
##Cox model separately by gender

```{r}
ukb_data = readRDS("objects/ukb_data.rds")

ptvs = grep("_g", colnames(ukb_data), value = T)
ptvs = grep("PTV", ptvs, value = T)

tumors = sort(unique(ukb_data$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

ukb_data$sex = factor(ukb_data$sex, levels = c(0,1), labels = c("female", "male"))

tumor_freq_data = as.data.frame(table(ukb_data$cancer_type, ukb_data$sex)) %>%
  set_colnames(c("cancer_type", "sex", "n")) %>% 
  mutate_if(is.factor, as.character) %>% 
  filter(cancer_type %in% tumors) %>% 
  filter(n >= 20)

plan(multisession(workers = 12))
i=0

res = lapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tempdf = ukb_data %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age, diag_date, cancer_type, all_of(p), gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
  colnames(tempdf)[9] = "PTVg"
  tumors_coxres = future_apply(tumor_freq_data, 1, function(t) {
    tempdfG = tempdf %>% filter(sex == t[2])
    tumorous = tempdfG %>% 
      filter(cancer_type == t[1]) %>% 
      arrange(diag_date) %>% 
      distinct(eid, .keep_all = T) %>% 
      mutate(time = as.numeric((diag_date - birthdate))) %>% 
      mutate(inc_age = round(time/365.25))
    nottumorous = tempdfG %>% 
      filter(!eid %in% tumorous$eid) %>% 
      distinct(eid, .keep_all = T) %>% 
      mutate(time = case_when(
        death == T ~ as.numeric(date_of_death - birthdate),
        death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
      )) %>% 
      mutate(inc_age = round(time/365.25))
    tempdfGU = bind_rows(tumorous, nottumorous)
    tempdfGU$status = as.factor(ifelse(tempdfGU$cancer_type == t[1], 2, 1))
    tempdfGU %<>% dplyr::select(eid, time, status, PTVg, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
    res.cox = coxph(Surv(time, status) ~ PTVg + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = tempdfGU, id = tempdfGU$eid)
    coxPvalues = summary(res.cox)$coefficients[,"Pr(>|z|)"]
    coxCoefs = summary(res.cox)$coefficients[,"coef"]
    names(coxPvalues)[grep("PTV", names(coxPvalues))] = "PTVg"
    names(coxCoefs)[grep("PTV", names(coxCoefs))] = "PTVg"
    coxPvalues = coxPvalues[fmatch(c("PTVg", paste0("gpca", 1:10)), names(coxPvalues))]
    coxCoefs = coxCoefs[fmatch(c("PTVg", paste0("gpca", 1:10)), names(coxCoefs))]
    names(coxPvalues) = paste0("p_", names(coxPvalues))
    names(coxCoefs) = paste0("coef_", names(coxCoefs))
    c(coxPvalues, coxCoefs)
  })
  out = cbind(tumor_freq_data, ptv_type = p, t(tumors_coxres))
  out
})
rm(i)

resdf = bind_rows(res)
save(resdf, file = "Objects/res_cox_model_sepgender")

##Heatmap
load("Objects/res_cox_model_sepgender")
resdf %<>% mutate(cancerSex = paste(cancer_type, sex, sep = "_"))

cancerSexs = sort(unique(resdf$cancerSex))
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(cancerSexs), dimnames = list(ptvs, cancerSexs))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVg[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancerSex == colnames(dataForHm)[j]] < 0.05, resdf$coef_PTVg[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancerSex == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(cancerSexs), dimnames = list(ptvs, cancerSexs))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVg[resdf$ptv_type == rownames(dataForHmP)[i] & resdf$cancerSex == colnames(dataForHmP)[j]] < 0.05, round(resdf$p_PTVg[resdf$ptv_type == rownames(dataForHmP)[i] & resdf$cancerSex == colnames(dataForHmP)[j]], digits = 4), NA)
  }
}



png(filename = "Plots/incidence_cox_analysis_1/heatmap_cox_model_sepgender.png", width = 40, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 7))
             })
draw(hm)
dev.off()

```

##Cox models with gender

```{r}
ukb_data = readRDS("Objects/ukb_data.rds")

ptvs = grep("_g", colnames(ukb_data), value = T)
ptvs = grep("PTV", ptvs, value = T)

tumors = sort(unique(ukb_data$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

ukb_data$sex = factor(ukb_data$sex, levels = c(0,1), labels = c("female", "male"))

tumor_freq_data = as.data.frame(table(ukb_data$cancer_type, ukb_data$sex)) %>%
  set_colnames(c("cancer_type", "sex", "n")) %>% 
  mutate_if(is.factor, as.character) %>% 
  filter(cancer_type %in% tumors) %>% 
  pivot_wider(id_cols = cancer_type, names_from = sex, values_from = n) %>% 
  filter(female >= 50, male >= 50)

plan(multisession(workers = 12))
i=0

res = lapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tempdf = ukb_data %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age, diag_date, cancer_type, all_of(p), gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
  colnames(tempdf)[9] = "PTVg"
  tumors_coxres = future_sapply(tumor_freq_data$cancer_type, function(t) {
    tumorous = tempdf %>% 
      filter(cancer_type == t) %>% 
      arrange(diag_date) %>% 
      distinct(eid, .keep_all = T) %>% 
      mutate(time = as.numeric((diag_date - birthdate))) %>% 
      mutate(inc_age = round(time/365.25))
    nottumorous = tempdf %>% 
      filter(!eid %in% tumorous$eid) %>% 
      distinct(eid, .keep_all = T) %>% 
      mutate(time = case_when(
        death == T ~ as.numeric(date_of_death - birthdate),
        death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
      )) %>% 
      mutate(inc_age = round(time/365.25))
    tempdfU = bind_rows(tumorous, nottumorous)
    tempdfU$status = as.factor(ifelse(tempdfU$cancer_type == t, 2, 1))
    tempdfU %<>% dplyr::select(eid, time, status, sex, PTVg, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
    res.cox <- coxph(Surv(time, status) ~ PTVg + sex + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = tempdfU, id = tempdfU$eid)
    coxPvalues = summary(res.cox)$coefficients[,"Pr(>|z|)"]
    coxCoefs = summary(res.cox)$coefficients[,"coef"]
    names(coxPvalues)[grep("PTV", names(coxPvalues))] = "PTVg"
    names(coxCoefs)[grep("PTV", names(coxCoefs))] = "PTVg"
    coxPvalues = coxPvalues[fmatch(c("PTVg", "sexmale", paste0("gpca", 1:10)), names(coxPvalues))]
    coxCoefs = coxCoefs[fmatch(c("PTVg", "sexmale", paste0("gpca", 1:10)), names(coxCoefs))]
    names(coxPvalues) = paste0("p_", names(coxPvalues))
    names(coxCoefs) = paste0("coef_", names(coxCoefs))
    c(coxPvalues, coxCoefs)
  })
  out = cbind(tumor_freq_data, ptv_type = p, t(tumors_coxres))
  out
})
rm(i)

resdf = bind_rows(res)
save(resdf, file = "Objects/res_cox_model_withgender")

##Heatmap
load("Objects/res_cox_model_withgender")

tumors = unique(resdf$cancer_type)
ptvs = unique(resdf$ptv_type)

#Coefficients
dataForHm = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHm)) {
  for(j in 1:ncol(dataForHm)) {
    dataForHm[i,j] = ifelse(resdf$p_PTVg[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]] < 0.05, resdf$coef_PTVg[resdf$ptv_type == rownames(dataForHm)[i] & resdf$cancer_type == colnames(dataForHm)[j]], NA)
  }
}

#P-values
dataForHmP = matrix(data = NA, nrow = length(ptvs), ncol = length(tumors), dimnames = list(ptvs, tumors))
for(i in 1:nrow(dataForHmP)) {
  for(j in 1:ncol(dataForHmP)) {
    dataForHmP[i,j] = ifelse(resdf$p_PTVg[resdf$ptv_type == rownames(dataForHmP)[i] & resdf$cancer_type == colnames(dataForHmP)[j]] < 0.05, round(resdf$p_PTVg[resdf$ptv_type == rownames(dataForHmP)[i] & resdf$cancer_type == colnames(dataForHmP)[j]], digits = 4), NA)
  }
}

png(filename = "Plots/incidence_cox_analysis_1/heatmap_cox_model_withgender.png", width = 30, height = 20, units = "cm", res = 300)
hm = Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })
draw(hm)
dev.off()

```

#Incidence of any tumor - Cox model

```{r}
ukb_data = readRDS("Objects/ukb_data.rds")

ptvs = grep("_g", colnames(ukb_data), value = T)
ptvs = grep("PTV", ptvs, value = T)

tumors = sort(unique(ukb_data$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

ukb_data$sex = factor(ukb_data$sex, levels = c(0,1), labels = c("female", "male"))

i=0

res = pbsapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tempdf = ukb_data %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age, diag_date, cancer_type, all_of(p), gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
  colnames(tempdf)[9] = "PTVg"
  tumorous = tempdf %>% 
    filter(cancer_type %in% tumors) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric((diag_date - birthdate))) %>% 
    mutate(inc_age = round(time/365.25))
  nottumorous = tempdf %>% 
    filter(!eid %in% tumorous$eid) %>% 
    filter(cancer_type == "No_cancer") %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = case_when(
      death == T ~ as.numeric(date_of_death - birthdate),
      death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
    )) %>% 
    mutate(inc_age = round(time/365.25))
  tempdfU = bind_rows(tumorous, nottumorous)
  tempdfU$status = as.factor(ifelse(tempdfU$cancer_type %in% tumors, 2, 1))
  tempdfU %<>% dplyr::select(eid, time, status, PTVg, sex, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
  res.cox <- coxph(Surv(time, status) ~ PTVg + sex + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = tempdfU, id = tempdfU$eid)
  coxPvalues = summary(res.cox)$coefficients[,"Pr(>|z|)"]
  coxCoefs = summary(res.cox)$coefficients[,"coef"]
  names(coxPvalues)[grep("PTV", names(coxPvalues))] = "PTVg"
  names(coxCoefs)[grep("PTV", names(coxCoefs))] = "PTVg"
  coxPvalues = coxPvalues[fmatch(c("PTVg", "sexmale", paste0("gpca", 1:10)), names(coxPvalues))]
  coxCoefs = coxCoefs[fmatch(c("PTVg", "sexmale", paste0("gpca", 1:10)), names(coxCoefs))]
  names(coxPvalues) = paste0("p_", names(coxPvalues))
  names(coxCoefs) = paste0("coef_", names(coxCoefs))
  c(ptv_type = p, coxPvalues, coxCoefs)
})
rm(i)
resdf = t(res)
resdf = as.data.frame(resdf)
resdf %<>% mutate_at(2:25, as.numeric)
save(resdf, file = "Objects/res_cox_model_anytumor")

#Generate Forest plots
pbsapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tempdf = ukb_data %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age, diag_date, cancer_type, all_of(p), gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
  colnames(tempdf)[9] = "PTVg"
  tumorous = tempdf %>% 
    filter(cancer_type %in% tumors) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric((diag_date - birthdate))) %>% 
    mutate(inc_age = round(time/365.25))
  nottumorous = tempdf %>% 
    filter(!eid %in% tumorous$eid) %>% 
    filter(cancer_type == "No_cancer") %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = case_when(
      death == T ~ as.numeric(date_of_death - birthdate),
      death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
    )) %>% 
    mutate(inc_age = round(time/365.25))
  tempdfU = bind_rows(tumorous, nottumorous)
  tempdfU$status = as.factor(ifelse(tempdfU$cancer_type %in% tumors, 2, 1))
  tempdfU %<>% dplyr::select(eid, time, status, PTVg, sex, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
  res.cox <- coxph(Surv(time, status) ~ PTVg + sex + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = tempdfU, id = tempdfU$eid)
  fig = forest_model(model = res.cox)
  ggsave(paste0("Plots/incidence_cox_analysis_1/cox_fp_anytumor_", p, ".jpg"), plot = fig, width = 40, height = 20, units = "cm", dpi = 150)
})


```

#Incidence of tumors II. - with frequent PTV_MAF genes
##Cox model separately by gender

```{r}
ukb_data = readRDS("Objects/ukb_data.rds")
ukb_data$cancer_type[ukb_data$cancer_type == "Brain/CNS"] = "Brain"
ukb_data$cancer_type[ukb_data$cancer_type == "Hodgkin lymphoma"] = "HodgkinLymphoma"
ukb_data$cancer_type[ukb_data$cancer_type == "Multiple myeloma"] = "MultipleMyeloma"
ukb_data$cancer_type[ukb_data$cancer_type == "Non-Hodgkin lymphoma"] = "NonHodgkinLymphoma"
ukb_data$sex = factor(ukb_data$sex, levels = c(0,1), labels = c("female", "male"))

ptvGeneFreqDF = readRDS("Objects/ptvGeneFreqDF.rds")
ptvGeneFreqDF$tumor[ptvGeneFreqDF$tumor == "Brain/CNS"] = "Brain"
ptvGeneFreqDF$tumor[ptvGeneFreqDF$tumor == "Hodgkin lymphoma"] = "HodgkinLymphoma"
ptvGeneFreqDF$tumor[ptvGeneFreqDF$tumor == "Multiple myeloma"] = "MultipleMyeloma"
ptvGeneFreqDF$tumor[ptvGeneFreqDF$tumor == "Non-Hodgkin lymphoma"] = "NonHodgkinLymphoma"

#gene_symbols = readRDS("Objects/gene_symbols.rds")
tumors = ptvGeneFreqDF$tumor

ptvs = grep("_g", colnames(ukb_data), value = T)
ptvs = grep("PTV", ptvs, value = T)
ptvs = grep("_MAF", ptvs, value = T)

tumor_freq_data = as.data.frame(table(ukb_data$cancer_type, ukb_data$sex)) %>%
  set_colnames(c("cancer_type", "sex", "n")) %>% 
  mutate_if(is.factor, as.character) %>% 
  filter(cancer_type %in% tumors) %>% 
  filter(n >= 20)

nottumorous = ukb_data %>% 
  dplyr::filter(cancer_type == "No_cancer") %>%
  distinct(eid, .keep_all = T) %>% 
  mutate(time = case_when(
    death == T ~ as.numeric(date_of_death - birthdate),
    death == F ~ as.numeric(max(date_of_death, na.rm = T) - birthdate)
  )) %>% 
  dplyr::select(eid, sex, cancer_type, time, all_of(ptvs), Genes_PTV_MAF, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)

tumorous = ukb_data %>% 
  filter(cancer_type != "No_cancer") %>% 
  mutate(time = as.numeric((diag_date - birthdate)))%>% 
  dplyr::select(eid, sex, diag_date, cancer_type, time, all_of(ptvs), Genes_PTV_MAF, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)

#sapply(ptvs, function(p) {dir.create(paste0("Plots/incidence_cox_analysis_2/", p))})

i=0
res = pblapply(ptvs, function(p) {
  i=i+1
  .GlobalEnv$i = i
  tumors_coxres = apply(tumor_freq_data, 1, function(t) {
    tumor = tumorous %>%
      filter(cancer_type == t[1]) %>% 
      filter(sex == t[2]) %>%
      arrange(diag_date) %>% 
      distinct(eid, .keep_all = T) %>% 
      mutate(status = 2) %>% 
      dplyr::select(eid, sex, cancer_type, time, status, all_of(p), Genes_PTV_MAF, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
    control = nottumorous %>% 
      filter(!eid %in% tumorous$eid) %>% 
      filter(sex == t[2]) %>% 
      mutate(status = 1) %>%
      dplyr::select(eid, sex, cancer_type, time, status, all_of(p), Genes_PTV_MAF, gpca1, gpca2, gpca3, gpca4, gpca5, gpca6, gpca7, gpca8, gpca9, gpca10)
    tempdfGU = bind_rows(tumor, control)
    colnames(tempdfGU)[6] = "PTVg"
    rm(control, tumor)
    
    #Frequent genes
    tempgenes = strsplit(ptvGeneFreqDF$freqGenesMAF_ENSG[ptvGeneFreqDF$tumor == t[1]], ",")[[1]]
    mat = sapply(tempgenes, function(tg) {
      grepl(tg, tempdfGU$Genes_PTV_MAF)
    })
    tempdfGU = cbind(tempdfGU, mat)
    l_tg = length(tempgenes)
    tempdfGU = tempdfGU[,c(1,4,5,6,8:ncol(tempdfGU))]
    
    #COX
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfGU)[4:ncol(tempdfGU)], collapse = "+")))
    res.cox <- coxph(myformula, data = tempdfGU, id = tempdfGU$eid)
    summary(res.cox)
    
    #Forest plot
    #fig = forest_model(model = res.cox)
    #ggsave(paste0("Plots/incidence_cox_analysis_2/", p, "/cox_fp_", t[1], "_", t[2], ".jpg"), plot = fig, width = 40, height = 40, units = "cm", dpi = 150)
    
    #OUTPUT
    c(summary(res.cox)$coefficients[1,"Pr(>|z|)"], summary(res.cox)$coefficients[1,"coef"], as.numeric(sapply(15:ncol(tempdfGU), function(y) c(fisher.test(table(tempdfGU$PTVg, tempdfGU[,y]))$p, unname(fisher.test(table(tempdfGU$PTVg, tempdfGU[,y]))$estimate)))))
  })
  m = max(lengths(tumors_coxres))
  tumors_coxres = lapply(tumors_coxres, function(z) c(z, rep(NA, (40-length(z)))))
  out = cbind(tumor_freq_data, ptv_type = p, do.call(rbind, tumors_coxres))
  colnames(out)[5:6] = c("p_PTVg", "coef_PTVg")
  out$p_PTVgAdj = p.adjust(out$p_PTVg, method = "BH")
  out
})
rm(i)

resdf = bind_rows(res)
save(resdf, file = "Objects/res_cox_model_sepgender_freqPTVgenes")

colnames(resdf)[seq(7,43,2)] = paste0("ensg_", 1:19, "_p")
colnames(resdf)[seq(8,44,2)] = paste0("ensg_", 1:19, "_coef")

```

