---
title: "incidence_by_age"
author: "Bagi Laura"
date: "2024-01-19"
output: html_document
---
#Libraries
```{r}
library(ggpubr)
library(fastmatch)
library(readxl)
library(forcats)
library(survival)
library(survminer)
library(grid)
library(gridExtra)
library(data.table)
library(caret)
library(tidyverse)
library(future.apply)
library(magrittr)
options(dplyr.summarise.inform = F)


```

#Files
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/icd_mapping")



```

#UKB age table basic
```{r}
ages_df = ukb_data_cancer %>%
  distinct(eid, age) %>%
  group_by(age) %>%
  summarize(Number_of_People = n()) %>%
  arrange(age) %>%
  mutate(
    cumulative_cases = cumsum(Number_of_People),
  )

temp_df = data.frame(age = 1:max(ukb_data_cancer$age))

ages_df_complete=temp_df %>% 
  left_join(ages_df, by = "age") %>%
  mutate(Number_of_People = ifelse(is.na(Number_of_People), 0, Number_of_People))

for(i in 2:nrow(ages_df_complete)){
  if(is.na(ages_df_complete$cumulative_cases[i]) & !is.na(ages_df_complete$cumulative_cases[i - 1])){
    ages_df_complete$cumulative_cases[i] = ages_df_complete$cumulative_cases[i - 1]
  }
}
l = length(unique(ukb_data_cancer$eid))
ages_df_complete$cumulative_cases[is.na(ages_df_complete$cumulative_cases)] = 0  
ages_df_complete$n.people = l - ages_df_complete$cumulative_cases

age_datas = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  tempdf_x = subset(ukb_data_cancer, cancer_type == x)
  tempdf_x = dplyr::arrange(tempdf_x, diag_date)
  tempdf_no_x = subset(ukb_data_cancer, cancer_type == "No_cancer")
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  unique_tempdf = rbind(tempdf_x, tempdf_no_x)
  unique_tempdf %<>% 
    mutate(age = case_when(
      cancer_type == x ~ diag_date - birthdate,
      death == T & is.na(diag_date) ~ date_of_death - birthdate,
      death == F & is.na(diag_date) ~ max(date_of_death, na.rm = T) - birthdate,
    ))
  unique_tempdf$age_in_years = floor(as.numeric(unique_tempdf$age)/365.25)
  unique_tempdf %>%
    filter(cancer_type == x) %>%
    group_by(age_in_years) %>%
    summarise(number_of_cases = n()) %>%
    mutate(cumulative_cases = cumsum(number_of_cases)) %>% 
    mutate(all_cases_minus_cases = max(nrow(unique_tempdf), default = 0) - cumulative_cases) %>%
    mutate(cancer_type = x, .before = "age_in_years") 

 })

age_tables = do.call(rbind, age_datas)
age_tables$n.people = ages_df_complete$n.people[match(age_tables$age_in_years, ages_df_complete$age)]
age_tables$age_associated_incidence = age_tables$number_of_cases/age_tables$n.people


  


```

#Age plots number 1
```{r}
ggplot(age_tables[age_tables$cancer_type == "Thyroid",], mapping = aes(x = age_in_years, y = age_associated_incidence)) +
  geom_point() +
  geom_smooth()

ggplot(age_tables[age_tables$cancer_type == "Melanoma",], mapping = aes(x = age_in_years, y = cumulative_cases)) +
  geom_point() +
  facet_wrap(~sex)

```

#Include sex
```{r}

ages_df_sex = ukb_data_cancer %>%
  distinct(eid, age, sex, PTV_universal_1) %>%
  group_by(age, sex, PTV_universal_1) %>%
  summarize(Number_of_People = n()) %>%
  arrange(age) %>%
  group_by(sex, PTV_universal_1) %>% 
  mutate(
    cumulative_cases = cumsum(Number_of_People)
  )

temp_df = expand.grid(age = 1:max(ukb_data_cancer$age), sex = 0:1)
 

ages_df_sex_complete = temp_df %>%
  left_join(ages_df_sex, by = c("age", "sex")) %>%
  mutate(Number_of_People = ifelse(is.na(Number_of_People), 0, Number_of_People))

ages_df_sex_temp = lapply(unique(ages_df_sex$sex), FUN = function(x){
  tempdf = ages_df_sex_complete[ages_df_sex_complete$sex == x, ]
  for(i in 2:nrow(tempdf)){
    if(is.na(tempdf$cumulative_cases[i]) & !is.na(tempdf$cumulative_cases[i - 1])){
      tempdf$cumulative_cases[i] = tempdf$cumulative_cases[i - 1]
    }
  }
  tempdf$cumulative_cases[is.na(tempdf$cumulative_cases)] = 0
  l = length(ukb_data_cancer$eid[ukb_data_cancer$sex == x])
  tempdf$n.people = l - tempdf$cumulative_cases
  tempdf
})

ages_df_sex_complete_2 = do.call(rbind, ages_df_sex_temp)



age_datas_skin = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){ 
  tempdf_x = subset(ukb_data_cancer, cancer_type == x)
  tempdf_x = arrange(tempdf_x, diag_date)
  tempdf_x$age = as.numeric(tempdf_x$diag_date - tempdf_x$birthdate)
  tempdf_no_x = subset(ukb_data_cancer, !(eid %in% tempdf_x$eid))
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_no_x$age = ifelse(tempdf_no_x$death == T, tempdf_no_x$date_of_death - tempdf_no_x$birthdate, max(tempdf_no_x$date_of_death, na.rm = T) - tempdf_no_x$birthdate)
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  unique_tempdf = rbind(tempdf_x, tempdf_no_x)
  unique_tempdf$diag_age_in_years = floor(as.numeric(unique_tempdf$age)/365.25)
  unique_tempdf %>%
    filter(cancer_type == x) %>%
    group_by(sex, diag_age_in_years) %>%
    summarise(number_of_cases = n()) %>%
    group_by(sex) %>%
    mutate(cumulative_cases_diag = cumsum(number_of_cases)) %>% 
    mutate(cancer_type = x, .before = "diag_age_in_years") 

 })

age_table_sex = bind_rows(age_datas_skin)


age_table_sex_final = age_table_sex %>% 
  left_join(ages_df_sex_complete_2, by = c("diag_age_in_years" = "age", "sex"))

age_table_sex_final$age_associated_incidence = age_table_sex_final$number_of_cases/age_table_sex_final$n.people


rm(age_table_sex, age_datas_skin, ages_df_sex_complete_2, ages_df_sex_temp, ages_df_sex_complete, temp_df, ages_df_sex)


```

#PTV universal 1
```{r}

ukb_data_cancer$cancer_type[is.na(ukb_data_cancer$cancer_type)] = "No_cancer"
tumors = unique(ukb_data_cancer$cancer_type)
tumors = tumors[tumors != "No_cancer"]

age_df_incidence = lapply(X = tumors, FUN = function(x){
  tempdf_x = subset(ukb_data_cancer, cancer_type == x)
  tempdf_x = dplyr::arrange(tempdf_x, diag_date)
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  tempdf_x %<>% mutate(inc_time = round(as.numeric((diag_date - birthdate))/365.25))
  tempdf_no_x = subset(ukb_data_cancer, cancer_type == "No_cancer")
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_no_x %<>% mutate(inc_time = case_when(
    death == T ~ round(as.numeric(date_of_death - birthdate)/365.25),
    death == F ~ round(as.numeric(max(date_of_death, na.rm = T) - birthdate)/365.25),
  ))
  minage = min(c(tempdf_x$inc_time, tempdf_no_x$inc_time))
  maxage = max(c(tempdf_x$inc_time, tempdf_no_x$inc_time))
  freq_tbl_x = tempdf_x %>% 
    group_by(inc_time, sex, PTV_universal_1) %>% 
    summarise(case_num = n()) 
  res = expand.grid(inc_time = seq(minage, maxage, 1), sex = unique(freq_tbl_x$sex), PTV_universal_1 = unique(freq_tbl_x$PTV_universal_1), stringsAsFactors = F) 
  res %<>% left_join(freq_tbl_x)
  res$case_num[is.na(res$case_num)] = 0
  res_l_0 = apply(X = unique(res[, c("sex", "PTV_universal_1")]), MARGIN = 1, FUN = function(y){
    res %>% filter(sex == y[1], PTV_universal_1 == y[2])
  })
  res_l_0 = lapply(X = res_l_0, FUN = function(k){
    k %<>%
      mutate(
        cumulative_cases = cumsum(case_num)
      )
    for(i in 2:nrow(k)){
      if(is.na(k$cumulative_cases[i]) & !is.na(k$cumulative_cases[i - 1])){
        k$cumulative_cases[i] = k$cumulative_cases[i - 1]
      }
    }
   
    k
  })
  res = bind_rows(res_l_0)
  freq_tbl_no_x = tempdf_no_x %>%
    group_by(age, sex, PTV_universal_1) %>%
    summarize(no_case_death_num = n()) %>%
    arrange(age) %>%
    group_by(sex, PTV_universal_1) %>% 
    mutate(
      cumulative_no_cases = cumsum(no_case_death_num)
    )
  res %<>% left_join(freq_tbl_no_x, by = c("inc_time" = "age", "sex", "PTV_universal_1")) 
  res$no_case_death_num[is.na(res$no_case_death_num)] = 0
  res_l = apply(X = unique(res[, c("sex", "PTV_universal_1")]), MARGIN = 1, FUN = function(y){
    res %>% filter(sex == y[1], PTV_universal_1 == y[2])
  })
  res_l = lapply(X = res_l, FUN = function(l){
    for(i in 2:nrow(l)){
      if(is.na(l$cumulative_no_cases[i]) & !is.na(l$cumulative_no_cases[i - 1])){
        l$cumulative_no_cases[i] = l$cumulative_no_cases[i - 1]
      }
    } 
    l
  })
  res = bind_rows(res_l)
  res$cumulative_no_cases[is.na(res$cumulative_no_cases)] = 0
  p = tempdf_no_x %>% 
    group_by(sex, PTV_universal_1) %>% 
    summarise(no_case_pop_num = n())
  res %<>% left_join(p)
  res %<>% mutate(no_case_alive = no_case_pop_num - cumulative_no_cases) 
  res %<>% mutate(pop_num = cumulative_cases + no_case_alive)
  res$PTV_universal_1 = factor(res$PTV_universal_1, levels = levels(tempdf_x$PTV_universal_1))
})
u = ukb_data_cancer %>%
  distinct(eid, sex, PTV_universal_1) %>% 
  group_by(sex, PTV_universal_1) %>% 
  summarise(n = n())


#Balazs
load("objects/ukb_data_cancer_final")
ukb_data_cancer$cancer_type[is.na(ukb_data_cancer$cancer_type)] = "No_cancer"
tumors = unique(ukb_data_cancer$cancer_type)
tumors = tumors[tumors != "No_cancer"]

age_inc_plots = lapply(X = tumors, FUN = function(x){
  tempdf_x = ukb_data_cancer %>% filter(cancer_type == x) %>% arrange(diag_date)
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  tempdf_x %<>% mutate(inc_time = round(as.numeric((diag_date - birthdate))/365.25),
                       final_age = case_when(
                         death == T ~ round(as.numeric(date_of_death - birthdate)/365.25),
                         death == F ~ round(as.numeric(max(date_of_death, na.rm = T) - birthdate)/365.25)))
  
  tempdf_no_x = ukb_data_cancer %>% filter(cancer_type == "No_cancer")
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_no_x %<>% mutate(inc_time = NA, 
                          final_age = case_when(
                            death == T ~ round(as.numeric(date_of_death - birthdate)/365.25),
                            death == F ~ round(as.numeric(max(date_of_death, na.rm = T) - birthdate)/365.25)))
  
  minage = min(c(tempdf_x$inc_time, tempdf_no_x$final_age))
  maxage = max(c(tempdf_x$inc_time, tempdf_no_x$final_age))
  res = expand.grid(inc_time = seq(minage, maxage, 1), sex = unique(ukb_data_cancer$sex), PTV_universal_1 = unique(tempdf_x$PTV_universal_1), stringsAsFactors = F) 
  res$PTV_universal_1 = factor(res$PTV_universal_1, levels = levels(tempdf_x$PTV_universal_1))

  res_case = tempdf_x %>% group_by(inc_time, sex, PTV_universal_1) %>% summarise(case = n())
  res %<>% left_join(res_case)
  res$case[is.na(res$case)] = 0
  
  res_nocase = tempdf_no_x %>% group_by(final_age, sex, PTV_universal_1) %>% summarise(no_case = n())
  
  res$no_case = 0
  for(i in 1:nrow(res_nocase)) {
    res$no_case[res$inc_time <= res_nocase$final_age[i] & res$sex == res_nocase$sex[i] & res$PTV_universal_1 == res_nocase$PTV_universal_1[i]] = res$no_case[res$inc_time <= res_nocase$final_age[i] & res$sex == res_nocase$sex[i] & res$PTV_universal_1 == res_nocase$PTV_universal_1[i]] + res_nocase$no_case[i]
  }
  
  res %<>% mutate(inc = case/(case+no_case))
  
  # ggplot(res) + 
  #   geom_point(mapping = aes(x = inc_time, y = inc, color = PTV_universal_1, shape = as.factor(sex))) + 
  #   geom_line(aes(x = inc_time, y = inc, color = PTV_universal_1, shape = as.factor(sex))) +
  #   facet_grid(rows = vars(sex), cols = vars(PTV_universal_1))
  
  ggplot(res, mapping = aes(x = inc_time, y = inc, color = PTV_universal_1, shape = as.factor(sex))) + 
    geom_point() + 
    geom_smooth() +
    facet_wrap(~sex) + 
    labs(title = x)
})

ggarrange(plotlist = age_inc_plots, ncol = 5, nrow = 5)
ggsave(filename = "plots/age_inc_plot_sex_PTV_universal_1.jpg", width = 100, height = 60, units = "cm", dpi = 300)

```



#Age-sex plots
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/age_table_sex")
ggplot(age_table_sex_final[age_table_sex_final$cancer_type == "Breast",], mapping = aes(x = diag_age_in_years, y = age_associated_incidence)) +
  geom_point() +
  facet_wrap(~sex)

ggplot(age_table_sex_final[age_table_sex_final$cancer_type == "Melanoma", ]) + 
  geom_point(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(sex))) +
  geom_smooth(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(sex)))

age_sex_list = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  ggplot(age_table_sex_final[age_table_sex_final$cancer_type == x, ]) + 
    geom_point(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(sex))) +
    geom_smooth(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(sex))) +
    scale_color_manual(values = c("0" = "red", "1" = "blue")) +
    ggtitle(label = "Age associated incidence", x) + xlab("Diagnosis age") + ylab("Incidence")
})

ggarrange(plotlist = age_sex_list, ncol = 5, nrow = 5, common.legend = T)
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/age_incidence_sex.jpg",  width = 80, height = 40, units = "cm", dpi = 300)


```

#Include skin for melanoma
```{r}

ages_df_skin = ukb_data_cancer %>%
  distinct(eid, age, s.color) %>%
  group_by(age, s.color) %>%
  summarize(Number_of_People = n()) %>%
  arrange(age) %>%
  group_by(s.color) %>% 
  mutate(
    cumulative_cases = cumsum(Number_of_People)
  )

ages_df_skin$s.color[is.na(ages_df_skin$s.color)] = "No data"


temp_df = expand.grid(age = 1:max(ukb_data_cancer$age), s.color = unique(ukb_data_cancer$s.color))
temp_df$s.color = factor(temp_df$s.color, levels = c(levels(temp_df$s.color), "No data"))
temp_df$s.color[is.na(temp_df$s.color)] = "No data"

ages_df_skin_complete = temp_df %>%
  left_join(ages_df_skin, by = c("age", "s.color")) %>%
  mutate(Number_of_People = ifelse(is.na(Number_of_People), 0, Number_of_People))


ages_df_skin_temp = lapply(unique(ages_df_skin$s.color), FUN = function(x){
  tempdf = ages_df_skin_complete[ages_df_skin_complete$s.color == x, ]
  for(i in 2:nrow(tempdf)){
    if(is.na(tempdf$cumulative_cases[i]) & !is.na(tempdf$cumulative_cases[i - 1])){
      tempdf$cumulative_cases[i] = tempdf$cumulative_cases[i - 1]
    }
  }
  tempdf$cumulative_cases[is.na(tempdf$cumulative_cases)] = 0
  l = length(ukb_data_cancer$eid[ukb_data_cancer$s.color == x])
  tempdf$n.people = l - tempdf$cumulative_cases
  tempdf
})

ages_df_skin_complete_2 = do.call(rbind, ages_df_skin_temp)


age_datas_skin = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){ 
  tempdf_x = subset(ukb_data_cancer, cancer_type == x)
  tempdf_x = arrange(tempdf_x, diag_date)
  tempdf_x$age = as.numeric(tempdf_x$diag_date - tempdf_x$birthdate)
  tempdf_no_x = subset(ukb_data_cancer, !(eid %in% tempdf_x$eid))
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_no_x$age = ifelse(tempdf_no_x$death == T, tempdf_no_x$date_of_death - tempdf_no_x$birthdate, max(tempdf_no_x$date_of_death, na.rm = T) - tempdf_no_x$birthdate)
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  unique_tempdf = rbind(tempdf_x, tempdf_no_x)
  unique_tempdf$diag_age_in_years = floor(as.numeric(unique_tempdf$age)/365.25)
  unique_tempdf$s.color[is.na(unique_tempdf$s.color)] = "No data"
  unique_tempdf %>%
    filter(cancer_type == x) %>%
    group_by(s.color, diag_age_in_years) %>%
    summarise(number_of_cases = n()) %>%
    group_by(s.color) %>%
    mutate(cumulative_cases_diag = cumsum(number_of_cases)) %>% 
    mutate(cancer_type = x, .before = "diag_age_in_years") 
 })

age_table_skin = bind_rows(age_datas_skin)
age_table_skin_final = age_table_skin %>% 
  left_join(ages_df_skin_complete_2, by = c("diag_age_in_years" = "age", "s.color"))

age_table_skin_final$age_associated_incidence = age_table_skin_final$number_of_cases/age_table_skin_final$n.people


rm(age_table_skin, age_datas_skin, ages_df_skin_complete_2, ages_df_skin_temp, ages_df_skin_complete, temp_df, ages_df_skin)

```

#Skin plot
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/age_table_skin")
groups_to_remove = c("Do not know", "No data")
age_table_skin_final = subset(age_table_skin_final, !(s.color %in% groups_to_remove))

ggplot(age_table_skin_final[age_table_skin_final$cancer_type == "Melanoma", ]) + 
  geom_point(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(s.color))) +
  geom_smooth(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(s.color))) +
  ggtitle(label = "Age associated incidence Melanoma") + xlab("Diagnosis age") + ylab("Incidence")

ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/age_incidence_by_skin.jpg", width = 60, height = 30, units = "cm", dpi = 300)


```

#Include ethnic
```{r}
#Ethnic groups

ethnic_df = data.frame(ethnic = c("White", "Mixed", "Asian or Asian British", "Black or Black British", "Chinese", "Other ethnic group", "Do not know", "Prefer not to answer"),
                        ethnic_code = c(1, 2, 3, 4, 5, 6, (-1), (-3)))

ukb_data_cancer$ethnic_1 = ifelse(is.na(as.numeric(ukb_data_cancer$ethnic_1)), 0, as.numeric(ukb_data_cancer$ethnic_1))

#ukb_data_cancer$ethnic_numb = as.integer(str_extract(ukb_data_cancer$ethnic_1, "-?\\d"))

ukb_data_cancer$ethnic_numb = ifelse(nchar(ukb_data_cancer$ethnic_1) == 4, substr(ukb_data_cancer$ethnic_1, 1,1), ukb_data_cancer$ethnic_1)
ukb_data_cancer$ethnic_group = ethnic_df$ethnic[fmatch(ukb_data_cancer$ethnic_numb, ethnic_df$ethnic_code)]


ages_df_ethnic = ukb_data_cancer %>%
  distinct(eid, age, ethnic_group) %>%
  group_by(age, ethnic_group) %>%
  summarize(Number_of_People = n()) %>%
  arrange(age) %>%
  group_by(ethnic_group) %>% 
  mutate(
    cumulative_cases = cumsum(Number_of_People)
  )

ages_df_ethnic$ethnic_group[is.na(ages_df_ethnic$ethnic_group)] = "No data"


temp_df = expand.grid(age = 1:max(ukb_data_cancer$age), ethnic_group = unique(ukb_data_cancer$ethnic_group))
temp_df$ethnic_group = factor(temp_df$ethnic_group, levels = c(levels(temp_df$ethnic_group), "No data"))
temp_df$ethnic_group[is.na(temp_df$ethnic_group)] = "No data"

ages_df_ethnic_complete = temp_df %>%
  left_join(ages_df_ethnic, by = c("age", "ethnic_group")) %>%
  mutate(Number_of_People = ifelse(is.na(Number_of_People), 0, Number_of_People))


ages_df_ethnic_temp = lapply(unique(ages_df_ethnic$ethnic_group), FUN = function(x){
  tempdf = ages_df_ethnic_complete[ages_df_ethnic_complete$ethnic_group == x, ]
  for(i in 2:nrow(tempdf)){
    if(is.na(tempdf$cumulative_cases[i]) & !is.na(tempdf$cumulative_cases[i - 1])){
      tempdf$cumulative_cases[i] = tempdf$cumulative_cases[i - 1]
    }
  }
  tempdf$cumulative_cases[is.na(tempdf$cumulative_cases)] = 0
  l = length(unique(ukb_data_cancer$eid[ukb_data_cancer$ethnic_group == x]))
  tempdf$n.people = l - tempdf$cumulative_cases
  tempdf
})

ages_df_ethnic_complete_2 = do.call(rbind, ages_df_ethnic_temp)


age_datas_ethnic = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){ 
  tempdf_x = subset(ukb_data_cancer, cancer_type == x)
  tempdf_x = arrange(tempdf_x, diag_date)
  tempdf_x$age = as.numeric(tempdf_x$diag_date - tempdf_x$birthdate)
  tempdf_no_x = subset(ukb_data_cancer, !(eid %in% tempdf_x$eid))
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_no_x$age = ifelse(tempdf_no_x$death == T, tempdf_no_x$date_of_death - tempdf_no_x$birthdate, max(tempdf_no_x$date_of_death, na.rm = T) - tempdf_no_x$birthdate)
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  unique_tempdf = rbind(tempdf_x, tempdf_no_x)
  unique_tempdf$diag_age_in_years = floor(as.numeric(unique_tempdf$age)/365.25)
  unique_tempdf$ethnic_group[is.na(unique_tempdf$ethnic_group)] = "No data"
  unique_tempdf %>%
    dplyr::filter(cancer_type == x) %>%
    group_by(ethnic_group, diag_age_in_years) %>%
    summarise(number_of_cases = n()) %>%
    group_by(ethnic_group) %>%
    mutate(cumulative_cases_diag = cumsum(number_of_cases)) %>% 
    mutate(cancer_type = x, .before = "diag_age_in_years") 
 })

age_table_ethnic = bind_rows(age_datas_ethnic)
age_table_ethnic_final = age_table_ethnic %>% 
  left_join(ages_df_ethnic_complete_2, by = c("diag_age_in_years" = "age", "ethnic_group"))

age_table_ethnic_final$age_associated_incidence = age_table_ethnic_final$number_of_cases/age_table_ethnic_final$n.people
age_table_ethnic_final
#save(age_table_ethnic_final, file = "C:/Users/bagil/Desktop/ukb/objects/age_ethnic")


rm(age_table_ethnic, age_datas_ethnic, ages_df_ethnic_complete_2, ages_df_ethnic_temp, ages_df_ethnic_complete, temp_df, ages_df_ethnic, groups_to_remove)

```

#Ethnic plots
```{r}

load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/age_ethnic")

groups_to_remove <- c("Do not know", "Prefer not to answer", "No data", "Other ethnic group")
age_table_ethnic_final = subset(age_table_ethnic_final, !(ethnic_group %in% groups_to_remove))

#age_table_ethnic_final$ethnic_group = factor(age_table_ethnic_final$ethnic_group, levels = c("White", "Mixed", "Asian or Asian British", "Black or Black British", "Chinese", "Other ethnic group"))

age_ethnic_list = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  tempdf = age_table_ethnic_final %>% 
    filter(cancer_type == x) %>% 
    add_count(ethnic_group) %>% 
    filter(n > 20)
  ggplot(tempdf) + 
    geom_point(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(ethnic_group))) +
    geom_smooth(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(ethnic_group))) +
    scale_color_manual(values = c("White" = "red", "Mixed" = "blue", "Asian or Asian British" = "green", "Black or Black British" = "yellow", "Chinese" = "brown", "Other ethnic group" = "pink")) +
    theme(legend.position = "right") +
    ggtitle(label = "Age associated incidence", x) + xlab("Diagnosis age") + ylab("Incidence")
})


#legend_ethnic = get_legend(age_ethnic_list[[1]])
#plots_ethnic = plot_grid(plotlist = age_ethnic_list, ncol = 5, align = "h", labels = "AUTO") +
  #theme(legend.position = "top")
#print(plots_ethnic)

#plots_without_legend <- plot_grid(plotlist = age_ethnic_list, ncol = 5, align = "h", labels = "AUTO")
#combined_plot <- plot_grid(plots_without_legend, legend_ethnic, ncol = 1, rel_heights = c(1, 0.1))
#print(combined_plot)

ethnic_plots = ggarrange(plotlist = age_ethnic_list, ncol = 5, nrow = 5)

ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/age_incidence_ethnic_f20.jpg", plot = ethnic_plots, width = 80, height = 40, units = "cm", dpi = 300)


```


#Include PTV burden group 1
```{r}

#Ages and burdens
ages_df_burden = ukb_data_cancer %>%
  distinct(eid, age, PTV_burden_group) %>%
  group_by(age, PTV_burden_group) %>%
  summarize(Number_of_People = n()) %>%
  arrange(age) %>%
  group_by(PTV_burden_group) %>% 
  mutate(
    cumulative_cases = cumsum(Number_of_People)
  )

temp_df = expand.grid(age = 1:max(ukb_data_cancer$age), PTV_burden_group = levels(ukb_data_cancer$PTV_burden_group), stringsAsFactors = F)

ages_df_burden_complete = temp_df %>%
  left_join(ages_df_burden, by = c("age", "PTV_burden_group")) %>%
  mutate(Number_of_People = ifelse(is.na(Number_of_People), 0, Number_of_People))

ages_df_burden_temp = lapply(unique(ages_df_burden$PTV_burden_group), FUN = function(x){
  tempdf = ages_df_burden_complete[ages_df_burden_complete$PTV_burden_group == x, ]
  for(i in 2:nrow(tempdf)){
    if(is.na(tempdf$cumulative_cases[i]) & !is.na(tempdf$cumulative_cases[i - 1])){
      tempdf$cumulative_cases[i] = tempdf$cumulative_cases[i - 1]
    }
  }
  tempdf$cumulative_cases[is.na(tempdf$cumulative_cases)] = 0
  l = length(unique(ukb_data_cancer$eid[ukb_data_cancer$PTV_burden_group == x]))
  tempdf$n.people = l - tempdf$cumulative_cases
  tempdf
})

ages_df_Burden_complete_2 = do.call(rbind, ages_df_burden_temp)

#Table
age_datas_burden = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){ 
  tempdf_x = subset(ukb_data_cancer, cancer_type == x)
  tempdf_x = dplyr::arrange(tempdf_x, diag_date)
  tempdf_no_x = subset(ukb_data_cancer, cancer_type == "No_cancer")
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  unique_tempdf = rbind(tempdf_x, tempdf_no_x)
  unique_tempdf %<>% 
    mutate(age = case_when(
      cancer_type == x ~ diag_date - birthdate,
      death == T & is.na(diag_date) ~ date_of_death - birthdate,
      death == F & is.na(diag_date) ~ max(date_of_death, na.rm = T) - birthdate,
    ))
  unique_tempdf$diag_age_in_years = floor(as.numeric(unique_tempdf$age)/365.25)
  unique_tempdf$PTV_burden_group[is.na(unique_tempdf$PTV_burden_group)] = "No data"
  unique_tempdf$PTV_burden_group = factor(unique_tempdf$PTV_burden_group, ordered = T)
  unique_tempdf %>%
    filter(cancer_type == x) %>%
    group_by(PTV_burden_group, diag_age_in_years) %>%
    summarise(number_of_cases = n()) %>%
    group_by(PTV_burden_group) %>%
    mutate(cumulative_cases_diag = cumsum(number_of_cases)) %>% 
    mutate(cancer_type = x, .before = "diag_age_in_years") 

 })

age_table_burden = bind_rows(age_datas_burden)
age_table_burden_final = age_table_burden %>% 
  left_join(ages_df_Burden_complete_2, by = c("diag_age_in_years" = "age", "PTV_burden_group"))

age_table_burden_final$age_associated_incidence = age_table_burden_final$number_of_cases/age_table_burden_final$n.people

rm(age_table_burden, age_datas_burden, ages_df_Burden_complete_2, ages_df_burden_temp, ages_df_burden_complete, temp_df, ages_df_burden)

```

#PTV burden plots group 1
```{r}

#load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/age_table_burden")
age_burden_list = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  ggplot(age_table_burden_final[age_table_burden_final$cancer_type == x, ]) + 
    geom_point(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(PTV_burden_group))) +
    geom_smooth(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(PTV_burden_group))) +
    scale_color_manual(values = c("High" = "purple", "Low" = "green" ))+
    ggtitle(label = "Age associated incidence", x) + xlab("Diagnosis age") + ylab("Incidence")
})

ggarrange(plotlist = age_burden_list, ncol = 5, nrow = 5, common.legend = T)
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Incidence/Age incidence/age_incidence_gburden_g1.png",  width = 80, height = 40, units = "cm", dpi = 300)



```

#PTV burden group 2
```{r}
#Ages and burdens
ages_df_burden = ukb_data_cancer %>%
  distinct(eid, age, PTV_burden_group_2) %>%
  group_by(age, PTV_burden_group_2) %>%
  summarize(Number_of_People = n()) %>%
  arrange(age) %>%
  group_by(PTV_burden_group_2) %>% 
  mutate(
    cumulative_cases = cumsum(Number_of_People)
  )

temp_df = expand.grid(age = 1:max(ukb_data_cancer$age), PTV_burden_group_2 = levels(ukb_data_cancer$PTV_burden_group_2), stringsAsFactors = F)

ages_df_burden_complete = temp_df %>%
  left_join(ages_df_burden, by = c("age", "PTV_burden_group_2")) %>%
  mutate(Number_of_People = ifelse(is.na(Number_of_People), 0, Number_of_People))

ages_df_burden_temp = lapply(unique(ages_df_burden$PTV_burden_group_2), FUN = function(x){
  tempdf = ages_df_burden_complete[ages_df_burden_complete$PTV_burden_group_2 == x, ]
  for(i in 2:nrow(tempdf)){
    if(is.na(tempdf$cumulative_cases[i]) & !is.na(tempdf$cumulative_cases[i - 1])){
      tempdf$cumulative_cases[i] = tempdf$cumulative_cases[i - 1]
    }
  }
  tempdf$cumulative_cases[is.na(tempdf$cumulative_cases)] = 0
  l = length(unique(ukb_data_cancer$eid[ukb_data_cancer$PTV_burden_group_2 == x]))
  tempdf$n.people = l - tempdf$cumulative_cases
  tempdf
})

ages_df_Burden_complete_2 = do.call(rbind, ages_df_burden_temp)

#Table
age_datas_burden = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){ 
  tempdf_x = subset(ukb_data_cancer, cancer_type == x)
  tempdf_x = dplyr::arrange(tempdf_x, diag_date)
  tempdf_no_x = subset(ukb_data_cancer, cancer_type == "No_cancer")
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  unique_tempdf = rbind(tempdf_x, tempdf_no_x)
  unique_tempdf %<>% 
    mutate(age = case_when(
      cancer_type == x ~ diag_date - birthdate,
      death == T & is.na(diag_date) ~ date_of_death - birthdate,
      death == F & is.na(diag_date) ~ max(date_of_death, na.rm = T) - birthdate,
    ))
  unique_tempdf$diag_age_in_years = floor(as.numeric(unique_tempdf$age)/365.25)
  unique_tempdf$PTV_burden_group_2[is.na(unique_tempdf$PTV_burden_group_2)] = "No data"
  unique_tempdf$PTV_burden_group_2 = factor(unique_tempdf$PTV_burden_group_2, ordered = T)
  unique_tempdf %>%
    filter(cancer_type == x) %>%
    group_by(PTV_burden_group_2, diag_age_in_years) %>%
    summarise(number_of_cases = n()) %>%
    group_by(PTV_burden_group_2) %>%
    mutate(cumulative_cases_diag = cumsum(number_of_cases)) %>% 
    mutate(cancer_type = x, .before = "diag_age_in_years") 

 })

age_table_burden = bind_rows(age_datas_burden)
age_table_burden_final_2 = age_table_burden %>% 
  left_join(ages_df_Burden_complete_2, by = c("diag_age_in_years" = "age", "PTV_burden_group_2"))

age_table_burden_final_2$age_associated_incidence = age_table_burden_final_2$number_of_cases/age_table_burden_final_2$n.people

rm(age_table_burden, age_datas_burden, ages_df_Burden_complete_2, ages_df_burden_temp, ages_df_burden_complete, temp_df, ages_df_burden)
save(age_table_burden_final_2 ,file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/age_table_burden_g2")

```


#PTV burden plots group 2
```{r}
#load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/age_table_burden_g2")

age_burden_list_2 = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  ggplot(age_table_burden_final_2[age_table_burden_final_2$cancer_type == x, ]) + 
  geom_point(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(PTV_burden_group_2))) +
  geom_smooth(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(PTV_burden_group_2))) +
    scale_color_manual(values = c("High" = "purple", "Medium" = "brown","Low" = "green" ))+
  ggtitle(label = "Age associated incidence", x) + xlab("Diagnosis age") + ylab("Incidence")
})

ggarrange(plotlist = age_burden_list_2, ncol = 5, nrow = 5, common.legend = T)
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Incidence/Age incidence/age_incidence_gburden_g2.png",  width = 80, height = 40, units = "cm", dpi = 300)


```

#PTV burden group 3
```{r}
#Age inlcude PTV burden
ages_df_burden = ukb_data_cancer %>%
  distinct(eid, age, PTV_burden_group_3) %>%
  group_by(age, PTV_burden_group_3) %>%
  summarize(Number_of_People = n()) %>%
  arrange(age) %>%
  group_by(PTV_burden_group_3) %>% 
  mutate(
    cumulative_cases = cumsum(Number_of_People)
  )

temp_df = expand.grid(age = 1:max(ukb_data_cancer$age), PTV_burden_group_3 = levels(ukb_data_cancer$PTV_burden_group_3), stringsAsFactors = F)

ages_df_burden_complete = temp_df %>%
  left_join(ages_df_burden, by = c("age", "PTV_burden_group_3")) %>%
  mutate(Number_of_People = ifelse(is.na(Number_of_People), 0, Number_of_People))

ages_df_burden_temp = lapply(unique(ages_df_burden$PTV_burden_group_3), FUN = function(x){
  tempdf = ages_df_burden_complete[ages_df_burden_complete$PTV_burden_group_3 == x, ]
  for(i in 2:nrow(tempdf)){
    if(is.na(tempdf$cumulative_cases[i]) & !is.na(tempdf$cumulative_cases[i - 1])){
      tempdf$cumulative_cases[i] = tempdf$cumulative_cases[i - 1]
    }
  }
  tempdf$cumulative_cases[is.na(tempdf$cumulative_cases)] = 0
  l = length(unique(ukb_data_cancer$eid[ukb_data_cancer$PTV_burden_group_3 == x]))
  tempdf$n.people = l - tempdf$cumulative_cases
  tempdf
})

ages_df_Burden_complete_2 = do.call(rbind, ages_df_burden_temp)

#Table
age_datas_burden = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){ 
  tempdf_x = subset(ukb_data_cancer, cancer_type == x)
  tempdf_x = dplyr::arrange(tempdf_x, diag_date)
  tempdf_no_x = subset(ukb_data_cancer, cancer_type == "No_cancer")
  tempdf_no_x = tempdf_no_x[!duplicated(tempdf_no_x$eid), ]
  tempdf_x = tempdf_x[!duplicated(tempdf_x$eid), ]
  unique_tempdf = rbind(tempdf_x, tempdf_no_x)
  unique_tempdf %<>% 
    mutate(age = case_when(
      cancer_type == x ~ diag_date - birthdate,
      death == T & is.na(diag_date) ~ date_of_death - birthdate,
      death == F & is.na(diag_date) ~ max(date_of_death, na.rm = T) - birthdate,
    ))
  unique_tempdf$diag_age_in_years = floor(as.numeric(unique_tempdf$age)/365.25)
  unique_tempdf$PTV_burden_group_3[is.na(unique_tempdf$PTV_burden_group_3)] = "No data"
  unique_tempdf$PTV_burden_group_3 = factor(unique_tempdf$PTV_burden_group_3, ordered = T)
  unique_tempdf %>%
    filter(cancer_type == x) %>%
    group_by(PTV_burden_group_3, diag_age_in_years) %>%
    summarise(number_of_cases = n()) %>%
    group_by(PTV_burden_group_3) %>%
    mutate(cumulative_cases_diag = cumsum(number_of_cases)) %>% 
    mutate(cancer_type = x, .before = "diag_age_in_years") 

 })

age_table_burden = bind_rows(age_datas_burden)
age_table_burden_final_3 = age_table_burden %>% 
  left_join(ages_df_Burden_complete_2, by = c("diag_age_in_years" = "age", "PTV_burden_group_3"))

age_table_burden_final_3$age_associated_incidence = age_table_burden_final_3$number_of_cases/age_table_burden_final_3$n.people

#save(age_table_burden_final_3, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/age_table_burden_g3")
rm(age_table_burden, age_datas_burden, ages_df_Burden_complete_2, ages_df_burden_temp, ages_df_burden_complete, temp_df, ages_df_burden)

```

#PTV burden plots group 3
```{r}

#load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/age_table_burden_g3")

age_burden_list_3 = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  ggplot(age_table_burden_final_3[age_table_burden_final_3$cancer_type == x, ]) + 
  geom_point(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(PTV_burden_group_3))) +
  geom_smooth(mapping = aes(x = diag_age_in_years, y = age_associated_incidence, color = factor(PTV_burden_group_3))) +
    scale_color_manual(values = c("High" = "purple", "Medium" = "brown","Low" = "green" ))+
  ggtitle(label = "Age associated incidence", x) + xlab("Diagnosis age") + ylab("Incidence")
})

ggarrange(plotlist = age_burden_list_3, ncol = 5, nrow = 5, common.legend = T)
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Incidence/Age incidence/age_incidence_gburden_g3.png",  width = 80, height = 40, units = "cm", dpi = 300)

```

