---
title: "L_104_Synonym_cntr_surv"
author: "Bagi Laura"
date: "2024-12-10"
output: html_document
---
#Libraries
```{r}
library(ggpubr)
library(fastmatch)
library(readxl)
library(forcats)
library(survival)
library(survminer)
library(grid)
library(gridExtra)
library(data.table)
library(caret)
library(tidyverse)
library(future.apply)
library(magrittr)
library(tidycmprsk)
library(ggsurvfit)
library(patchwork)
library(cowplot)
library(gt)
library(gtsummary)
library(devtools)
library(pbapply)
library(broom)
library(pheatmap)
library(RColorBrewer)
library(circlize)
library(dendsort)
library(forestmodel)
options(dplyr.summarise.inform = F)

```

#Loads
```{r}

load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_ptv")
ukb_data$caucasian = factor(ukb_data$caucasian, levels = c(0,1), labels = c("not_caucasian", "caucasian"))
ukb_data = ukb_data %>% 
  filter(caucasian == "caucasian")

#Values
ptvs = grep("PTV", colnames(ukb_data), value = T)
ptvs = ptvs[!grepl("Genes_", ptvs)]
ptvs_maf = ptvs[!(ptvs %in% c("PTV", "PTVim", "PTVtsg", "PTVpli","PTV_g90", "PTV_g95", "PTVim_g90", "PTVim_g95", "PTVtsg_g90", "PTVtsg_g95", "PTVpli_g90"))]

tumors = sort(unique(ukb_data$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

```

#FineGray model
##Table
```{r}

#Freq table
tumor_freq_data = as.data.frame(table(ukb_data$cancer_type, ukb_data$sex)) %>%
  set_colnames(c("cancer_type", "sex", "n")) %>% 
  mutate_if(is.factor, as.character) %>% 
  filter(cancer_type %in% tumors) %>% 
  pivot_wider(id_cols = cancer_type, names_from = sex, values_from = n) 

gpca = paste0("gpca", 1:10)

tumorous_all = ukb_data %>% 
      filter(cancer_type %in% tumors) %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age_at_cancer, diag_date, cancer_type, death_type, synonym_burden, all_of(ptvs_maf), all_of(gpca))
nottumorous_all = ukb_data %>% 
      filter(cancer_type == "No_cancer") %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age_at_cancer, diag_date, cancer_type, death_type, synonym_burden, all_of(ptvs_maf), all_of(gpca))


max_d_date = max(ukb_data$date_of_death, na.rm = T)

plan(multisession(workers = 3))
tumors_grayres = pblapply(tumor_freq_data$cancer_type, function(t) {
  tumorous_d = tumorous_all %>% 
    filter(cancer_type == t & death_type == t) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumorous_all %>% 
    filter(cancer_type == t & death_type != t) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(max_d_date - diag_date))
  tempdfU = bind_rows(tumorous_d, tumorous_alive)
  tempdfU = tempdfU %>% 
    mutate(status = case_when(
      death == F ~ 0,
      death == T & death_type == t ~ 1,
      death == T & death_type != t ~ 2
    ))
  tempdfU %<>% dplyr::select(eid, time, status, sex, synonym_burden, age_at_cancer, all_of(gpca))
  colnames(tempdfU)[5] = "synonym_burden"
  tempdfU$status = as.factor(tempdfU$status)
  sex_counts = table(tempdfU$sex)
  if (length(sex_counts) == 2 & all(sex_counts >= 50) & length(table(tempdfU$status)) == 3){
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[4:ncol(tempdfU)], collapse = "+")))
    res.inc = crr(myformula, data = tempdfU, id = tempdfU$eid)
  } else if ("female" %in% names(sex_counts) & sex_counts["female"] >= 50 & length(table(tempdfU$status)) == 3) {
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[5:ncol(tempdfU)], collapse = "+")))
    res.inc = crr(myformula, data = tempdfU %>% filter(sex == "female"), id = tempdfU$eid)
  } else if ("male" %in% names(sex_counts) & sex_counts["male"] >= 50 & length(table(tempdfU$status)) == 3) {
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[5:ncol(tempdfU)], collapse = "+")))
    res.inc = crr(myformula, data = tempdfU %>% filter(sex == "male"), id = tempdfU$eid)
  } else { message("No competing risk in:", t)}
  tidy_res = broom::tidy(res.inc)
  data.frame(
    cancer_type = t,
    term = tidy_res$term,
    coef = tidy_res$estimate, 
    p_value = tidy_res$p.value
  )
})
grayres_df = do.call(rbind, tumors_grayres)
grayres_wide = grayres_df %>%
  pivot_wider(
    id_cols = cancer_type,
    names_from = term,
    values_from = c(coef, p_value))
out = tumor_freq_data %>%
  left_join(grayres_wide, by = "cancer_type") 

syn_res = out


save(syn_res, file = "objects/res_gray_model_synonym")

```

##Heatmap
```{r}

load("objects/res_gray_model_synonym")
synonym = "synonym"

dataForHm = matrix(data = NA, nrow = 1, ncol = length(tumors), dimnames = list(synonym, tumors))

for(j in 1:ncol(dataForHm)) {
  dataForHm[j] = ifelse(syn_res$p_value_synonym_burden[syn_res$cancer_type == colnames(dataForHm)[j]] < 0.05, syn_res$coef_synonym_burden[syn_res$cancer_type == colnames(dataForHm)[j]], NA)
}


#P-values
dataForHmP =  matrix(data = NA, nrow = 1, ncol = length(tumors), dimnames = list(synonym, tumors))
for(j in 1:ncol(dataForHmP)) {
  dataForHmP[j] = ifelse(syn_res$p_value_synonym_burden[syn_res$cancer_type == colnames(dataForHmP)[j]] < 0.05, round(syn_res$p_value_synonym_burden[syn_res$cancer_type == colnames(dataForHmP)[j]], digits = 4), NA)
}

hm = ComplexHeatmap::Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-10, 0, 10), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })

```

#Cox model
##Overall
```{r}

tumor_freq_data = as.data.frame(table(ukb_data$cancer_type, ukb_data$sex)) %>%
  set_colnames(c("cancer_type", "sex", "n")) %>% 
  mutate_if(is.factor, as.character) %>% 
  filter(cancer_type %in% tumors) %>% 
  pivot_wider(id_cols = cancer_type, names_from = sex, values_from = n) 

gpca = paste0("gpca", 1:10)

tumorous_all = ukb_data %>% 
      filter(cancer_type %in% tumors) %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age, age_at_cancer, diag_date, cancer_type, death_type, metastati_tumor, synonym_burden, caucasian, all_of(ptvs), all_of(gpca))
nottumorous_all = ukb_data %>% 
      filter(cancer_type == "No_cancer") %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age, age_at_cancer, diag_date, cancer_type, death_type, metastati_tumor, synonym_burden, caucasian, all_of(ptvs), all_of(gpca))



max_d_date = max(ukb_data$date_of_death, na.rm = T)

plan(multisession(workers = 3))

tumors_survres = pbsapply(tumor_freq_data$cancer_type, function(t) {
  tumorous_d = tumorous_all %>% 
    filter(cancer_type == t & death == T) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumorous_all %>% 
    filter(cancer_type == t & death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(max_d_date - diag_date))
  tempdfU = bind_rows(tumorous_d, tumorous_alive)
  tempdfU$event = as.numeric(ifelse(tempdfU$death == T, 1, 0))
  tempdfU %<>% dplyr::select(eid, time, event, sex, synonym_burden, age_at_cancer, all_of(gpca))
  myformula = as.formula(paste('Surv(time, event) ~ ', paste0(colnames(tempdfU)[4:ncol(tempdfU)], collapse = "+")))
  res.surv = coxph(myformula, data = tempdfU)
  coxPvalues = summary(res.surv)$coefficients[,"Pr(>|z|)"]
  coxCoefs = summary(res.surv)$coefficients[,"coef"]
  names(coxPvalues)[grep("synonym_burden", names(coxPvalues))] = "synonym"
  names(coxCoefs)[grep("synonym_burden", names(coxCoefs))] = "synonym"
  coxPvalues = coxPvalues[fmatch(c("sexmale", "synonym", "age_at_cancer", paste0("gpca", 1:10)), names(coxPvalues))]
  coxCoefs = coxCoefs[fmatch(c("sexmale", "synonym", "age_at_cancer", paste0("gpca", 1:10)), names(coxPvalues))]
  names(coxPvalues) = paste0("p_", names(coxPvalues))
  names(coxCoefs) = paste0("coef_", names(coxCoefs))
  c(coxPvalues, coxCoefs)
})
out = cbind(tumor_freq_data, t(tumors_survres))
#colnames(out)[seq(5,ncol(out),2)] = c("coef_PTVvar", "coef_sexmale", paste0("coef_gpca", 1:10))
#colnames(out)[seq(6,ncol(out),2)] = c("p_PTVvar", "p_sexmale", paste0("p_gpca", 1:10))
syn_cox = out

save(syn_cox, file = "objects/res_syn_cox")

```

###Heatmap
```{r}

load("objects/res_syn_cox")
synonym = "synonym"

dataForHm = matrix(data = NA, nrow = 1, ncol = length(tumors), dimnames = list(synonym, tumors))
for(j in 1:ncol(dataForHm)) {
  dataForHm[j] = ifelse(syn_cox$p_synonym[syn_cox$cancer_type == colnames(dataForHm)[j]] < 0.05, syn_cox$coef_synonym[syn_cox$cancer_type == colnames(dataForHm)[j]], NA)
}


#P-values
dataForHmP =  matrix(data = NA, nrow = 1, ncol = length(tumors), dimnames = list(synonym, tumors))
for(j in 1:ncol(dataForHmP)) {
  dataForHmP[j] = ifelse(syn_cox$p_synonym[syn_cox$cancer_type == colnames(dataForHmP)[j]] < 0.05, round(syn_cox$p_synonym[syn_cox$cancer_type == colnames(dataForHmP)[j]], digits = 4), NA)
}

hm = ComplexHeatmap::Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })

```

###Forestplot
```{r}

out_dir = "plots/Survival/102_forest/"
pdf_width = 6 
pdf_height = 10
max_d_date = max(ukb_data$date_of_death, na.rm = T)

pdf_filename = paste0(out_dir, "forest_surv_syn_oa", ".pdf")
pdf(pdf_filename, onefile = T, width = pdf_width, height = pdf_height)
tumors_survres = pblapply(tumor_freq_data$cancer_type, function(t) {
  tumorous_d = tumorous_all %>% 
    filter(cancer_type == t & death == T) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumorous_all %>% 
    filter(cancer_type == t & death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(max_d_date - diag_date))
  tempdfU = bind_rows(tumorous_d, tumorous_alive)
  tempdfU$status = as.numeric(ifelse(tempdfU$death == T, 1, 0))
  tempdfU %<>% dplyr::select(eid, time, status, sex, synonym_burden, age_at_cancer, all_of(gpca))
  #colnames(tempdfU)[5] = "PTVvar"
  gender_counts = table(tempdfU$sex)
  #if (any(gender_counts < 20)) {
  #tempdfU <- tempdfU[tempdfU$sex %in% names(gender_counts)[gender_counts >= 20], ]
  #print("Excluding gender categories with fewer than 20 individuals.")}
  if (length(table(tempdfU$synonym_burden[tempdfU$status == 1])) > 1 & length(unique(tempdfU$sex)) == 2 & all(gender_counts >= 20)) {
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[4:ncol(tempdfU)], collapse = "+")))
    hr_model = survival::coxph(myformula, data = as.data.frame(tempdfU))
  } else if (length(table(tempdfU$synonym_burden[tempdfU$status == 1])) == 1 & length(unique(tempdfU$sex)) == 1) { 
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[6:ncol(tempdfU)], collapse = "+")))
    hr_model = survival::coxph(myformula, data = as.data.frame(tempdfU))
  } else if (length(table(tempdfU$synonym_burden[tempdfU$status == 1])) > 1 & all(table(tempdfU$sex) >= 20)) {
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[5:ncol(tempdfU)], collapse = "+")))
    hr_model =survival::coxph(myformula, data = as.data.frame(tempdfU))
  } else {
    hr_model = survival::coxph(Surv(time, status) ~ sex + age_at_cancer + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = as.data.frame(tempdfU))
  }
  panels = list(list(width = 0.1, display = ~variable, fontface = "bold", heading = "synonym"), list(width = 0.1, display = ~level), list(width = 0.05, display = ~n, hjust = 1, heading = "N"), list(width = 0.03, item = "vline", hjust = 0.5), list(width = 0.03, item = "vline", hjust = 0.5), list(item = "forest", heading = t, linetype = "dashed", line_x = 0), list(width = 0.03), list(width = 0.12, display = ~ ifelse(reference, "Reference", sprintf("%0.2f (%0.2f - %0.2f)",trans(estimate), trans(conf.low), trans(conf.high))), display_na = NA, heading="95% CI (Range)"), list(width = 0.05,display = ~ ifelse(reference, "", format.pval(p.value, digits = 1, eps = 0.001)), display_na = NA, hjust = 1, heading = "p"), list(width = 0.03))
  forest = forestmodel::forest_model(hr_model, format_options = forest_model_format_options(text_size = 3), panels = panels, exclude_infinite_cis = T, limits = c(-2,2))
  print(forest)
})
dev.off()

```

##Disease specific
```{r}

tumor_freq_data = as.data.frame(table(ukb_data$cancer_type, ukb_data$sex)) %>%
  set_colnames(c("cancer_type", "sex", "n")) %>% 
  mutate_if(is.factor, as.character) %>% 
  filter(cancer_type %in% tumors) %>% 
  pivot_wider(id_cols = cancer_type, names_from = sex, values_from = n) 

gpca = paste0("gpca", 1:10)

tumorous_all = ukb_data %>% 
      filter(cancer_type %in% tumors) %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age, age_at_cancer, diag_date, cancer_type, death_type, metastati_tumor, synonym_burden, caucasian, all_of(ptvs), all_of(gpca))
nottumorous_all = ukb_data %>% 
      filter(cancer_type == "No_cancer") %>% 
    dplyr::select(eid, birthdate, sex, death, date_of_death, age, age_at_cancer, diag_date, cancer_type, death_type, metastati_tumor, synonym_burden, caucasian, all_of(ptvs), all_of(gpca))



max_d_date = max(ukb_data$date_of_death, na.rm = T)

plan(multisession(workers = 3))

tumors_survres = pbsapply(tumor_freq_data$cancer_type, function(t) {
  tumorous_d = tumorous_all %>% 
    filter(cancer_type == t & death_type == t) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumorous_all %>% 
    filter(cancer_type == t & death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(max_d_date - diag_date))
  tempdfU = bind_rows(tumorous_d, tumorous_alive)
  tempdfU$event = as.numeric(ifelse(tempdfU$death == T, 1, 0))
  tempdfU %<>% dplyr::select(eid, time, event, sex, synonym_burden, age_at_cancer, all_of(gpca))
  myformula = as.formula(paste('Surv(time, event) ~ ', paste0(colnames(tempdfU)[4:ncol(tempdfU)], collapse = "+")))
  res.surv = coxph(myformula, data = tempdfU)
  coxPvalues = summary(res.surv)$coefficients[,"Pr(>|z|)"]
  coxCoefs = summary(res.surv)$coefficients[,"coef"]
  names(coxPvalues)[grep("synonym_burden", names(coxPvalues))] = "synonym"
  names(coxCoefs)[grep("synonym_burden", names(coxCoefs))] = "synonym"
  coxPvalues = coxPvalues[fmatch(c("sexmale", "synonym", "age_at_cancer", paste0("gpca", 1:10)), names(coxPvalues))]
  coxCoefs = coxCoefs[fmatch(c("sexmale", "synonym", "age_at_cancer", paste0("gpca", 1:10)), names(coxPvalues))]
  names(coxPvalues) = paste0("p_", names(coxPvalues))
  names(coxCoefs) = paste0("coef_", names(coxCoefs))
  c(coxPvalues, coxCoefs)
})
out = cbind(tumor_freq_data, t(tumors_survres))
#colnames(out)[seq(5,ncol(out),2)] = c("coef_PTVvar", "coef_sexmale", paste0("coef_gpca", 1:10))
#colnames(out)[seq(6,ncol(out),2)] = c("p_PTVvar", "p_sexmale", paste0("p_gpca", 1:10))
syn_cox_ds = out

save(syn_cox_ds, file = "objects/res_syn_cox_d")

```

###Heatmap
```{r}

load("objects/res_syn_cox_d")
synonym = "synonym"

dataForHm = matrix(data = NA, nrow = 1, ncol = length(tumors), dimnames = list(synonym, tumors))
for(j in 1:ncol(dataForHm)) {
  dataForHm[j] = ifelse(syn_cox_ds$p_synonym[syn_cox_ds$cancer_type == colnames(dataForHm)[j]] < 0.05, syn_cox_ds$coef_synonym[syn_cox_ds$cancer_type == colnames(dataForHm)[j]], NA)
}


#P-values
dataForHmP =  matrix(data = NA, nrow = 1, ncol = length(tumors), dimnames = list(synonym, tumors))
for(j in 1:ncol(dataForHmP)) {
  dataForHmP[j] = ifelse(syn_cox_ds$p_synonym[syn_cox_ds$cancer_type == colnames(dataForHmP)[j]] < 0.05, round(syn_cox_ds$p_synonym[syn_cox_ds$cancer_type == colnames(dataForHmP)[j]], digits = 4), NA)
}

hm = ComplexHeatmap::Heatmap(matrix = dataForHm, 
             name = "Coefficient", 
             na_col = "gray",
             col = colorRamp2(c(-2, 0, 2), c("green", "white", "red")),
             cluster_columns = F, 
             cluster_rows = F, 
             rect_gp = gpar(col = "black", lwd = 1), 
             cell_fun = function(j, i, x, y, width, height, fill) {
               if(!is.na(dataForHmP[i, j]))
                 grid.text(sprintf("%.3f", dataForHmP[i, j]), x, y, gp = gpar(fontsize = 8))
             })

```


###Forestplot
```{r}

out_dir = "plots/Survival/102_forest/"
pdf_width = 6 
pdf_height = 10
max_d_date = max(ukb_data$date_of_death, na.rm = T)

pdf_filename = paste0(out_dir, "forest_surv_syn_ds", ".pdf")
pdf(pdf_filename, onefile = T, width = pdf_width, height = pdf_height)
tumors_survres = pblapply(tumor_freq_data$cancer_type, function(t) {
  tumorous_d = tumorous_all %>% 
    filter(cancer_type == t & death_type == t) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(date_of_death - diag_date))
  tumorous_alive = tumorous_all %>% 
    filter(cancer_type == t & death == F) %>% 
    arrange(diag_date) %>% 
    distinct(eid, .keep_all = T) %>% 
    mutate(time = as.numeric(max_d_date - diag_date))
  tempdfU = bind_rows(tumorous_d, tumorous_alive)
  tempdfU$status = as.numeric(ifelse(tempdfU$death == T, 1, 0))
  tempdfU %<>% dplyr::select(eid, time, status, sex, synonym_burden, age_at_cancer, all_of(gpca))
  #colnames(tempdfU)[5] = "PTVvar"
  gender_counts = table(tempdfU$sex)
  #if (any(gender_counts < 20)) {
  #tempdfU <- tempdfU[tempdfU$sex %in% names(gender_counts)[gender_counts >= 20], ]
  #print("Excluding gender categories with fewer than 20 individuals.")}
  if (length(table(tempdfU$synonym_burden[tempdfU$status == 1])) > 1 & length(unique(tempdfU$sex)) == 2 & all(gender_counts >= 20)) {
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[4:ncol(tempdfU)], collapse = "+")))
    hr_model = survival::coxph(myformula, data = as.data.frame(tempdfU))
  } else if (length(table(tempdfU$synonym_burden[tempdfU$status == 1])) == 1 & length(unique(tempdfU$sex)) == 1) { 
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[6:ncol(tempdfU)], collapse = "+")))
    hr_model = survival::coxph(myformula, data = as.data.frame(tempdfU))
  } else if (length(table(tempdfU$synonym_burden[tempdfU$status == 1])) > 1 & all(table(tempdfU$sex) >= 20)) {
    myformula = as.formula(paste('Surv(time, status) ~ ', paste0(colnames(tempdfU)[5:ncol(tempdfU)], collapse = "+")))
    hr_model =survival::coxph(myformula, data = as.data.frame(tempdfU))
  } else {
    hr_model = survival::coxph(Surv(time, status) ~ sex + age_at_cancer + gpca1 + gpca2 + gpca3 + gpca4 + gpca5 + gpca6 + gpca7 + gpca8 + gpca9 + gpca10, data = as.data.frame(tempdfU))
  }
  panels = list(list(width = 0.1, display = ~variable, fontface = "bold", heading = "synonym"), list(width = 0.1, display = ~level), list(width = 0.05, display = ~n, hjust = 1, heading = "N"), list(width = 0.03, item = "vline", hjust = 0.5), list(width = 0.03, item = "vline", hjust = 0.5), list(item = "forest", heading = t, linetype = "dashed", line_x = 0), list(width = 0.03), list(width = 0.12, display = ~ ifelse(reference, "Reference", sprintf("%0.2f (%0.2f - %0.2f)",trans(estimate), trans(conf.low), trans(conf.high))), display_na = NA, heading="95% CI (Range)"), list(width = 0.05,display = ~ ifelse(reference, "", format.pval(p.value, digits = 1, eps = 0.001)), display_na = NA, hjust = 1, heading = "p"), list(width = 0.03))
  forest = forestmodel::forest_model(hr_model, format_options = forest_model_format_options(text_size = 3), panels = panels, exclude_infinite_cis = T, limits = c(-2,2))
  print(forest)
})
dev.off()

```


