---
title: "Survival_analysis_cancer"
author: "Bagi Laura"
date: "2024-03-18"
output: html_document
---

#Libraries
```{r}
library(ggpubr)
library(fastmatch)
library(readxl)
library(forcats)
library(survival)
library(survminer)
library(grid)
library(gridExtra)
library(data.table)
library(caret)
library(tidyverse)
library(future.apply)
library(magrittr)
library(cowplot)
options(dplyr.summarise.inform = F)

```

#Files
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")
load("C:/Users/bagil/Desktop/ukb/objects/icd_mapping")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")

```


#Survival analysis for PTV burden group 1
```{r}
cancer_surv_PTV1 = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  temp_can = subset(cancer_data, cancer_type == x)
  temp_can = temp_can[!duplicated(temp_can$eid), ]
  temp_can %<>% 
  mutate(time_in_days = case_when(
      death == T ~ date_of_death - diag_date,
      death == F ~ max(date_of_death, na.rm = T) - diag_date
    ))
  temp_can$cancer_type[is.na(temp_can$cancer_type)] = "No cancer"
  temp_can$event_indicator = ifelse(temp_can$death == T, 1, 0)
  temp_can$PTV_burden_group = factor(temp_can$PTV_burden_group, ordered = T)
  fit = do.call(survfit, list(formula = Surv(time_in_days, event = event_indicator) ~ PTV_burden_group,data = temp_can))
  args = list(fit = fit, title = paste0("Survival Analysis for ", x, "\n(N=", nrow(temp_can), ")"), pval = T, legend = "none")
  pfit = do.call(ggsurvplot, args)
  tblA = ggsurvplot(survfit(Surv(time_in_days, event = event_indicator) ~ PTV_burden_group, data = temp_can), risk.table = T, tables.theme = clean_theme())$table
  grid.arrange(pfit$plot, tblA, layout_matrix = rbind(c(1, 1), c(1,1), c(2, 2)))
})


ggarrange(plotlist =  cancer_surv_PTV1, ncol = 5, nrow = 5)
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Survival/PTV_burden_g1_surv_cancer.png", width = 100, height = 50, units = "cm", dpi = 300)


```

#Survival analysis for PTV burden group 2
```{r}

cancer_surv_PTV2 = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  temp_can = subset(cancer_data, cancer_type == x)
  temp_can = temp_can[!duplicated(temp_can$eid), ]
  temp_can %<>% 
  mutate(time_in_days = case_when(
      death == T ~ date_of_death - diag_date,
      death == F ~ max(date_of_death, na.rm = T) - diag_date
    ))
  temp_can$cancer_type[is.na(temp_can$cancer_type)] = "No cancer"
  temp_can$event_indicator = ifelse(temp_can$death == T, 1, 0)
  temp_can$PTV_burden_group_2 = factor(temp_can$PTV_burden_group_2, ordered = T)
  fit = do.call(survfit, list(formula = Surv(time_in_days, event = event_indicator) ~ PTV_burden_group_2, data = temp_can))
  args = list(fit = fit, title = paste0("Survival Analysis for ", x, "\n(N=", nrow(temp_can), ")"), pval = T, legend = "none")
  pfit = do.call(ggsurvplot, args)
  tblA = ggsurvplot(survfit(Surv(time_in_days, event = event_indicator) ~ PTV_burden_group_2, data = temp_can), risk.table = T, tables.theme = clean_theme())$table
  grid.arrange(pfit$plot, tblA, layout_matrix = rbind(c(1, 1), c(1,1), c(2, 2)))
})

ggarrange(plotlist =  cancer_surv_PTV2, ncol = 5, nrow = 5)
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Survival/PTV_burden_g2_surv_cancer.png", width = 100, height = 50, units = "cm", dpi = 300)

```

#Survival analysis for PTV burden group 3
```{r}

cancer_surv_PTV3 = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  temp_can = subset(cancer_data, cancer_type == x)
  temp_can = temp_can[!duplicated(temp_can$eid), ]
  temp_can %<>% 
  mutate(time_in_days = case_when(
      death == T ~ date_of_death - diag_date,
      death == F ~ max(date_of_death, na.rm = T) - diag_date
    ))
  temp_can$cancer_type[is.na(temp_can$cancer_type)] = "No cancer"
  temp_can$event_indicator = ifelse(temp_can$death == T, 1, 0)
  temp_can$PTV_burden_group_3 = factor(temp_can$PTV_burden_group_3, ordered = T)
  fit = do.call(survfit, list(formula = Surv(time_in_days, event = event_indicator) ~ PTV_burden_group_3, data = temp_can))
  args = list(fit = fit, title = paste0("Survival Analysis for ", x, "\n(N=", nrow(temp_can), ")"), pval = T, legend = "none")
  pfit = do.call(ggsurvplot, args)
  tblA = ggsurvplot(survfit(Surv(time_in_days, event = event_indicator) ~ PTV_burden_group_3, data = temp_can), risk.table = T, tables.theme = clean_theme())$table
  grid.arrange(pfit$plot, tblA, layout_matrix = rbind(c(1, 1), c(1,1), c(2, 2)))
})

ggarrange(plotlist =  cancer_surv_PTV3, ncol = 5, nrow = 5)
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Survival/PTV_burden_g3_surv_cancer.png", width = 100, height = 50, units = "cm", dpi = 300)


```

#Survival analysis for PTV burden group 4
```{r}

cancer_surv_PTV4 = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  temp_can = subset(cancer_data, cancer_type == x)
  temp_can = temp_can[!duplicated(temp_can$eid), ]
  temp_can %<>% 
  mutate(time_in_days = case_when(
      death == T ~ date_of_death - diag_date,
      death == F ~ max(date_of_death, na.rm = T) - diag_date
    ))
  temp_can$cancer_type[is.na(temp_can$cancer_type)] = "No cancer"
  temp_can$event_indicator = ifelse(temp_can$death == T, 1, 0)
  temp_can$PTV_burden_group_4 = cut(temp_can$PTV_burden, breaks = quantile(temp_can$PTV_burden, c(0, 0.05, 0.95, 1)), labels = c("Low", "Medium","High"), include.lowest = T, right = T)
  fit = do.call(survfit, list(formula = Surv(time_in_days, event = event_indicator) ~ PTV_burden_group_4, data = temp_can))
  args = list(fit = fit, title = paste0("Survival Analysis for ", x, "\n(N=", nrow(temp_can), ")"), pval = T, legend = "none")
  pfit = do.call(ggsurvplot, args)
  tblA = ggsurvplot(survfit(Surv(time_in_days, event = event_indicator) ~ PTV_burden_group_4, data = temp_can), risk.table = T, tables.theme = clean_theme())$table
  grid.arrange(pfit$plot, tblA, layout_matrix = rbind(c(1, 1), c(1,1), c(2, 2)))
})
ggarrange(plotlist =  cancer_surv_PTV4, ncol = 5, nrow = 5)

ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Survival/PTV_burden_g4_surv_cancer.jpg", width = 100, height = 50, units = "cm", dpi = 300)

#temp_can$PTV_burden_group_4 = cut(temp_can$PTV_burden, breaks = quantile(temp_can$PTV_burden, c(0, 0.01, 0.99, 1)), labels = c("Low", "Medium","High"), include.lowest = T, right = T)

```

#All tumor survival analysis
```{r}
temp_df_1 = data.frame(eid = cancer_data$eid,
                       birthdate = cancer_data$birthdate,
                       date_of_death = cancer_data$date_of_death,
                       diag_date = cancer_data$diag_date,
                       death = cancer_data$death,
                       cancer_type = cancer_data$cancer_type,
                       PTV_burden_group = cancer_data$PTV_burden_group,
                       PTV_burden_group_2 = cancer_data$PTV_burden_group_2,
                       PTV_burden_group_3 = cancer_data$PTV_burden_group_3)

temp_df_1 %<>%
  group_by(eid) %>%
  summarize(
    birthdate = first(birthdate),
    date_of_death = first(date_of_death),
    diag_date = first(diag_date),
    death = first(death),
    PTV_burden_group = first(PTV_burden_group),
    PTV_burden_group_2 = first(PTV_burden_group_2),
    PTV_burden_group_3 = first(PTV_burden_group_3))

temp_df_1 %<>% 
  mutate(time_in_days = case_when(
      death == T ~ date_of_death - diag_date,
      death == F ~ max(date_of_death, na.rm = T) - diag_date
    ))
temp_df_1$event_indicator = ifelse(temp_df_1$death == T, 1, 0)

fit_4 = survfit(Surv(time_in_days, event = event_indicator) ~ PTV_burden_group, data = temp_df_1)
PTV_g1_cancer_surv_death = ggsurvplot(fit_4, risk.table = T, pval = T, tables.theme = clean_theme(), title = paste0("Survival Analysis for Tumors (PTV burden group 1)"))
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Survival/PTV_g1_tumor_surv.png", plot = PTV_g1_cancer_surv_death$plot, width = 60, height = 30, units = "cm", dpi = 300)


fit_5 = survfit(Surv(time_in_days, event = event_indicator) ~ PTV_burden_group_2, data = temp_df_1)
PTV_g2_cancer_surv_death = ggsurvplot(fit_5, risk.table = T, pval = T, tables.theme = clean_theme(), title = paste0("Survival Analysis for Tumors (PTV burden group 2)"))
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Survival/PTV_g2_tumor_surv.png", plot = PTV_g2_cancer_surv_death$plot, width = 60, height = 30, units = "cm", dpi = 300)

fit_6 = survfit(Surv(time_in_days, event = event_indicator) ~ PTV_burden_group_3, data = temp_df_1)
PTV_g3_cancer_surv_death = ggsurvplot(fit_6, risk.table = T, pval = T, tables.theme = clean_theme(), title = paste0("Survival Analysis for Tumors (PTV burden group 3)"))
ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Survival/PTV_g3_tumor_surv.png", plot = PTV_g3_cancer_surv_death$plot, width = 60, height = 30, units = "cm", dpi = 300)



PTV_plot_list_surv = list(PTV_g1_cancer_surv_death$plot, PTV_g2_cancer_surv_death$plot, PTV_g3_cancer_surv_death$plot)
PTV_risk_list_surv = list(PTV_g1_cancer_surv_death$table, PTV_g2_cancer_surv_death$table, PTV_g3_cancer_surv_death$table)
PTV_plot_list_combined = c(PTV_plot_list_surv, PTV_risk_list_surv)

grid.arrange(grobs = PTV_plot_list_combined, ncol = 3)
plot_grid(plotlist = PTV_plot_list_combined, ncol = 3)

ggsave(filename ="C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/Survival/PTV_cancer_all_surv.png", width = 100, height = 50, units = "cm", dpi = 300 )


```


```{r}


```


```{r}


```

