---
title: "ukb_table_creator"
author: "Bagi Laura"
date: "2024-01-16"
output: html_document
---

#Libaries
```{r}
library(ggpubr)
library(fastmatch)
library(readxl)
library(forcats)
library(survival)
library(survminer)
library(grid)
library(gridExtra)
library(data.table)
library(caret)
library(tidyverse)
library(future.apply)
library(magrittr)
library(xml2)
library(purrr)
library(archive)
library(utils)
options(dplyr.summarise.inform = F)

```

#ukb datas part 1
```{r}
#birthdate
year_of_birth = read.table("C:/Users/bagil/Desktop/ukb/34.txt", header = T) #34
month_of_birth= read.table("C:/Users/bagil/Desktop/ukb/52.txt", header = T) #52
ukb_data=data.frame(eid= year_of_birth$eid)
df_births = data.frame(eid=year_of_birth$eid, year=year_of_birth$value, 
                       month= month_of_birth$value[match(month_of_birth$eid, year_of_birth$eid)], 
                       day= 15)
df_births$birthdate = paste(df_births$year,
                  df_births$month,
                  df_births$day,
                  sep = "-")
df_births$birthdate=as.Date(df_births$birthdate)
df_births$birthdate = format(df_births$birthdate, "%Y-%m-%d")
ukb_data$birthdate= df_births$birthdate[match(df_births$eid, ukb_data$eid)]
rm(year_of_birth, month_of_birth, df_births)
#sex
sex = read.table("C:/Users/bagil/Desktop/ukb/31_0_0.txt", header = T) #31
ukb_data$sex = sex$value[match(sex$eid, ukb_data$eid)]
rm(sex)
#ethnic
ethnic = read.table("C:/Users/bagil/Desktop/ukb/21000.txt", header = T) #21000
dataframe_ethnic = pivot_wider(data = ethnic, id_cols = eid, names_from = UKB_column_name, values_from = value)
colnames(dataframe_ethnic)=c("eid", "ethnic_1", "ethnic_2", "ethnic_3", "ethnic_4")
ukb_data = cbind(ukb_data, dataframe_ethnic[match(ukb_data$eid, dataframe_ethnic$eid), c("ethnic_1", "ethnic_2", "ethnic_3", "ethnic_4")])
ethnic_df = data.frame(ethnic = c("British", "Irish", "Any other white group", "White and Black Caribbean", "White and Black African", "White and Asian", "Any other mixed background", "Indian","Pakistani","Bangladeshi", "Any other Asian background", "Caribbean", "African", "Any other Black background", "Chinese", "Other ethnic group", "Do not know", "Prefer not to answer"),
                       ethnic_code = c(1001, 1002, 1003, 2001, 2002, 2003, 2004, 3001, 3002, 3003, 3004, 4001, 4002, 4003, 5, 6,(-1), (-3)))
ethnic_df2 = data.frame(ethnic = c("White", "Mixed", "Asian or Asian British", "Black or Black British", "Chinese", "Other ethnic group", "Do not know", "Prefer not to answer"),
                        ethnic_code = c(1, 2, 3, 4, 5, 6, (-1), (-3)))
ukb_data$ethnic_group = ethnic_df$ethnic[match(ukb_data$ethnic_1, ethnic_df$ethnic_code)]
rm(ethnic, dataframe_ethnic, ethnic_df, ethnic_df2)

#Skin
skin_colour = read.table("C:/Users/bagil/Desktop/ukb/1717.txt", header = T)
skin_mapping = data.frame(color = c("Very fair", "Fair", "Light olive", "Dark olive", "Brown", "Black", "Do not know", "Prefer not to answer"),
                          value = c(1,2,3,4,5,6, (-1), (-2)))
skin_colour$skin = skin_mapping$color[match(skin_colour$value, skin_mapping$value)]
ukb_data$skin = skin_colour$skin[match(ukb_data$eid, skin_colour$eid)]
rm(skin_colour, skin_mapping)
#Attendings
date_of_attendings = read.table("C:/Users/bagil/Desktop/ukb/53.txt", header = T) #53
attendings = pivot_wider(date_of_attendings, id_cols = eid, names_from = UKB_column_name, values_from = value)
colnames(attendings)=c("eid", "attending_1", "attending_3", "attending_4", "attending_2")
ukb_data = cbind(ukb_data, attendings[match(ukb_data$eid, attendings$eid), c("attending_1", "attending_2", "attending_3", "attending_4")])
rm(date_of_attendings, attendings)

#paste("attending", 1:10, sep = "_")
#paste0("attending", 1:10)
#paste("attending", 1:10, sep = "_", collapse = ",")

#Date of death
date_of_death= read.table("C:/Users/bagil/Desktop/ukb/40000.txt", header = T) #40000
ukb_data$date_of_death = date_of_death$value[match(ukb_data$eid, date_of_death$eid, nomatch = NA)]
ukb_data$death= !is.na(ukb_data$date_of_death)
rm(date_of_death)

```


#ukb datas part 2
```{r}
#Primary case of death
p_cause_of_death = read.table("C:/Users/bagil/Desktop/ukb/40001.txt", header = T)#40001
p_cause_of_death = p_cause_of_death[, c(1,3)]
p_cause_of_death = unique(p_cause_of_death)
View(p_cause_of_death[p_cause_of_death$eid %in% p_cause_of_death$eid[duplicated(p_cause_of_death$eid)],])
p_cause_of_death$value[p_cause_of_death$eid == 1043064] = "C459"
p_cause_of_death$value[p_cause_of_death$eid == 1065596] = "X45" #Accidental poisoning by and exposure to alcohol, I251: Atherosclerotic heart disease
p_cause_of_death$value[p_cause_of_death$eid == 1393895] = "V134" #Vs: accidednts
p_cause_of_death$value[p_cause_of_death$eid == 1439801] = "C459"
p_cause_of_death$value[p_cause_of_death$eid == 1623783] = "X80" #X80: intetntional self-harm, Y30: undetermined intent, jumping off
p_cause_of_death$value[p_cause_of_death$eid == 1790406] = "C450"
p_cause_of_death$value[p_cause_of_death$eid == 1804027] = "X62"
p_cause_of_death$value[p_cause_of_death$eid == 1821938] = "C450"
p_cause_of_death$value[p_cause_of_death$eid == 2115545] = "I259"
p_cause_of_death$value[p_cause_of_death$eid == 2253164] = "C349"
p_cause_of_death$value[p_cause_of_death$eid == 2573640] = "N832"
p_cause_of_death$value[p_cause_of_death$eid == 2650792] = "W19" #Unspecified fall
p_cause_of_death$value[p_cause_of_death$eid == 2654992] = "C450"
p_cause_of_death$value[p_cause_of_death$eid == 2960538] = "E101"
p_cause_of_death$value[p_cause_of_death$eid == 3395887] = "C459"
p_cause_of_death$value[p_cause_of_death$eid == 3399475] = "I251"
p_cause_of_death$value[p_cause_of_death$eid == 3542163] = "I694" #A419:sepsis,unspecified, I694: Sequelae of intracerebral haemorrhage
p_cause_of_death$value[p_cause_of_death$eid == 3755904] = "C457"
p_cause_of_death$value[p_cause_of_death$eid == 3766505] = "C711"
p_cause_of_death$value[p_cause_of_death$eid == 3804095] = "I259"
p_cause_of_death$value[p_cause_of_death$eid == 4139546] = "I312"
p_cause_of_death$value[p_cause_of_death$eid == 4238947] = "W15"
p_cause_of_death$value[p_cause_of_death$eid == 4278166] = "I313"
p_cause_of_death$value[p_cause_of_death$eid == 4280796] = "E101"
p_cause_of_death$value[p_cause_of_death$eid == 4369584] = "X42"
p_cause_of_death$value[p_cause_of_death$eid == 4471349] = "K992" #K992: Gastrointestinal haemorrhage, unspecified, K221: Ulcer of oesophagus
p_cause_of_death$value[p_cause_of_death$eid == 4486627] = "X67"
p_cause_of_death$value[p_cause_of_death$eid == 4521671] = "K265"
p_cause_of_death$value[p_cause_of_death$eid == 4750507] = "Q612"
p_cause_of_death$value[p_cause_of_death$eid == 4872527] = "C61"
p_cause_of_death$value[p_cause_of_death$eid == 4921756] = "X80"
p_cause_of_death$value[p_cause_of_death$eid == 5115953] = "Y830"
p_cause_of_death$value[p_cause_of_death$eid == 5265396] = "I269"
p_cause_of_death$value[p_cause_of_death$eid == 5537565] = "V031"
p_cause_of_death$value[p_cause_of_death$eid == 5565123] = "X64"
p_cause_of_death$value[p_cause_of_death$eid == 5668463] = "C260"
p_cause_of_death$value[p_cause_of_death$eid == 5749941] = "I359"
p_cause_of_death$value[p_cause_of_death$eid == 5802912] = "J449"
p_cause_of_death$value[p_cause_of_death$eid == 5962197] = "F102"
p_cause_of_death$value[p_cause_of_death$eid == 5997743] = "K318"
p_cause_of_death$value[p_cause_of_death$eid == 6009165] = "I639"

p_cause_of_death = unique(p_cause_of_death)
ukb_data$cause_of_death = p_cause_of_death$value[match(ukb_data$eid, p_cause_of_death$eid, nomatch = NA)]
rm(p_cause_of_death)

#reported occurences
reported_occurences = read.table("C:/Users/bagil/Desktop/ukb/40009.txt", header = T) #40009
ukb_data$c.occurences= reported_occurences$value[match(ukb_data$eid, reported_occurences$eid, nomatch = NA)]
rm(reported_occurences)

ukb_data$birthdate = as.Date(ukb_data$birthdate)
ukb_data$attending_1 = as.Date(ukb_data$attending_1)
ukb_data$date_of_death = as.Date(ukb_data$date_of_death)

#Age
ukb_data$age = ifelse(ukb_data$death == T, ukb_data$date_of_death - ukb_data$birthdate, Sys.Date() - ukb_data$birthdate)
ukb_data$age = floor(as.numeric(ukb_data$age)/365.25)

#usless columns
ukb_data$ethnic_2 = NULL
ukb_data$ethnic_3 = NULL
ukb_data$ethnic_4 = NULL

save(ukb_data, file = "C:/Users/bagil/Desktop/ukb/objects/ukb_data_1")

load("C:/Users/bagil/Desktop/ukb/objects/ukb_data_1")
```


#cancer datas
```{r}

histology_of_cancer = read.table("C:/Users/bagil/Desktop/ukb/40011.txt", header = T) #40011
type_of_cancer = read.table("C:/Users/bagil/Desktop/ukb/40006.txt", header = T) #40006
date_of_cancer_diag = read.table("C:/Users/bagil/Desktop/ukb/40005.txt", header = T) #40005


plan(multisession)
cancer_data = future_lapply(X = unique(histology_of_cancer$eid),FUN=function(x){
   temp_df=histology_of_cancer[histology_of_cancer$eid==x,]
   temp_df$cnid= substr(x = temp_df$UKB_column_name, start = 7, stop = 10)
   tempdf_2=type_of_cancer[type_of_cancer$eid==x,]
   tempdf_2$cnid= substr(x = tempdf_2$UKB_column_name, start = 7, stop = 10)
   tempdf_3=date_of_cancer_diag[date_of_cancer_diag$eid==x,]
   tempdf_3$cnid=substr(x = tempdf_3$UKB_column_name, start = 7, stop = 10)
   cancer_codes_df=left_join(x = temp_df, y = tempdf_2,  by = "cnid")
   cancer_codes_df= left_join(x = cancer_codes_df, y = tempdf_3, by="cnid")
   cancer_codes_df=cancer_codes_df[,c(1,10,7,3)]
   colnames(cancer_codes_df)= c("eid", "date","ICD10", "histology")
   cancer_codes_df
}, future.seed = 4)
rm(date_of_cancer_diag, histology_of_cancer, type_of_cancer)
cancer_data = do.call(rbind, cancer_data)
cancer_data = unite(cancer_data,col = "ICD_hist", c("ICD10", "histology") ,sep = "_", remove = F )
cancer_data$birthdate = ukb_data$birthdate[match(cancer_data$eid, ukb_data$eid)]
cancer_data$age_at_cancer = apply(X = cancer_data, MARGIN = 1, FUN = function(x){
  as.Date(as.character(x[2]))-as.Date(as.character(x[6]))
})

#Only cancer datas
#sex
sex = read.table("C:/Users/bagil/Desktop/ukb/31_0_0.txt", header = T) #31
cancer_data$sex = sex$value[match(cancer_data$eid, sex$eid)]
rm(sex)
#ethnic
ethnic = read.table("C:/Users/bagil/Desktop/ukb/21000.txt", header = T) #21000
dataframe_ethnic = pivot_wider(data = ethnic, id_cols = eid, names_from = UKB_column_name, values_from = value)
colnames(dataframe_ethnic)=c("eid", "ethnic_1", "ethnic_2", "ethnic_3", "ethnic_4")
cancer_data = cbind(cancer_data, dataframe_ethnic[match(cancer_data$eid, dataframe_ethnic$eid), "ethnic_1"])
ethnic_df = data.frame(ethnic = c("British", "Irish", "Any other white group", "White and Black Caribbean", "White and Black African", "White and Asian", "Any other mixed background", "Indian","Pakistani","Bangladeshi", "Any other Asian background", "Caribbean", "African", "Any other Black background", "Chinese", "Other ethnic group", "Do not know", "Prefer not to answer"),
                       ethnic_code = c(1001, 1002, 1003, 2001, 2002, 2003, 2004, 3001, 3002, 3003, 3004, 4001, 4002, 4003, 5, 6,(-1), (-3)))
ethnic_df2 = data.frame(ethnic = c("White", "Mixed", "Asian or Asian British", "Black or Black British", "Chinese", "Other ethnic group", "Do not know", "Prefer not to answer"),
                        ethnic_code = c(1, 2, 3, 4, 5, 6, (-1), (-3)))
cancer_data$ethnic_group = ethnic_df$ethnic[match(cancer_data$ethnic_1, ethnic_df$ethnic_code)]
rm(ethnic, dataframe_ethnic, ethnic_df, ethnic_df2)

#skin
skin_colour = read.table("C:/Users/bagil/Desktop/ukb/1717.txt", header = T)
skin_mapping = data.frame(color = c("Very fair", "Fair", "Light olive", "Dark olive", "Brown", "Black", "Do not know", "Prefer not to answer"),
                          value = c(1,2,3,4,5,6, (-1), (-2)))
skin_colour$skin = skin_mapping$color[match(skin_colour$value, skin_mapping$value)]
cancer_data$skin = skin_colour$skin[match(cancer_data$eid, skin_colour$eid)]
rm(skin_colour, skin_mapping)
#attendings
date_of_attendings = read.table("C:/Users/bagil/Desktop/ukb/53.txt", header = T) #53
attendings = pivot_wider(date_of_attendings, id_cols = eid, names_from = UKB_column_name, values_from = value)
colnames(attendings)=c("eid", "attending_1", "attending_3", "attending_4", "attending_2")
cancer_data= cbind(cancer_data, attendings[match(cancer_data$eid, attendings$eid), c("attending_1", "attending_2", "attending_3", "attending_4")])
rm(date_of_attendings, attendings)

#date of death
date_of_death= read.table("C:/Users/bagil/Desktop/ukb/40000.txt", header = T) #40000
cancer_data$date_of_death=date_of_death$value[match(cancer_data$eid, date_of_death$eid)]
cancer_data$death= !is.na(cancer_data$date_of_death)
rm(date_of_death)

#cause of death
p_cause_of_death = read.table("C:/Users/bagil/Desktop/ukb/40001.txt", header = T)#40001
p_cause_of_death = p_cause_of_death[, c(1,3)]
p_cause_of_death = unique(p_cause_of_death)
#View(p_cause_of_death[p_cause_of_death$eid %in% p_cause_of_death$eid[duplicated(p_cause_of_death$eid)],])
p_cause_of_death$value[p_cause_of_death$eid == 1043064] = "C459"
p_cause_of_death$value[p_cause_of_death$eid == 1065596] = "X45" #Accidental poisoning by and exposure to alcohol, I251: Atherosclerotic heart disease
p_cause_of_death$value[p_cause_of_death$eid == 1393895] = "V134" #Vs: accidednts
p_cause_of_death$value[p_cause_of_death$eid == 1439801] = "C459"
p_cause_of_death$value[p_cause_of_death$eid == 1623783] = "X80" #X80: intetntional self-harm, Y30: undetermined intent, jumping off
p_cause_of_death$value[p_cause_of_death$eid == 1790406] = "C450"
p_cause_of_death$value[p_cause_of_death$eid == 1804027] = "X62"
p_cause_of_death$value[p_cause_of_death$eid == 1821938] = "C450"
p_cause_of_death$value[p_cause_of_death$eid == 2115545] = "I259"
p_cause_of_death$value[p_cause_of_death$eid == 2253164] = "C349"
p_cause_of_death$value[p_cause_of_death$eid == 2573640] = "N832"
p_cause_of_death$value[p_cause_of_death$eid == 2650792] = "W19" #Unspecified fall
p_cause_of_death$value[p_cause_of_death$eid == 2654992] = "C450"
p_cause_of_death$value[p_cause_of_death$eid == 2960538] = "E101"
p_cause_of_death$value[p_cause_of_death$eid == 3395887] = "C459"
p_cause_of_death$value[p_cause_of_death$eid == 3399475] = "I251"
p_cause_of_death$value[p_cause_of_death$eid == 3542163] = "I694" #A419:sepsis,unspecified, I694: Sequelae of intracerebral haemorrhage
p_cause_of_death$value[p_cause_of_death$eid == 3755904] = "C457"
p_cause_of_death$value[p_cause_of_death$eid == 3766505] = "C711"
p_cause_of_death$value[p_cause_of_death$eid == 3804095] = "I259"
p_cause_of_death$value[p_cause_of_death$eid == 4139546] = "I312"
p_cause_of_death$value[p_cause_of_death$eid == 4238947] = "W15"
p_cause_of_death$value[p_cause_of_death$eid == 4278166] = "I313"
p_cause_of_death$value[p_cause_of_death$eid == 4280796] = "E101"
p_cause_of_death$value[p_cause_of_death$eid == 4369584] = "X42"
p_cause_of_death$value[p_cause_of_death$eid == 4471349] = "K992" #K992: Gastrointestinal haemorrhage, unspecified, K221: Ulcer of oesophagus
p_cause_of_death$value[p_cause_of_death$eid == 4486627] = "X67"
p_cause_of_death$value[p_cause_of_death$eid == 4521671] = "K265"
p_cause_of_death$value[p_cause_of_death$eid == 4750507] = "Q612"
p_cause_of_death$value[p_cause_of_death$eid == 4872527] = "C61"
p_cause_of_death$value[p_cause_of_death$eid == 4921756] = "X80"
p_cause_of_death$value[p_cause_of_death$eid == 5115953] = "Y830"
p_cause_of_death$value[p_cause_of_death$eid == 5265396] = "I269"
p_cause_of_death$value[p_cause_of_death$eid == 5537565] = "V031"
p_cause_of_death$value[p_cause_of_death$eid == 5565123] = "X64"
p_cause_of_death$value[p_cause_of_death$eid == 5668463] = "C260"
p_cause_of_death$value[p_cause_of_death$eid == 5749941] = "I359"
p_cause_of_death$value[p_cause_of_death$eid == 5802912] = "J449"
p_cause_of_death$value[p_cause_of_death$eid == 5962197] = "F102"
p_cause_of_death$value[p_cause_of_death$eid == 5997743] = "K318"
p_cause_of_death$value[p_cause_of_death$eid == 6009165] = "I639"

p_cause_of_death = unique(p_cause_of_death)
cancer_data$cause_of_death = p_cause_of_death$value[match(cancer_data$eid, p_cause_of_death$eid, nomatch = NA)]
rm(p_cause_of_death)

#reported occurences
reported_occurences = read.table("C:/Users/bagil/Desktop/ukb/40009.txt", header = T) #40009
cancer_data$r.occurences= reported_occurences$value[match(cancer_data$eid, reported_occurences$eid)]
rm(reported_occurences)

#with this the birth date will
cancer_data = cancer_data[, c(1, 6, 2:5, 7:19)]


#only cancer datas to ukb datas
#ukb_data = left_join(ukb_data, cancer_data %>% select(eid, diag_date, ICD_hist, ICD10, histology, time), by = "eid")
#ukb_data = cbind(ukb_data, cancer_data[match(cancer_data$eid, ukb_data$eid), c("diag_date", "ICD_hist", "ICD")])

#dates
cancer_data$diag_date = as.Date(cancer_data$diag_date)
cancer_data$date_of_death = as.Date(cancer_data$date_of_death)
#ukb_data$diag_date = as.Date(ukb_data$diag_date)
cancer_data$birthdate = as.Date(cancer_data$birthdate)
cancer_data$attending_1 = as.Date(cancer_data$attending_1)
cancer_data$attending_2 = as.Date(cancer_data$attending_2)
cancer_data$attending_3 = as.Date(cancer_data$attending_3)
cancer_data$attending_4 = as.Date(cancer_data$attending_4)
#age
cancer_data$age = ifelse(cancer_data$death == T, cancer_data$date_of_death - cancer_data$birthdate, max(cancer_data$date_of_death, na.rm = T) - cancer_data$birthdate)
cancer_data$age_in_years = floor(as.numeric(cancer_data$age)/365.25)


#saves

save(cancer_data, file = "C:/Users/bagil/Desktop/ukb/objects/cancer_data_1")

load("C:/Users/bagil/Desktop/ukb/objects/cancer_data_1")
```

#ICD mapping
```{r}
icd_oral=data.frame(ICD10 = paste0("C0", 1:6), cancer_type = "Oral")
icd_rectum=data.frame(ICD10= paste0("C", 19:21), cancer_type= "Rectum")
icd_kidney = data.frame(ICD10=paste0("C", 64:65), cancer_type= "Kidney")
icd_non_h_lymph = data.frame(ICD10 = paste0("C", 82:86), cancer_type = "Non-Hodgkin lymphoma")
icd_leukemia = data.frame(ICD10 = paste0("C", 91:95), cancer_type = "Leukemia")
icd_lung = data.frame(ICD10 = paste0("C", 33:34), cancer_type = "Lung")
icd_brain = data.frame(ICD10 = paste0("C", 70:72), cancer_type = "Brain/CNS")

icd_only_datas=data.frame(ICD10 =c("C32", "C15", "C16","C18","C22", "C25", "C61", "C62", "C67", "C50", "C53", "C54", "C56", "C81", "C45", "C43","C73", "C96", "C88", "C90" ),
                          cancer_type = c("Larynx","Esophagus", "Stomach", "Colon", "Liver", "Pancreas", "Prostate", "Testis", "Bladder","Breast",  "Cervix", "Endometrium", "Ovary", "Hodgkin lymphoma", "Mesothelioma", "Melanoma", "Thyroid", "Non-Hodgkin lymphoma", "Multiple myeloma", "Multiple myeloma"))
icd_mapping = rbind(icd_only_datas, icd_brain,icd_lung, icd_leukemia, icd_non_h_lymph, icd_kidney, icd_rectum,icd_oral)
rm(icd_brain, icd_kidney, icd_only_datas, icd_lung, icd_leukemia, icd_non_h_lymph, icd_rectum, icd_oral)
save(file = "C:/Users/bagil/Desktop/ukb/objects/icd_mapping", icd_mapping)


```


#UKB data + cancer data
```{r}
load("C:/Users/bagil/Desktop/ukb/objects/cancer_data_1")
load("C:/Users/bagil/Desktop/ukb/objects/ukb_data_1")

cancer_data_f = cancer_data[,c("eid", "diag_date", "ICD_hist", "ICD10", "histology", "age_at_cancer")]

ukb_data_cancer = left_join(ukb_data, cancer_data_f, by = "eid")

load("C:/Users/bagil/Desktop/ukb/objects/icd_mapping")
#cutting the ICD10 codes

ukb_data_cancer$ICD10_codes = substr(ukb_data_cancer$ICD10, 1, 3)
cancer_data$ICD10_codes = substr(cancer_data$ICD10, 1, 3)

#matching
ukb_data_cancer$cancer_type = icd_mapping$cancer_type[match(ukb_data_cancer$ICD10_codes, icd_mapping$ICD10)]
cancer_data$cancer_type = icd_mapping$cancer_type[match(cancer_data$ICD10_codes, icd_mapping$ICD10)]
ukb_data_cancer$cancer_type[is.na(ukb_data_cancer$cancer_type)] = "No_cancer"
rm(cancer_data_f)


save(ukb_data_cancer, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")
save(cancer_data, file = "C:/Users/bagil/Desktop/ukb/objects/cancer_data_final")
```


#Genetic_PCAs
```{r}
#Clean gpca
genetic_pca = fread("C:/Users/bagil/Desktop/ukb/ukb_genetic_pca_40.tsv")
genetic_pca_clean = genetic_pca[,1:3]
genetic_pca_clean = pivot_wider(data = genetic_pca_clean, id_cols = eid, names_from = UKB_column_name, values_from = value)
save(genetic_pca_clean, file = "C:/Users/bagil/Desktop/ukb/objects/genetic_pca_clean")
load("C:/Users/bagil/Desktop/ukb/objects/genetic_pca_clean")

#Match
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")

colnames(genetic_pca_clean)[2:42] = paste0("gpca", 1:40)
cancer_data %<>%
  left_join(genetic_pca_clean, by = "eid")


```

#Add PTVs
```{r}
genetic_PTV = fread("C:/Users/bagil/Desktop/ukb/rawdata/specific_ultra_rare_variants_MAF_all_retained_variants_PTVBurden_final_Shetscores.7z")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final") 


file_path <- "C:/Users/bagil/Desktop/ukb/rawdata/specific_ultra_rare_variants_MAF_all_retained_variants_PTVBurden_final_Shetscores.7z"

custom_dir <- "C:/Users/bagil/Desktop/extracted_files"
if (!dir.exists(custom_dir)) {
  dir.create(custom_dir)
}


cmd <- paste0('"C:/Program Files/7-Zip/7z.exe" e "', file_path, '" -o"', custom_dir, '" -y')
system(cmd)

extracted_files <- list.files(custom_dir, full.names = TRUE)
print(extracted_files)

if(length(extracted_files) > 0) {
  data <- read.csv(extracted_files[1])
  print(head(data))
}

#PTV burdens

#ukb_data_cancer$PTV_burden = cut(ukb_data_cancer$PTV_burden_of_MAF_1_percent, breaks = c(min(ukb_data_cancer$PTV_burden_of_MAF_1_percent, na.rm = T), median(ukb_data_cancer$PTV_burden_of_MAF_1_percent, na.rm = T), max(ukb_data_cancer$PTV_burden_of_MAF_1_percent, na.rm = T)), labels = c("Low", "High"), include.lowest = T, right = T)

colnames(genetic_PTV)[c(1,3)] = c("eid", "PTV_burden")
genetic_PTV = genetic_PTV[,c("eid", "PTV_burden")]

#UKB datas
ukb_data_cancer$PTV_burden = genetic_PTV$PTV_burden[fmatch(ukb_data_cancer$eid, genetic_PTV$eid)]
#3 different group
ukb_data_cancer$PTV_burden_group = cut(ukb_data_cancer$PTV_burden, breaks = quantile(ukb_data_cancer$PTV_burden, probs = c(0, 0.5, 1), na.rm = T), labels = c("Low", "High"), include.lowest = T, right = T)

ukb_data_cancer$PTV_burden_group_2 = cut(ukb_data_cancer$PTV_burden, breaks = c(min(ukb_data_cancer$PTV_burden), 8, 19, max(ukb_data_cancer$PTV_burden)), labels = c("Low", "Medium","High"), include.lowest = T, right = T, ordered_result = T)
table(ukb_data_cancer$PTV_burden_group_2)

ukb_data_cancer$PTV_burden_group_3 = cut(ukb_data_cancer$PTV_burden, breaks = c(min(ukb_data_cancer$PTV_burden), 6, 30, max(ukb_data_cancer$PTV_burden)), labels = c("Low", "Medium","High"), include.lowest = T, right = T, ordered_result = T)
table(ukb_data_cancer$PTV_burden_group_3[ukb_data_cancer$cancer_type == "Lung"])

ukb_data_cancer %<>% 
  dplyr::filter(!is.na(PTV_burden))


#Cancer datas
cancer_data$PTV_burden = genetic_PTV$PTV_burden[fmatch(cancer_data$eid, genetic_PTV$eid)]
#3 different group
cancer_data$PTV_burden_group = cut(cancer_data$PTV_burden, breaks = quantile(cancer_data$PTV_burden, probs = c(0, 0.5, 1), na.rm = T), labels = c("Low", "High"), include.lowest = T, right = T)

cancer_data$PTV_burden_group_2 = cut(cancer_data$PTV_burden, breaks = c(min(cancer_data$PTV_burden), 8, 19, max(cancer_data$PTV_burden)), labels = c("Low", "Medium","High"), include.lowest = T, right = T)
table(cancer_data$PTV_burden_group_2)

cancer_data$PTV_burden_group_3 = cut(cancer_data$PTV_burden, breaks = c(min(cancer_data$PTV_burden), 6, 30, max(cancer_data$PTV_burden)), labels = c("Low", "Medium","High"), include.lowest = T, right = T)
cancer_data$PTV_burden_group_3 = factor(cancer_data$PTV_burden_group_3, ordered = T)
table(cancer_data$PTV_burden_group_3)

cancer_data %<>% 
  dplyr::filter(!is.na(PTV_burden))

save(cancer_data, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")

```

#New PTVs
```{r}
#Files
genetic_PTV = fread("C:/Users/bagil/Desktop/ukb/rawdata/specific_ultra_rare_variants_MAF_all_retained_variants_PTVBurden_final_Shetscores.tsv")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final") 

#Colnames
colnames(genetic_PTV)[c(1,3)] = c("eid", "PTV_burden")
genetic_PTV = genetic_PTV[,c("eid", "PTV_burden")]

#UKB datas
ukb_data_cancer$PTV_burden = genetic_PTV$PTV_burden[fmatch(ukb_data_cancer$eid, genetic_PTV$eid)]
#3 different group
ukb_data_cancer$PTV_burden_group = cut(ukb_data_cancer$PTV_burden, breaks = quantile(ukb_data_cancer$PTV_burden, probs = c(0, 0.5, 1), na.rm = T), labels = c("Low", "High"), include.lowest = T, right = T)

ukb_data_cancer$PTV_burden_group_2 = cut(ukb_data_cancer$PTV_burden, breaks = c(min(ukb_data_cancer$PTV_burden, na.rm = T), 8, 19, max(ukb_data_cancer$PTV_burden, na.rm = T)), labels = c("Low", "Medium","High"), include.lowest = T, right = T, ordered_result = T)
table(ukb_data_cancer$PTV_burden_group_2)

ukb_data_cancer$PTV_burden_group_3 = cut(ukb_data_cancer$PTV_burden, breaks = c(min(ukb_data_cancer$PTV_burden, na.rm = T), 6, 30, max(ukb_data_cancer$PTV_burden, na.rm = T)), labels = c("Low", "Medium","High"), include.lowest = T, right = T, ordered_result = T)

ukb_data_cancer %<>% 
  dplyr::filter(!is.na(PTV_burden))
save(ukb_data_cancer, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")

#Cancer datas
cancer_data$PTV_burden = genetic_PTV$PTV_burden[fmatch(cancer_data$eid, genetic_PTV$eid)]
#3 different group
cancer_data$PTV_burden_group = cut(cancer_data$PTV_burden, breaks = quantile(cancer_data$PTV_burden, probs = c(0, 0.5, 1), na.rm = T), labels = c("Low", "High"), include.lowest = T, right = T)
table(cancer_data$PTV_burden_group)

cancer_data$PTV_burden_group_2 = cut(cancer_data$PTV_burden, breaks = c(min(cancer_data$PTV_burden, na.rm = T), 8, 19, max(cancer_data$PTV_burden, na.rm = T)), labels = c("Low", "Medium","High"), include.lowest = T, right = T)
table(cancer_data$PTV_burden_group_2)

cancer_data$PTV_burden_group_3 = cut(cancer_data$PTV_burden, breaks = c(min(cancer_data$PTV_burden, na.rm = T), 6, 30, max(cancer_data$PTV_burden, na.rm = T)), labels = c("Low", "Medium","High"), include.lowest = T, right = T)
cancer_data$PTV_burden_group_3 = factor(cancer_data$PTV_burden_group_3, ordered = T)
table(cancer_data$PTV_burden_group_3)

cancer_data %<>% 
  dplyr::filter(!is.na(PTV_burden))

save(cancer_data, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")

```

#PTV quantiles
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/q_cut_off")

tumors = unique(ukb_data_cancer$cancer_type)
tumors = tumors[tumors != "No_cancer"]

#General cutt off

#Uiversal
q_all = ukb_data_cancer %>% 
  select(eid, PTV_burden) %>% 
  unique() %>% 
  pull(PTV_burden) %>% 
  quantile(probs = seq(0, 1, 0.05)) 
q_all[c("10%", "20%")]

#Add to ukb
ukb_data_cancer = ukb_data_cancer %>%
  mutate(PTV_universal_1 = cut(PTV_burden, breaks = q_all[c("0%","10%", "20%", "80%", "90%", "100%")], include.lowest = T)) %>% 
  mutate(PTV_universal_2 = cut(PTV_burden, breaks = q_all[c("0%","10%", "20%", "30%", "70%", "80%", "90%", "100%")], include.lowest = T))

cancer_data = cancer_data %>%
  mutate(PTV_universal_1 = cut(PTV_burden, breaks = q_all[c("0%","10%", "20%", "80%", "90%", "100%")], include.lowest = T)) %>% 
  mutate(PTV_universal_2 = cut(PTV_burden, breaks = q_all[c("0%","10%", "20%", "30%", "70%", "80%", "90%", "100%")], include.lowest = T))

#Only cancer
q_cancer = ukb_data_cancer %>% 
  filter(cancer_type != "No_cancer") %>% 
  select(eid, PTV_burden) %>% 
  unique() %>% 
  pull(PTV_burden) %>% 
  quantile(probs = seq(0, 1, 0.05))
#Add to ukb
ukb_data_cancer = ukb_data_cancer %>%
  mutate(PTV_cancer_1 = cut(PTV_burden, breaks = q_cancer[c("0%","10%", "20%", "80%", "90%", "100%")], include.lowest = T)) %>% 
  mutate(PTV_cancer_2 = cut(PTV_burden, breaks = q_cancer[c("0%","10%", "20%", "30%", "70%", "80%", "90%", "100%")],include.lowest = T))

cancer_data = cancer_data %>% 
  mutate(PTV_cancer_1 = cut(PTV_burden, breaks = q_cancer[c("0%","10%", "20%", "80%", "90%", "100%")], include.lowest = T)) %>% 
  mutate(PTV_cancer_2 = cut(PTV_burden, breaks = q_cancer[c("0%","10%", "20%", "30%", "70%", "80%", "90%", "100%")],include.lowest = T))

#Tumor specific by cancer type
q_tumor_spec = lapply(X = tumors, FUN = function(x){
  ukb_data_cancer %>% 
    filter(cancer_type == x) %>% 
    select(eid, PTV_burden) %>% 
    unique() %>% 
    pull(PTV_burden) %>% 
    quantile(probs = seq(0, 1, 0.05))
})
names(q_tumor_spec) = tumors
q_tumor_spec[["Pancreas"]][c("5%", "95%")]
#Add to ukb

cancer_data_list = lapply(X = tumors, FUN = function(t){
  tempdf = cancer_data %>% filter(cancer_type == t)
  tempdf %>% 
    mutate(PTV_cancer_type_1 = cut(PTV_burden,
                            breaks = unique(q_tumor_spec[[t]][c("0%","20%", "80%", "100%")]),
                            include.lowest = TRUE)) %>% 
    mutate(PTV_cancer_type_2 = cut(PTV_burden,
                            breaks = unique(q_tumor_spec[[t]][c("0%","10%" ,"20%", "80%", "90%", "100%")]),
                            include.lowest = TRUE)) %>%
    mutate(PTV_cancer_type_3 = cut(PTV_burden,
                            breaks = unique(q_tumor_spec[[t]][c("0%","5%" ,"6%", "94%", "95%", "100%")]),
                            include.lowest = TRUE)) %>%
    ungroup()
})
cancer_data = bind_rows(cancer_data_list)

ukb_data_no_cancer = ukb_data_cancer %>% filter(cancer_type == "No_cancer")

ukb_data_no_cancer %<>% mutate(PTV_cancer_type_1 = NA, PTV_cancer_type_2 = NA)

columns_to_convert = c("PTV_cancer_type_1", "PTV_cancer_type_2")

ukb_data_no_cancer = ukb_data_no_cancer %>%
  mutate(across(all_of(columns_to_convert), as.factor))
 
ukb_data_cancer_list = lapply(X = tumors, FUN = function(t){
  tempdf = ukb_data_cancer %>% filter(cancer_type == t)
  tempdf %>% 
    mutate(PTV_cancer_type_1 = cut(PTV_burden,
                            breaks = unique(q_tumor_spec[[t]][c("0%","20%", "80%", "100%")]),
                            include.lowest = TRUE)) %>% 
    mutate(PTV_cancer_type_2 = cut(PTV_burden,
                            breaks = unique(q_tumor_spec[[t]][c("0%","10%" ,"20%", "80%", "90%", "100%")]),
                            include.lowest = TRUE)) %>% 
    mutate(PTV_cancer_type_3 = cut(PTV_burden,
                            breaks = unique(q_tumor_spec[[t]][c("0%","5%" ,"6%", "94%", "95%", "100%")]),
                            include.lowest = TRUE)) %>%
    ungroup()
})
ukb_data_cancer = bind_rows(ukb_data_no_cancer, bind_rows(ukb_data_cancer_list))

#Tumor specific by histology group

tumors_hist = unique(ukb_data_cancer$hist_tumor_cat)
tumors_hist = tumors_hist[tumors_hist != "No_cancer"]
q_tumor_spec_hist = lapply(X = tumors_hist, FUN = function(x){
  ukb_data_cancer %>% 
    filter(hist_tumor_cat == x) %>% 
    select(eid, PTV_burden) %>% 
    unique() %>% 
    pull(PTV_burden) %>% 
    quantile(probs = seq(0, 1, 0.05))
})
names(q_tumor_spec_hist) = tumors_hist
q_tumor_spec_hist[["carcinoma"]][c("10%", "20%")]
#Add to ukb
cancer_data_list_hist = lapply(X = tumors_hist, FUN = function(t){
  tempdf = cancer_data %>% filter(hist_tumor_cat == t)
  tempdf %>% 
    mutate(PTV_hist_type_1 = cut(PTV_burden,
                                 breaks = unique(q_tumor_spec_hist[[t]][c("0%","20%", "80%", "100%")]),
                                 include.lowest = TRUE)) %>% 
    mutate(PTV_hist_type_2 = cut(PTV_burden,
                                 breaks = unique(q_tumor_spec_hist[[t]][c("0%","10%" ,"20%", "80%", "90%", "100%")]), include.lowest = TRUE)) %>% 
    mutate(PTV_hist_type_3 = cut(PTV_burden,
                                 breaks = unique(q_tumor_spec_hist[[t]][c("0%","5%" ,"6%", "94%", "95%", "100%")]), include.lowest = TRUE)) %>% 
    ungroup()
})
cancer_data = bind_rows(cancer_data_list_hist)

ukb_data_no_cancer = ukb_data_cancer %>% filter(hist_tumor_cat == "No_cancer")

ukb_data_no_cancer %<>% mutate(PTV_hist_type_1 = NA, PTV_hist_type_2 = NA, PTV_hist_type_3 = NA)

columns_to_convert = c("PTV_hist_type_1", "PTV_hist_type_2", "PTV_hist_type_3")

ukb_data_no_cancer = ukb_data_no_cancer %>%
  mutate(across(all_of(columns_to_convert), as.factor))
ukb_data_cancer_list_hist = lapply(X = tumors_hist, FUN = function(t){
  tempdf = ukb_data_cancer %>% filter(hist_tumor_cat == t)
  tempdf %>% 
    mutate(PTV_hist_type_1 = cut(PTV_burden,
                            breaks = unique(q_tumor_spec_hist[[t]][c("0%","20%", "80%", "100%")]),
                            include.lowest = TRUE)) %>% 
    mutate(PTV_hist_type_2 = cut(PTV_burden,
                            breaks = unique(q_tumor_spec_hist[[t]][c("0%","10%" ,"20%", "80%", "90%", "100%")]),
                            include.lowest = TRUE)) %>% 
    mutate(PTV_hist_type_3 = cut(PTV_burden,
                                 breaks = unique(q_tumor_spec_hist[[t]][c("0%","5%" ,"6%", "94%", "95%", "100%")]), include.lowest = TRUE)) %>% 
    ungroup()
})
ukb_data_cancer = rbind(ukb_data_no_cancer, bind_rows(ukb_data_cancer_list_hist))


save(q_tumor_spec, q_all, q_cancer, q_tumor_spec_hist, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/q_cut_off")



save(ukb_data_cancer, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")
save(cancer_data, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")

#UKB datas
#10%
percentiles = unique(quantile(ukb_data_cancer$PTV_burden, probs = seq(0, 1, by = 0.1), na.rm = TRUE))
ukb_data_cancer$PTV_perc_10 = cut(ukb_data_cancer$PTV_burden, breaks = percentiles, include.lowest = T, right = T)

#20%
percentiles = unique(quantile(ukb_data_cancer$PTV_burden, probs = seq(0, 1, by = 0.2), na.rm = TRUE))
ukb_data_cancer$PTV_perc_20 = cut(ukb_data_cancer$PTV_burden, breaks = percentiles, include.lowest = T, right = T)

#Cancer specific

tumor_PTV_per = lapply(X = unique(ukb_data_cancer$hist_tumor_cat), FUN = function(x){
  temp_df = subset(ukb_data_cancer, hist_tumor_cat == x)
  temp_df = dplyr::arrange(temp_df, diag_date)
  temp_df = temp_df[!duplicated(temp_df$eid), ]
  #temp_df$PTV_burden = as.numeric(temp_df$PTV_burden)
  percentiles = quantile(temp_df$PTV_burden, probs = seq(0, 1, by = 0.05), na.rm = TRUE)
  percentiles = unique(percentiles)
  temp_df$PTV_percent_5 = cut(temp_df$PTV_burden, breaks = percentiles, include.lowest = T, right = T)
  temp_df[, c("eid", "PTV_percent_5", "hist_tumor_cat")]
})

df_tumor_PTV_per = do.call(rbind, tumor_PTV_per)

ukb_data_cancer %<>% 
  left_join(df_tumor_PTV_per, by = c("eid", "hist_tumor_cat")) 



```



#PTV genes
```{r}
genetic_PTV = fread("C:/Users/bagil/Desktop/ukb/rawdata/MAF_1percent_all_retained_variants_PTVBurden_final_mapped.tsv")

colnames(genetic_PTV)[c(1,3)] = c("eid", "PTV_burden")
genetic_PTV_genes = genetic_PTV[,c("eid", "PTV_burden", "Genes", "Variants")]

ukb_data_cancer$PTV_burden_Genes = genetic_PTV_genes$Genes[fmatch(ukb_data_cancer$eid, genetic_PTV$eid)]
ukb_data_cancer$PTV_burden_var = genetic_PTV_genes$Variants[fmatch(ukb_data_cancer$eid, genetic_PTV_genes$eid)]

#P-value
pvalconvert = function(p) {
  if(p < 0.001) {
    tempnum = formatC(p, format = "e", digits = 1)
    out = c(strsplit(tempnum, split = "e")[[1]][1], as.numeric(strsplit(tempnum, split = "e")[[1]][2]))
  } else {
    out = round(p, 3)
  }
  out
}

```

#Antigene table
```{r}

library(xml2)
antigenPP = read_xml(x = "C:/Users/bagil/Desktop/ukb/rawdata/hsa04612.xml")
names = antigenPP %>% xml_find_all("//entry") %>% purrr::map_chr(~xml_attr(., "name"))
id = antigenPP %>% xml_find_all("//entry") %>% purrr::map_chr(~xml_attr(., "id"))
type = antigenPP %>% xml_find_all("//entry") %>% purrr::map_chr(~xml_attr(., "type"))
value = antigenPP %>% xml_find_all("//entry") %>% purrr::map_chr(~xml_attr(., "number"))
link = antigenPP %>% xml_find_all("//entry") %>% purrr::map_chr(~xml_attr(., "link"))
g_names = antigenPP %>% xml_find_all("//entry") %>% purrr::map_chr(~xml_attr(., "graphics name"))
antigenedf = data.frame(ID = id, Names = names, Type = type, Link = link)



```

#PTV and antigene
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/antigenedf")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/genetic_PTV_genes")



```

#PTV coef table:incidence from birth
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_g1")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_g2")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_g3")

cancer_PTV_coef = rbind(cancer_new_PTV_g1_df, cancer_new_PTV_g2_df, cancer_new_PTV_g3_df)

save(cancer_PTV_coef, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_combined")

```

#PTV coef table: incidence from attending
```{r}

load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_g1_attending")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_g2_attending")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_g3_attending")

cancer_new_PTV_coef_attending = rbind(cancer_new_PTV_g1_a_df, cancer_new_PTV_g2_a_df, cancer_new_PTV_g3_a_df)

save(cancer_new_PTV_coef_attending, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_attending_combined")

```

#PTV coef table: surv analysis
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_surv_g1")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_surv_g2")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_surv_g3")

cancer_PTV_coef_surv = rbind(cancer_new_PTV_surv_g1_df, cancer_new_PTV_surv_g2_df, cancer_new_PTV_surv_g3_df)

save(cancer_PTV_coef_surv, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_surv_combined")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_new_PTV_coef_surv_combined")

```

#PTV median
```{r}

load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/icd_mapping")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")

#Boxplot
ukb_data_cancer$cancer_type = as.factor(ukb_data_cancer$cancer_type)
ukb_data_cancer$cancer_type = fct_reorder(ukb_data_cancer$cancer_type, ukb_data_cancer$PTV_burden, .fun = function(x){quantile(x, 0.25)})

PTV_tumor_box = ggplot(ukb_data_cancer, aes(x = cancer_type, y = PTV_burden, color = cancer_type)) +
  geom_violin() +
  geom_boxplot(notch = T, width = 0.3) + 
  labs(title = "Number of PTV burden in tumors", x = "Tumor", y = "PTV") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
print(PTV_tumor_box)

ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/update_PTV_tumor_box.jpg", plot = PTV_tumor_box, width = 60, height = 30, units = "cm", dpi = 300)



#Median
ukb_data_cancer$PTV_burden_group = cut(ukb_data_cancer$PTV_burden, breaks = quantile(ukb_data_cancer$PTV_burden, probs = c(0, 0.5, 1), na.rm = T), labels = c("Low", "High"), include.lowest = T, right = T)

tumor_PTV_median = lapply(X = unique(icd_mapping$cancer_type), FUN = function(x){
  temp_df = subset(cancer_data, cancer_type == x)
  temp_df = dplyr::arrange(temp_df, diag_date)
  temp_df = temp_df[!duplicated(temp_df$eid), ]
  temp_df$PTV_burden_median = cut(temp_df$PTV_burden, breaks = quantile(temp_df$PTV_burden, probs = c(0, 0.5, 1), na.rm = T), labels = c("Low", "High"), include.lowest = T, right = T)
})


#%

cp = 5
cp = 10
cp = 15
cp = 20

ukb_data_cancer$cancer_type[is.na(ukb_data_cancer$cancer_type)] = "No_cancer"
tumor_PTV_per = lapply(X = unique(ukb_data_cancer$cancer_type), FUN = function(x){
  temp_df = subset(ukb_data_cancer, cancer_type == x)
  temp_df = dplyr::arrange(temp_df, diag_date)
  temp_df = temp_df[!duplicated(temp_df$eid), ]
  temp_df$PTV_burden_group = cut(temp_df$PTV_burden, breaks = quantile(temp_df$PTV_burden, probs = c(0, cp/100, 1-cp/100, 1), na.rm = T), labels = c("Low", "Medium", "High"), include.lowest = T, right = T)
  temp_df[, c("eid", "cancer_type", "PTV_burden", "PTV_burden_group")]
})

df_tumor_PTV_per = do.call(rbind, tumor_PTV_per)
#ukb_data_cancer = ukb_data_cancer[, 1:65]
ukb_data_cancer$PTV_burden = NULL
ukb_data_cancer$PTV_burden_group = NULL
ukb_data_cancer$PTV_burden_group_2 = NULL
ukb_data_cancer$PTV_burden_group_3 = NULL
ukb_data_cancer %<>% 
  left_join(df_tumor_PTV_per, by = c("eid", "cancer_type")) 


PTV_group_freq = df_tumor_PTV_per %>% 
  group_by(cancer_type, PTV_burden_group) %>% 
  summarise(patient_nb = n())

ggplot(PTV_group_freq, mapping = aes(x = cancer_type, y = patient_nb, fill = PTV_burden_group)) +
  geom_bar(stat = "identity", position = "fill")

save(ukb_data_cancer, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")


PTV_tumor_box_20per = ggplot(df_tumor_PTV_20per, aes(x = cancer_type, y = PTV_burden_group, color = cancer_type)) +
  geom_violin() +
  geom_boxplot(notch = T, width = 0.3) + 
  labs(title = "PTV groups in tumors", x = "Tumor", y = "PTV group") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
print(PTV_tumor_box_20per)

ggsave(filename = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/plots/PTV_tumor_box_20per.jpg", plot = PTV_tumor_box_20per, width = 60, height = 30, units = "cm", dpi = 300)

#cancer data

cp = 5
cp = 10
cp = 15
cp = 20

cancer_data$cancer_type[is.na(cancer_data$cancer_type)] = "No_cancer"
tumor_PTV_per = lapply(X = unique(cancer_data$cancer_type), FUN = function(x){
  temp_df = subset(cancer_data, cancer_type == x)
  temp_df = dplyr::arrange(temp_df, diag_date)
  temp_df = temp_df[!duplicated(temp_df$eid), ]
  temp_df$PTV_burden_group_20per = cut(temp_df$PTV_burden, breaks = quantile(temp_df$PTV_burden, probs = c(0, cp/100, 1-cp/100, 1), na.rm = T), labels = c("Low", "Medium", "High"), include.lowest = T, right = T)
  temp_df[, c("eid", "cancer_type", "PTV_burden", "PTV_burden_group_20per")]
})

df_tumor_PTV_per = do.call(rbind, tumor_PTV_per)
#cancer_data = cancer_data[, 1:65]
cancer_data$PTV_burden = NULL
cancer_data$PTV_burden_group = NULL
cancer_data$PTV_burden_group_2 = NULL
cancer_data$PTV_burden_group_3 = NULL
cancer_data %<>% 
  left_join(df_tumor_PTV_per, by = c("eid", "cancer_type")) 


PTV_group_freq = df_tumor_PTV_per %>% 
  group_by(cancer_type, PTV_burden_group) %>% 
  summarise(patient_nb = n())

save(cancer_data, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")


```

#Tumor groups
```{r}
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")
ICD_table = read_xlsx("C:/Users/bagil/Desktop/ukb/Section111ValidICD10-Jan2023-DupFixed.xlsx")
type_of_cancer = read.table("C:/Users/bagil/Desktop/ukb/rawdata/40006.txt", header = T) #40006
histology = read_xlsx("C:/Users/bagil/Desktop/ukb/sitetype.icdo3.d20220429.xlsx")
histology_of_cancer = read.table("C:/Users/bagil/Desktop/ukb/rawdata/40011.txt", header = T) #40011 

categorize_cancer <- function(description) {
  if (grepl("carcinoma", tolower(description))) {
    return("carcinoma")
  } else if (grepl("sarcoma", tolower(description))) {
    return("sarcoma")
  } else if (grepl("myeloma", tolower(description))) {
    return("myeloma")
  } else if (grepl("leukemia", tolower(description))) {
    return("leukemia")
  } else if (grepl("lymphoma", tolower(description))) {
    return("lymphoma")
  } else {
    return("other")
  }
}

#ICD10
ICD_table$tumor_cat = sapply(ICD_table$`LONG DESCRIPTION (VALID ICD-10 FY2023)`, categorize_cancer) 
ICD_map_tumor_cat = ICD_table[, c(1, ncol(ICD_table))]
ICD_map_tumor_cat$short_code = substr(ICD_map_tumor_cat$CODE, 1, 4)
#type_of_cancer$short_code = substr(type_of_cancer$value, 1, 4)
type_of_cancer = type_of_cancer[, c(1, 3)]
ICD_map_tumor_cat = ICD_map_tumor_cat[, c(2, 3)]

rm(ICD_table, ICD_map_tumor)

ICD_mapping_fin = full_join(ICD_map_tumor_cat, type_of_cancer, by = c("short_code" = "value"))
ICD_mapping_fin$tumor_cat[is.na(ICD_mapping_fin$tumor_cat)] = "other"

#ICD_mapping_fin_unique <- ICD_mapping_fin %>% 
  #group_by(eid) %>% 
  #slice(1) %>% 
  #ungroup()

cancer_data$tumor_cat = ICD_mapping_fin$tumor_cat[fmatch(cancer_data$eid, ICD_mapping_fin$eid)]
ukb_data_cancer$tumor_cat = ICD_mapping_fin$tumor_cat[fmatch(ukb_data_cancer$eid, ICD_mapping_fin$eid, nomatch = NA)]
ukb_data_cancer$tumor_cat[is.na(ukb_data_cancer$tumor_cat)] = "No_cancer"

#Histology
histology$tumor_cat = sapply(histology$`Histology/Behavior Description`, categorize_cancer)
histology$`Histology/Behavior` = strsplit(histology$`Histology/Behavior`, "/")
histology$`Histology/Behavior` = sapply(histology$`Histology/Behavior`, function(x) x[1])
histology_map_tumor_cat = histology[, c(5, ncol(histology))]
colnames(histology_map_tumor_cat)[1] = "hist_code"
colnames(histology_of_cancer)[3] = "hist_code"
histology_of_cancer$hist_code = as.character(histology_of_cancer$hist_code)

#Mapping table whit eid
hist_tumor_cat_fin = full_join(histology_map_tumor_cat, histology_of_cancer, by = c("hist_code"))
hist_tumor_cat_fin$tumor_cat[is.na(hist_tumor_cat_fin$tumor_cat)] = "other"
rm(histology, histology_map_tumor_cat, histology_of_cancer)

#Tumor categories by histology
cancer_data$hist_tumor_cat = hist_tumor_cat_fin$tumor_cat[fmatch(cancer_data$eid, hist_tumor_cat_fin$eid)]
ukb_data_cancer$hist_tumor_cat = hist_tumor_cat_fin$tumor_cat[fmatch(ukb_data_cancer$eid, hist_tumor_cat_fin$eid)]
ukb_data_cancer$hist_tumor_cat[is.na(ukb_data_cancer$hist_tumor_cat)] = "No_cancer"

cancer_data$tumor_cat = NULL
ukb_data_cancer$tumor_cat = NULL
save(cancer_data, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/cancer_data_final")
save(ukb_data_cancer, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_cancer_final")



```

