---
title: "Wikipathway_beta"
author: "Bagi Laura"
date: "2025-01-06"
output: html_document
---

#Libraries
```{r}

#if (!require("BiocManager", quietly = TRUE))
    #install.packages("BiocManager")

#BiocManager::install("rWikiPathways")
#BiocManager::install("RCy3")

library(RCy3)
library(rWikiPathways)
library(ggpubr)
library(fastmatch)
library(readxl)
library(forcats)
library(survival)
library(survminer)
library(grid)
library(gridExtra)
library(data.table)
library(caret)
library(tidyverse)
library(magrittr)
library(tidycmprsk)
library(ggsurvfit)
library(patchwork)
library(cowplot)
library(gt)
library(gtsummary)
library(devtools)
library(pbapply)
library(broom)
library(pheatmap)
library(RColorBrewer)
library(circlize)
library(dendsort)
library(forestmodel)
options(dplyr.summarise.inform = F)

#remove.packages(c("survminer", "data.table"))
#install.packages('Rcpp', dependencies = TRUE)
#install.packages('survminer', dependencies = TRUE)
#install.packages('data.table', dependencies = TRUE)

```

#Dataset
```{r}

load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/ukb_data_ptv")
ukb_data$caucasian = factor(ukb_data$caucasian, levels = c(0,1), labels = c("not_caucasian", "caucasian"))
ukb_data = ukb_data %>% 
  filter(caucasian == "caucasian")
genetic_PTV = fread("C:/Users/bagil/Desktop/ukb/rawdata/MAF_1percent_all_retained_variants_PTVBurden_final_mapped.tsv")

colnames(genetic_PTV)[c(1,3)] = c("eid", "PTV_burden_MAF")
genetic_PTV = genetic_PTV[,c("eid", "PTV_burden_MAF", "Genes")]

```

#Setups
```{r}

#Data frame 
tumorous = ukb_data[,c("eid", "cancer_type")]
tumorous = tumorous %>%  left_join(genetic_PTV, by = "eid")  
rm(ukb_data, genetic_PTV)

#Lists
tumors = sort(unique(tumorous$cancer_type))
tumors = tumors[!(tumors %in% c("Benign", "Hydatidiform_mole", "No_cancer", "other", "undef"))]

gene_list = c("WDFY4", "CTSH", "GBA1", "RAB32", "RAB34", "CLEC4M", "RAB4A", "CD8A")


```

#Pathway
```{r}
#List organism
listOrganisms()

#Homo sapiens pathways
hs.pathways <- listPathways('Homo sapiens')
hs.pathways #WP+number -> wikipathway code
?listPathways
length(hs.pathways)
?listPathwayIds

#Specific gene pathways
#Df
wdf4.pathways <- findPathwaysByXref()
rab34.pathways <- findPathwaysByXref("RAB34", "H") 
rab4a_pw = findPathwaysByXref("RAB4A", "H")
cd8a_pw = findPathwaysByXref("CD8A", "H")
#lists
clec4m_pathways = findPathwayIdsByXref("CLEC4M", "H")
ctsh_pw = findPathwayIdsByXref("CTSH", "H") #empty
gba1_pw = findPathwayIdsByXref("GBA1", "H") #empty
rab32_pw = findPathwayIdsByXref("RAB32", "H") #empty


#Tumor pathways
tumor_pathways = findPathwaysByText(query = "cancer")
immun_pw = findPathwaysByText(query = "immun")
antigene_pw = findPathwaysByText(query = "antigen", field = "description")
tumirim_pw = findPathwaysByText(query = "antitumor immunity")
melanoma_pw = findPathwaysByText(query = "melanoma")
hs_pw = findPathwaysByText(query = "Homo sapiens")

save(hs_pw, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/hs_pw")
save(antigene_pw, file = "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/antigene_pw")

#get pw info
getPathwayInfo(pathway = "WP1067")

#Vizualize with cytoscape
#Connecting with cytoscape
cytoscapePing()
#Pathway
RCy3::commandsRun('wikipathways import-as-pathway id=WP5352') 


```


```{r}

load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/hs_pw")
load("C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/antigene_pw")
antigene_pw = filter(antigene_pw, species == "Homo sapiens")
hs_rwpw = hs_pw[, c(1,3,7,8)]
antigene_rwpw = antigene_pw[, c(1,3,7,8)]
rm(hs_pw, antigene_pw)

save(hs_rwpw, file =  "C:/Users/bagil/Desktop/MyGit/ukb_tumor/objects/hs_rwpw")

#List genes
genlist = lapply(antigene_rwpw$datanodes, function(x) strsplit(x, ",")[[1]])
genlist[[1]]

#PW infos
gen_inf = findPathwaysByXref(identifier = "MAP2K1", systemCode = "H")
 #or
gen_inf2 = findPathwayIdsByXref()

#HLA
hla_pw = hs_rwpw %>% filter(grepl("HLA", datanodes, ignore.case = T))

```

```{r}

TICCom = read.csv("C:/Users/bagil/Desktop/ukb/Experimentally_verified_TIC_communication2.csv", header = T, sep = ";", stringsAsFactors = F)
load()



```

